import {
  registerUser,
  loginUser,
  logoutUser,
  verifyUserEmail,
  sendPasswordResetEmail,
  resetPassword,
  getCurrentUser,
  updateUserProfile,
  changeUserPassword,
  getInstructorList,
  getInstructorBySlug,
  adminGetAllUsers,
  adminUpdateUser,
} from "./auth.service";
import {
  createCourse,
  updateCourse,
  deleteCourse,
  getCourseBySlug,
  getCourseById,
  listCourses,
  getInstructorCourses,
  submitCourseForReview,
  adminUpdateCourseStatus,
  getRelatedCourses,
  getPopularCourses,
  getFeaturedCourses,
  getNewestCourses,
  createCategory,
  getAllCategories,
  getCategoryBySlug,
} from "./course.service";
import {
  createModule,
  updateModule,
  deleteModule,
  getCourseCurriculum,
  reorderModules,
  createLesson,
  updateLesson,
  deleteLesson,
  reorderLessons,
  getLessonById,
  getAdjacentLessons,
} from "./content.service";
import {
  createEnrollment,
  getStudentEnrollments,
  getEnrollment,
  getCourseStudents,
  updateLessonProgress,
  getCourseProgress,
  issueCertificate,
  verifyCertificate,
  getStudentCertificates,
  getCertificateById,
  adminGetAllEnrollments,
} from "./enrollment.service";
import {
  createQuiz,
  updateQuiz,
  deleteQuiz,
  getQuizById,
  addQuestion,
  updateQuestion,
  deleteQuestion,
  submitQuizAttempt,
  startQuizAttempt,
  getStudentQuizAttempts,
  getQuizAttempt,
  getCourseQuizzes,
  getStudentQuizzes,
} from "./quiz.service";
import {
  createAssignment,
  updateAssignment,
  deleteAssignment,
  getAssignmentById,
  getCourseAssignments,
  getInstructorAssignments,
  submitAssignment,
  gradeSubmission,
  getAssignmentSubmissions,
  getStudentSubmissions,
  getStudentAssignmentSubmission,
  getStudentAssignments,
} from "./assignment.service";
import {
  validateCoupon,
  calculateCouponDiscount,
  createOrder,
  verifyPayment,
  handleRazorpayWebhook,
  createCoupon,
  updateCoupon,
  getAllCoupons,
  createReview,
  getCourseReviews,
  getWishlist,
  addToWishlist,
  removeFromWishlist,
  isInWishlist,
  refundOrder,
  adminGetAllOrders,
  getStudentOrders,
  getPlatformAnalytics,
} from "./payment.service";

export const authService = {
  register: registerUser,
  login: loginUser,
  logout: logoutUser,
  verifyEmail: verifyUserEmail,
  forgotPassword: sendPasswordResetEmail,
  resetPassword,
  getCurrentUser,
  updateProfile: updateUserProfile,
  changePassword: changeUserPassword,
  getInstructors: getInstructorList,
  getInstructor: getInstructorBySlug,
  adminGetAllUsers,
  adminUpdateUser,
};

export const courseService = {
  create: createCourse,
  update: updateCourse,
  delete: deleteCourse,
  getBySlug: getCourseBySlug,
  getById: getCourseById,
  list: listCourses,
  getInstructorCourses,
  submitForReview: submitCourseForReview,
  adminUpdateStatus: adminUpdateCourseStatus,
  getRelated: getRelatedCourses,
  getPopular: getPopularCourses,
  getFeatured: getFeaturedCourses,
  getNewest: getNewestCourses,
  createCategory,
  getAllCategories,
  getCategoryBySlug,
};

export const contentService = {
  createModule,
  updateModule,
  deleteModule,
  getCourseCurriculum,
  reorderModules,
  createLesson,
  updateLesson,
  deleteLesson,
  reorderLessons,
  getLessonById,
  getAdjacentLessons,
};

export const enrollmentService = {
  create: createEnrollment,
  getStudentEnrollments,
  get: getEnrollment,
  getCourseStudents,
  updateProgress: updateLessonProgress,
  getProgress: getCourseProgress,
  issueCertificate,
  verifyCertificate,
  getStudentCertificates,
  getCertificateById,
  adminGetAll: adminGetAllEnrollments,
};

export const quizService = {
  create: createQuiz,
  update: updateQuiz,
  delete: deleteQuiz,
  getById: getQuizById,
  addQuestion,
  updateQuestion,
  deleteQuestion,
  submitAttempt: submitQuizAttempt,
  startAttempt: startQuizAttempt,
  getStudentAttempts: getStudentQuizAttempts,
  getAttempt: getQuizAttempt,
  getCourseQuizzes,
  getStudentQuizzes,
};

export const assignmentService = {
  create: createAssignment,
  update: updateAssignment,
  delete: deleteAssignment,
  getById: getAssignmentById,
  getCourseAssignments,
  getInstructorAssignments,
  submit: submitAssignment,
  grade: gradeSubmission,
  getSubmissions: getAssignmentSubmissions,
  getStudentSubmissions,
  getStudentSubmission: getStudentAssignmentSubmission,
  getStudentAssignments,
};

export const paymentService = {
  validateCoupon,
  calculateDiscount: calculateCouponDiscount,
  createOrder,
  verifyPayment,
  handleWebhook: handleRazorpayWebhook,
  createCoupon,
  updateCoupon,
  getAllCoupons,
  createReview,
  getCourseReviews,
  getWishlist,
  addToWishlist,
  removeFromWishlist,
  isInWishlist,
  refundOrder,
  adminGetAllOrders,
  getStudentOrders,
  getPlatformAnalytics,
};

const serviceIndex = {
  auth: authService,
  course: courseService,
  content: contentService,
  enrollment: enrollmentService,
  quiz: quizService,
  assignment: assignmentService,
  payment: paymentService,
};

export default serviceIndex;
