export const adminReviews = [
  {
    id: "review-001",
    reviewId: "REV-EDU-10245",
    studentId: "stu-001",
    studentName: "Rahul Sharma",
    studentEmail: "rahul@example.com",
    courseId: "course-001",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    enrollmentId: "ENR-2026-00451",
    rating: 5,
    review:
      "Excellent course with practical examples and clear explanations. The projects helped me build confidence quickly and the mentor support was genuinely useful.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-10-02",
    updatedAt: "2026-10-02",
    helpfulVotes: 42,
    notHelpfulVotes: 3,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-002",
    reviewId: "REV-EDU-10246",
    studentId: "stu-002",
    studentName: "Aisha Khan",
    studentEmail: "aisha@example.com",
    courseId: "course-002",
    courseName: "React for Modern Web Apps",
    instructorId: "inst-002",
    instructorName: "Sarah Ahmed",
    enrollmentId: "ENR-2026-00472",
    rating: 4,
    review:
      "Solid course overall. The curriculum is well structured and covers real-world React patterns. I would like a little more depth on advanced state management.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-10-01",
    updatedAt: "2026-10-01",
    helpfulVotes: 31,
    notHelpfulVotes: 5,
    reportCount: 0,
    reports: [],
    instructorResponse: "Thanks for the feedback. We are expanding advanced state management examples in the next update.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-003",
    reviewId: "REV-EDU-10247",
    studentId: "stu-003",
    studentName: "Daniel Wilson",
    studentEmail: "daniel@example.com",
    courseId: "course-003",
    courseName: "Digital Marketing Masterclass",
    instructorId: "inst-003",
    instructorName: "Emily Carter",
    enrollmentId: "ENR-2026-00488",
    rating: 5,
    review:
      "Everything is explained in a practical way. The ad strategy and analytics lessons were especially useful for my marketing job.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-09-27",
    updatedAt: "2026-09-28",
    helpfulVotes: 57,
    notHelpfulVotes: 4,
    reportCount: 1,
    reports: [
      {
        id: "rep-301",
        reason: "Misleading information",
        reportedDate: "2026-09-29",
        reporterType: "student",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: "admin-01",
    reviewedAt: "2026-09-29",
  },
  {
    id: "review-004",
    reviewId: "REV-EDU-10248",
    studentId: "stu-004",
    studentName: "Meera Patel",
    studentEmail: "meera@example.com",
    courseId: "course-004",
    courseName: "UI/UX Design Fundamentals",
    instructorId: "inst-004",
    instructorName: "Olivia Brooks",
    enrollmentId: "ENR-2026-00500",
    rating: 3,
    review:
      "The content is okay but I expected more case studies and portfolio guidance. Some sections felt repetitive and could use stronger structure.",
    reviewType: "course",
    status: "pending",
    createdAt: "2026-10-02",
    updatedAt: "2026-10-02",
    helpfulVotes: 12,
    notHelpfulVotes: 9,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-005",
    reviewId: "REV-EDU-10249",
    studentId: "stu-005",
    studentName: "Lucas Green",
    studentEmail: "lucas@example.com",
    courseId: "course-005",
    courseName: "Data Science Essentials",
    instructorId: "inst-005",
    instructorName: "Maya Singh",
    enrollmentId: "ENR-2026-00506",
    rating: 4,
    review:
      "Good content and neat organization. The notebook examples were helpful, but I wanted more on model evaluation and deployment.",
    reviewType: "course",
    status: "reported",
    createdAt: "2026-09-22",
    updatedAt: "2026-09-25",
    helpfulVotes: 18,
    notHelpfulVotes: 7,
    reportCount: 3,
    reports: [
      {
        id: "rep-302",
        reason: "Offensive language",
        reportedDate: "2026-09-23",
        reporterType: "student",
        status: "open",
      },
      {
        id: "rep-303",
        reason: "Spam",
        reportedDate: "2026-09-24",
        reporterType: "instructor",
        status: "open",
      },
      {
        id: "rep-304",
        reason: "Misleading information",
        reportedDate: "2026-09-25",
        reporterType: "admin",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: "Multiple reports require review.",
    reviewedBy: "admin-02",
    reviewedAt: "2026-09-25",
  },
  {
    id: "review-006",
    reviewId: "REV-EDU-10250",
    studentId: "stu-006",
    studentName: "Priya Nair",
    studentEmail: "priya@example.com",
    courseId: "course-006",
    courseName: "Python for Data Analysis",
    instructorId: "inst-006",
    instructorName: "James Patel",
    enrollmentId: "ENR-2026-00512",
    rating: 5,
    review:
      "The course is very clear and beginner friendly. I appreciated the step-by-step walkthroughs and practical assignments.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-09-19",
    updatedAt: "2026-09-20",
    helpfulVotes: 68,
    notHelpfulVotes: 4,
    reportCount: 0,
    reports: [],
    instructorResponse: "Glad to hear the walkthroughs were helpful. Keep building with Python!",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-007",
    reviewId: "REV-EDU-10251",
    studentId: "stu-007",
    studentName: "Noah Brown",
    studentEmail: "noah@example.com",
    courseId: "course-007",
    courseName: "Business Analytics Bootcamp",
    instructorId: "inst-007",
    instructorName: "Emma Walker",
    enrollmentId: "ENR-2026-00518",
    rating: 2,
    review:
      "The basics were okay but the course feels rushed in later modules. I had to do extra research outside the course to complete some assignments.",
    reviewType: "course",
    status: "hidden",
    createdAt: "2026-09-14",
    updatedAt: "2026-09-17",
    helpfulVotes: 9,
    notHelpfulVotes: 14,
    reportCount: 2,
    reports: [
      {
        id: "rep-305",
        reason: "Off-topic",
        reportedDate: "2026-09-15",
        reporterType: "student",
        status: "reviewed",
      },
      {
        id: "rep-306",
        reason: "Spam",
        reportedDate: "2026-09-16",
        reporterType: "course-manager",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: "User concerns about content depth were reviewed and hidden temporarily.",
    reviewedBy: "admin-03",
    reviewedAt: "2026-09-17",
  },
  {
    id: "review-008",
    reviewId: "REV-EDU-10252",
    studentId: "stu-008",
    studentName: "Sofia Martinez",
    studentEmail: "sofia@example.com",
    courseId: "course-008",
    courseName: "AWS Cloud Foundations",
    instructorId: "inst-008",
    instructorName: "Daniel Lee",
    enrollmentId: "ENR-2026-00522",
    rating: 5,
    review:
      "This is one of the best cloud courses I've taken. The labs were practical and the explanations were easy to follow.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-09-09",
    updatedAt: "2026-09-10",
    helpfulVotes: 44,
    notHelpfulVotes: 2,
    reportCount: 0,
    reports: [],
    instructorResponse: "Appreciate the feedback. We are adding more guided labs to keep the path hands-on.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-009",
    reviewId: "REV-EDU-10253",
    studentId: "stu-009",
    studentName: "Ethan Lee",
    studentEmail: "ethan@example.com",
    courseId: "course-009",
    courseName: "Machine Learning for Beginners",
    instructorId: "inst-009",
    instructorName: "Isabella Moore",
    enrollmentId: "ENR-2026-00531",
    rating: 4,
    review:
      "The course has strong fundamentals and practical examples, though some parts were slightly too fast for a beginner schedule.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-09-04",
    updatedAt: "2026-09-05",
    helpfulVotes: 36,
    notHelpfulVotes: 6,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-010",
    reviewId: "REV-EDU-10254",
    studentId: "stu-010",
    studentName: "Harper Allen",
    studentEmail: "harper@example.com",
    courseId: "course-010",
    courseName: "Cybersecurity Essentials",
    instructorId: "inst-010",
    instructorName: "Benjamin Ross",
    enrollmentId: "ENR-2026-00539",
    rating: 1,
    review:
      "Very generic content with outdated examples. I did not feel that the course matched current industry practice.",
    reviewType: "instructor",
    status: "rejected",
    createdAt: "2026-08-29",
    updatedAt: "2026-08-30",
    helpfulVotes: 3,
    notHelpfulVotes: 18,
    reportCount: 5,
    reports: [
      {
        id: "rep-307",
        reason: "Fake review",
        reportedDate: "2026-08-29",
        reporterType: "student",
        status: "open",
      },
      {
        id: "rep-308",
        reason: "Spam",
        reportedDate: "2026-08-30",
        reporterType: "course-manager",
        status: "closed",
      },
      {
        id: "rep-309",
        reason: "Offensive content",
        reportedDate: "2026-08-30",
        reporterType: "admin",
        status: "closed",
      },
    ],
    instructorResponse: null,
    moderationReason: "Review rejected due to unsupported criticism and duplicated reports.",
    reviewedBy: "admin-04",
    reviewedAt: "2026-08-30",
  },
  {
    id: "review-011",
    reviewId: "REV-EDU-10255",
    studentId: "stu-011",
    studentName: "Liam Davis",
    studentEmail: "liam@example.com",
    courseId: "course-001",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    enrollmentId: "ENR-2026-00544",
    rating: 5,
    review:
      "This course gave me the confidence to switch careers. The structure, assignments, and project-based learning were excellent.",
    reviewType: "instructor",
    status: "published",
    createdAt: "2026-08-21",
    updatedAt: "2026-08-22",
    helpfulVotes: 49,
    notHelpfulVotes: 2,
    reportCount: 0,
    reports: [],
    instructorResponse: "Amazing to hear. I am glad the course helped transform your career path.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-012",
    reviewId: "REV-EDU-10256",
    studentId: "stu-012",
    studentName: "Zoe Chen",
    studentEmail: "zoe@example.com",
    courseId: "course-011",
    courseName: "SEO Growth Toolkit",
    instructorId: "inst-011",
    instructorName: "Alicia Turner",
    enrollmentId: "ENR-2026-00550",
    rating: 4,
    review:
      "Covers useful topics and explains strategy in a practical way. I would love more exercises on local SEO and technical audits.",
    reviewType: "course",
    status: "pending",
    createdAt: "2026-09-28",
    updatedAt: "2026-09-28",
    helpfulVotes: 23,
    notHelpfulVotes: 4,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-013",
    reviewId: "REV-EDU-10257",
    studentId: "stu-013",
    studentName: "Avery Scott",
    studentEmail: "avery@example.com",
    courseId: "course-012",
    courseName: "Product Management Launchpad",
    instructorId: "inst-012",
    instructorName: "Michael Green",
    enrollmentId: "ENR-2026-00557",
    rating: 5,
    review:
      "Very practical and insightful. The frameworks and product examples were incredibly helpful for my interviews and day-to-day role.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-09-01",
    updatedAt: "2026-09-01",
    helpfulVotes: 58,
    notHelpfulVotes: 2,
    reportCount: 0,
    reports: [],
    instructorResponse: "Thank you! We are adding more product strategy templates in the next update.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-014",
    reviewId: "REV-EDU-10258",
    studentId: "stu-014",
    studentName: "Mason Hall",
    studentEmail: "mason@example.com",
    courseId: "course-013",
    courseName: "Leadership and Team Management",
    instructorId: "inst-013",
    instructorName: "Sophia Clark",
    enrollmentId: "ENR-2026-00564",
    rating: 3,
    review:
      "Some chapters were useful, but the course felt dependent on a lot of external reading. I wanted more direct examples from real managers.",
    reviewType: "instructor",
    status: "published",
    createdAt: "2026-08-16",
    updatedAt: "2026-08-17",
    helpfulVotes: 27,
    notHelpfulVotes: 9,
    reportCount: 1,
    reports: [
      {
        id: "rep-310",
        reason: "Misleading information",
        reportedDate: "2026-08-17",
        reporterType: "student",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: "admin-02",
    reviewedAt: "2026-08-17",
  },
  {
    id: "review-015",
    reviewId: "REV-EDU-10259",
    studentId: "stu-015",
    studentName: "Charlotte King",
    studentEmail: "charlotte@example.com",
    courseId: "course-014",
    courseName: "AI Prompt Engineering",
    instructorId: "inst-014",
    instructorName: "Liam Parker",
    enrollmentId: "ENR-2026-00570",
    rating: 5,
    review:
      "Phenomenal course. The prompt techniques are practical, reusable, and explained with enough examples to apply immediately.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-08-12",
    updatedAt: "2026-08-12",
    helpfulVotes: 63,
    notHelpfulVotes: 3,
    reportCount: 0,
    reports: [],
    instructorResponse: "Happy to hear it. We will keep adding prompt frameworks to the library.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-016",
    reviewId: "REV-EDU-10260",
    studentId: "stu-016",
    studentName: "Jayden Walker",
    studentEmail: "jayden@example.com",
    courseId: "course-015",
    courseName: "SQL for Analysts",
    instructorId: "inst-015",
    instructorName: "Grace Lopez",
    enrollmentId: "ENR-2026-00578",
    rating: 2,
    review:
      "The course starts strong but ends too abruptly. I was left wanting clearer explanations for advanced joins and window functions.",
    reviewType: "course",
    status: "reported",
    createdAt: "2026-10-01",
    updatedAt: "2026-10-01",
    helpfulVotes: 11,
    notHelpfulVotes: 10,
    reportCount: 2,
    reports: [
      {
        id: "rep-311",
        reason: "Spam",
        reportedDate: "2026-10-01",
        reporterType: "student",
        status: "open",
      },
      {
        id: "rep-312",
        reason: "Off-topic",
        reportedDate: "2026-10-01",
        reporterType: "admin",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: "Submitted report indicates review may be spam-related.",
    reviewedBy: "admin-01",
    reviewedAt: "2026-10-01",
  },
  {
    id: "review-017",
    reviewId: "REV-EDU-10261",
    studentId: "stu-017",
    studentName: "Ella Perez",
    studentEmail: "ella@example.com",
    courseId: "course-016",
    courseName: "Introduction to Finance",
    instructorId: "inst-016",
    instructorName: "Henry Baker",
    enrollmentId: "ENR-2026-00586",
    rating: 4,
    review:
      "This course gave me a solid foundation in finance basics. I especially liked the budgeting and valuation chapters.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-08-03",
    updatedAt: "2026-08-04",
    helpfulVotes: 39,
    notHelpfulVotes: 5,
    reportCount: 0,
    reports: [],
    instructorResponse: "Great to hear. We will continue to expand practical examples in the core modules.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-018",
    reviewId: "REV-EDU-10262",
    studentId: "stu-018",
    studentName: "Oscar Reed",
    studentEmail: "oscar@example.com",
    courseId: "course-017",
    courseName: "Career Growth Playbook",
    instructorId: "inst-017",
    instructorName: "Rachel Young",
    enrollmentId: "ENR-2026-00590",
    rating: 4,
    review:
      "Useful material with clear guidance on job search strategy. The templates and exercises were practical and motivating.",
    reviewType: "instructor",
    status: "pending",
    createdAt: "2026-09-17",
    updatedAt: "2026-09-17",
    helpfulVotes: 20,
    notHelpfulVotes: 4,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-019",
    reviewId: "REV-EDU-10263",
    studentId: "stu-019",
    studentName: "Penelope Hill",
    studentEmail: "penelope@example.com",
    courseId: "course-018",
    courseName: "Motion Design Bootcamp",
    instructorId: "inst-018",
    instructorName: "Victoria Adams",
    enrollmentId: "ENR-2026-00599",
    rating: 5,
    review:
      "Highly recommended for creatives. The lessons are polished, and the animation exercises make the learning process engaging.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-07-28",
    updatedAt: "2026-07-29",
    helpfulVotes: 48,
    notHelpfulVotes: 1,
    reportCount: 0,
    reports: [],
    instructorResponse: "Thanks a lot. The creative walkthroughs are tuned for hands-on practice.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-020",
    reviewId: "REV-EDU-10264",
    studentId: "stu-020",
    studentName: "Benjamin Clark",
    studentEmail: "benjamin@example.com",
    courseId: "course-019",
    courseName: "Project Planning Fundamentals",
    instructorId: "inst-019",
    instructorName: "Nathan Hughes",
    enrollmentId: "ENR-2026-00604",
    rating: 4,
    review:
      "A clear and useful course for project managers. The templates and milestone planning lessons were valuable in my work.",
    reviewType: "course",
    status: "hidden",
    createdAt: "2026-09-26",
    updatedAt: "2026-09-27",
    helpfulVotes: 18,
    notHelpfulVotes: 8,
    reportCount: 1,
    reports: [
      {
        id: "rep-313",
        reason: "Duplicate",
        reportedDate: "2026-09-27",
        reporterType: "student",
        status: "reviewed",
      },
    ],
    instructorResponse: null,
    moderationReason: "Duplicate report triaged and review hidden for admin review.",
    reviewedBy: "admin-05",
    reviewedAt: "2026-09-27",
  },
  {
    id: "review-021",
    reviewId: "REV-EDU-10265",
    studentId: "stu-021",
    studentName: "Riley Hill",
    studentEmail: "riley@example.com",
    courseId: "course-020",
    courseName: "Mobile App Design Systems",
    instructorId: "inst-020",
    instructorName: "Chloe Martin",
    enrollmentId: "ENR-2026-00612",
    rating: 5,
    review:
      "The system design lessons and practical design critiques helped me improve my workflow dramatically. This was excellent value.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-07-11",
    updatedAt: "2026-07-11",
    helpfulVotes: 72,
    notHelpfulVotes: 4,
    reportCount: 0,
    reports: [],
    instructorResponse: "Thank you! We are building more design critique templates for the next cohort.",
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-022",
    reviewId: "REV-EDU-10266",
    studentId: "stu-022",
    studentName: "Carter Johnson",
    studentEmail: "carter@example.com",
    courseId: "course-021",
    courseName: "Advanced Excel for Analysts",
    instructorId: "inst-021",
    instructorName: "Isla Roberts",
    enrollmentId: "ENR-2026-00618",
    rating: 3,
    review:
      "Good basics, but it did not dive deep enough into formulas and dashboard design for advanced analysts.",
    reviewType: "course",
    status: "rejected",
    createdAt: "2026-09-20",
    updatedAt: "2026-09-21",
    helpfulVotes: 9,
    notHelpfulVotes: 11,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: "Review rejected due to incomplete context and request for manual moderation.",
    reviewedBy: "admin-03",
    reviewedAt: "2026-09-21",
  },
  {
    id: "review-023",
    reviewId: "REV-EDU-10267",
    studentId: "stu-023",
    studentName: "Layla Garcia",
    studentEmail: "layla@example.com",
    courseId: "course-022",
    courseName: "Content Strategy Lab",
    instructorId: "inst-022",
    instructorName: "David White",
    enrollmentId: "ENR-2026-00626",
    rating: 5,
    review:
      "Exceptional strategy guidance and content planning examples. I used the frameworks immediately in my content role.",
    reviewType: "course",
    status: "published",
    createdAt: "2026-06-28",
    updatedAt: "2026-06-29",
    helpfulVotes: 52,
    notHelpfulVotes: 2,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
  {
    id: "review-024",
    reviewId: "REV-EDU-10268",
    studentId: "stu-024",
    studentName: "Nathan Price",
    studentEmail: "nathan@example.com",
    courseId: "course-023",
    courseName: "Modern Sales Strategy",
    instructorId: "inst-023",
    instructorName: "Jennifer Hill",
    enrollmentId: "ENR-2026-00634",
    rating: 4,
    review:
      "The framework was strong and the sales process examples were relevant. I wanted slightly more focus on enterprise sales.",
    reviewType: "course",
    status: "pending",
    createdAt: "2026-09-30",
    updatedAt: "2026-09-30",
    helpfulVotes: 17,
    notHelpfulVotes: 3,
    reportCount: 0,
    reports: [],
    instructorResponse: null,
    moderationReason: null,
    reviewedBy: null,
    reviewedAt: null,
  },
];

export default adminReviews;
