export const initialAdminSettings = {
  general: {
    platformName: "EduLearn",
    platformDescription: "Professional online learning platform for students and instructors.",
    supportEmail: "support@edulearn.example",
    supportPhone: "+91 00000 00000",
    language: "English",
    currency: "INR",
    timezone: "Asia/Kolkata",
    dateFormat: "DD/MM/YYYY",
    timeFormat: "12 Hour",
    maintenanceMode: false,
  },
  branding: {
    logoPreview: null,
    faviconPreview: null,
    primaryColor: "#024AD8",
    secondaryColor: "#0F3D91",
    footerCopyright: "© 2026 EduLearn. All rights reserved.",
  },
  users: {
    allowStudentRegistration: true,
    allowInstructorRegistration: true,
    requireEmailVerification: true,
    allowGuestPreview: true,
    allowMultipleSessions: true,
    defaultRole: "Student",
    instructorApproval: true,
    showUserActivity: true,
  },
  courses: {
    requireApproval: true,
    allowPublishing: false,
    enableReviews: true,
    enableWishlist: true,
    allowFreeCourses: true,
    allowPreview: true,
    maxTitleLength: 100,
    maxDescriptionLength: 5000,
    defaultLevel: "All Levels",
    defaultLessonType: "Video",
    completionTracking: true,
    instructorRatings: true,
  },
  enrollments: {
    allowSelfEnrollment: true,
    allowInstructorEnrollment: false,
    confirmation: true,
    completionTracking: true,
    allowReEnrollment: false,
    allowCancellation: true,
    defaultStatus: "Active",
    maxStudents: 1000,
    showEnrollmentCount: true,
    showProgress: true,
  },
  payments: {
    mode: "Test",
    currency: "INR",
    provider: "None",
    enabled: false,
    refunds: false,
    taxEnabled: true,
    taxPercentage: 18,
  },
  certificates: {
    enabled: true,
    autoGenerate: true,
    completionPercentage: 100,
    passingScore: 70,
    prefix: "EDU",
    idFormat: "EDU-{YEAR}-{NUMBER}",
    showStudentName: true,
    showInstructorName: true,
    showCompletionDate: true,
    showScore: true,
    verification: true,
  },
  notifications: {
    email: true,
    enrollment: true,
    assignment: true,
    quiz: true,
    certificate: true,
    payment: true,
    review: true,
    system: true,
    admin: true,
    browser: false,
  },
  security: {
    strongPasswords: true,
    emailVerification: true,
    loginTracking: true,
    sessionTimeoutEnabled: true,
    sessionTimeout: "30 minutes",
    maxLoginAttempts: 5,
    lockoutDuration: "15 minutes",
    twoFactorEnabled: false,
  },
  maintenance: {
    enabled: false,
    message: "EduLearn is currently undergoing scheduled maintenance. Please check back shortly.",
    scheduled: false,
    startDate: "",
    endDate: "",
    allowAdminAccess: true,
  },
};
