export const adminStudentsSummary = {
  totalStudents: 10840,
  activeStudents: 8420,
  newStudents: 684,
  completedLearners: 3248,
};

export const adminStudents = [
  {
    id: "STU-1001",
    name: "Aarav Sharma",
    email: "aarav@example.com",
    phone: "+91 98765 43210",
    country: "India",
    status: "active",
    joinedAt: "2026-09-12",
    lastActive: "5 minutes ago",
    enrolledCourses: 8,
    completedCourses: 3,
    certificates: 2,
    overallProgress: 72,
    learningHours: 84,
    weeklyGoal: { current: 4, target: 6 },
    currentCourse: "React Fundamentals",
    courses: [
      { id: "course-001", title: "React Fundamentals", instructor: "John Doe", progress: 72, status: "in-progress", lastActivity: "React Hooks" },
      { id: "course-002", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 54, status: "in-progress", lastActivity: "Async Patterns" },
      { id: "course-003", title: "Next.js Complete Guide", instructor: "Daniel Kim", progress: 31, status: "in-progress", lastActivity: "Routing Fundamentals" },
    ],
    activities: [
      { type: "Completed", detail: "React Hooks lesson", time: "2 hours ago" },
      { type: "Started", detail: "Next.js Routing", time: "Yesterday" },
      { type: "Completed", detail: "JavaScript Quiz", time: "2 days ago" },
      { type: "Enrolled", detail: "MERN Stack Development", time: "5 days ago" },
    ],
    progressBreakdown: [
      { course: "React Fundamentals", progress: 72 },
      { course: "JavaScript Mastery", progress: 54 },
      { course: "Next.js Complete Guide", progress: 31 },
    ],
  },
  {
    id: "STU-1002",
    name: "Priya Nair",
    email: "priya@example.com",
    phone: "+91 99876 12345",
    country: "India",
    status: "active",
    joinedAt: "2026-08-20",
    lastActive: "2 hours ago",
    enrolledCourses: 5,
    completedCourses: 2,
    certificates: 1,
    overallProgress: 64,
    learningHours: 60,
    weeklyGoal: { current: 5, target: 6 },
    currentCourse: "MERN Stack Development",
    courses: [
      { id: "course-004", title: "MERN Stack Development", instructor: "Alicia Green", progress: 64, status: "in-progress", lastActivity: "MongoDB Setup" },
      { id: "course-005", title: "UI/UX Design", instructor: "Riya Shah", progress: 48, status: "in-progress", lastActivity: "Design System" },
    ],
    activities: [
      { type: "Started", detail: "MERN Stack Development", time: "3 hours ago" },
      { type: "Completed", detail: "Design Challenge", time: "Yesterday" },
      { type: "Enrolled", detail: "Node.js Bootcamp", time: "4 days ago" },
    ],
    progressBreakdown: [
      { course: "MERN Stack Development", progress: 64 },
      { course: "UI/UX Design", progress: 48 },
    ],
  },
  {
    id: "STU-1003",
    name: "Daniel Kim",
    email: "daniel@example.com",
    phone: "+1 415 555 0102",
    country: "United States",
    status: "inactive",
    joinedAt: "2026-07-28",
    lastActive: "3 days ago",
    enrolledCourses: 3,
    completedCourses: 1,
    certificates: 0,
    overallProgress: 36,
    learningHours: 28,
    weeklyGoal: { current: 1, target: 6 },
    currentCourse: "JavaScript Mastery",
    courses: [
      { id: "course-006", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 36, status: "in-progress", lastActivity: "Closures" },
    ],
    activities: [
      { type: "Started", detail: "JavaScript Mastery", time: "1 week ago" },
      { type: "Completed", detail: "Variables and Scope", time: "2 weeks ago" },
    ],
    progressBreakdown: [
      { course: "JavaScript Mastery", progress: 36 },
    ],
  },
  {
    id: "STU-1004",
    name: "Sofia Martinez",
    email: "sofia@example.com",
    phone: "+34 612 345 678",
    country: "Spain",
    status: "suspended",
    joinedAt: "2026-03-15",
    lastActive: "Never",
    enrolledCourses: 2,
    completedCourses: 0,
    certificates: 0,
    overallProgress: 12,
    learningHours: 10,
    weeklyGoal: { current: 0, target: 6 },
    currentCourse: "UI/UX Design",
    courses: [
      { id: "course-007", title: "UI/UX Design", instructor: "Riya Shah", progress: 12, status: "not-started", lastActivity: "Not started" },
    ],
    activities: [
      { type: "Enrolled", detail: "UI/UX Design", time: "8 days ago" },
    ],
    progressBreakdown: [
      { course: "UI/UX Design", progress: 12 },
    ],
  },
  {
    id: "STU-1005",
    name: "Michael Chen",
    email: "michael@example.com",
    phone: "+1 646 555 0190",
    country: "United States",
    status: "active",
    joinedAt: "2026-09-22",
    lastActive: "15 minutes ago",
    enrolledCourses: 4,
    completedCourses: 1,
    certificates: 1,
    overallProgress: 49,
    learningHours: 41,
    weeklyGoal: { current: 3, target: 6 },
    currentCourse: "Next.js Complete Guide",
    courses: [
      { id: "course-008", title: "Next.js Complete Guide", instructor: "Daniel Kim", progress: 49, status: "in-progress", lastActivity: "Server Components" },
      { id: "course-009", title: "React Fundamentals", instructor: "John Doe", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "React Fundamentals", time: "1 day ago" },
      { type: "Started", detail: "Next.js Routing", time: "2 days ago" },
    ],
    progressBreakdown: [
      { course: "Next.js Complete Guide", progress: 49 },
      { course: "React Fundamentals", progress: 100 },
    ],
  },
  {
    id: "STU-1006",
    name: "Ava Patel",
    email: "ava@example.com",
    phone: "+44 7700 900123",
    country: "United Kingdom",
    status: "active",
    joinedAt: "2026-09-05",
    lastActive: "1 hour ago",
    enrolledCourses: 6,
    completedCourses: 2,
    certificates: 1,
    overallProgress: 81,
    learningHours: 76,
    weeklyGoal: { current: 5, target: 6 },
    currentCourse: "MERN Stack Development",
    courses: [
      { id: "course-010", title: "MERN Stack Development", instructor: "Alicia Green", progress: 81, status: "in-progress", lastActivity: "API Routes" },
      { id: "course-011", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "JavaScript Mastery", time: "3 hours ago" },
      { type: "Started", detail: "MERN Stack Development", time: "1 day ago" },
    ],
    progressBreakdown: [
      { course: "MERN Stack Development", progress: 81 },
      { course: "JavaScript Mastery", progress: 100 },
    ],
  },
  {
    id: "STU-1007",
    name: "Ethan Brooks",
    email: "ethan@example.com",
    phone: "+1 212 555 0134",
    country: "United States",
    status: "active",
    joinedAt: "2026-08-14",
    lastActive: "Yesterday",
    enrolledCourses: 7,
    completedCourses: 3,
    certificates: 2,
    overallProgress: 76,
    learningHours: 92,
    weeklyGoal: { current: 4, target: 6 },
    currentCourse: "React Fundamentals",
    courses: [
      { id: "course-012", title: "React Fundamentals", instructor: "John Doe", progress: 76, status: "in-progress", lastActivity: "Custom Hooks" },
      { id: "course-013", title: "UI/UX Design", instructor: "Riya Shah", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "Design System", time: "Yesterday" },
      { type: "Started", detail: "React Fundamentals", time: "2 days ago" },
    ],
    progressBreakdown: [
      { course: "React Fundamentals", progress: 76 },
      { course: "UI/UX Design", progress: 100 },
    ],
  },
  {
    id: "STU-1008",
    name: "Nia Thompson",
    email: "nia@example.com",
    phone: "+61 412 345 678",
    country: "Australia",
    status: "inactive",
    joinedAt: "2026-06-08",
    lastActive: "2 weeks ago",
    enrolledCourses: 2,
    completedCourses: 0,
    certificates: 0,
    overallProgress: 18,
    learningHours: 12,
    weeklyGoal: { current: 0, target: 6 },
    currentCourse: "JavaScript Mastery",
    courses: [
      { id: "course-014", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 18, status: "in-progress", lastActivity: "Arrays and Objects" },
    ],
    activities: [
      { type: "Started", detail: "JavaScript Mastery", time: "1 week ago" },
    ],
    progressBreakdown: [
      { course: "JavaScript Mastery", progress: 18 },
    ],
  },
  {
    id: "STU-1009",
    name: "Lucas Wilson",
    email: "lucas@example.com",
    phone: "+1 305 555 0118",
    country: "United States",
    status: "active",
    joinedAt: "2026-09-15",
    lastActive: "30 minutes ago",
    enrolledCourses: 5,
    completedCourses: 2,
    certificates: 1,
    overallProgress: 68,
    learningHours: 48,
    weeklyGoal: { current: 2, target: 6 },
    currentCourse: "React Fundamentals",
    courses: [
      { id: "course-015", title: "React Fundamentals", instructor: "John Doe", progress: 68, status: "in-progress", lastActivity: "Context API" },
      { id: "course-016", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "JavaScript Mastery", time: "2 days ago" },
      { type: "Started", detail: "React Fundamentals", time: "4 days ago" },
    ],
    progressBreakdown: [
      { course: "React Fundamentals", progress: 68 },
      { course: "JavaScript Mastery", progress: 100 },
    ],
  },
  {
    id: "STU-1010",
    name: "Emma Davis",
    email: "emma@example.com",
    phone: "+44 7911 123456",
    country: "United Kingdom",
    status: "active",
    joinedAt: "2026-09-18",
    lastActive: "10 minutes ago",
    enrolledCourses: 4,
    completedCourses: 1,
    certificates: 0,
    overallProgress: 58,
    learningHours: 40,
    weeklyGoal: { current: 3, target: 6 },
    currentCourse: "JavaScript Mastery",
    courses: [
      { id: "course-017", title: "JavaScript Mastery", instructor: "Sarah Wilson", progress: 58, status: "in-progress", lastActivity: "Functions" },
      { id: "course-018", title: "UI/UX Design", instructor: "Riya Shah", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "UI/UX Design", time: "5 hours ago" },
      { type: "Started", detail: "JavaScript Mastery", time: "1 day ago" },
    ],
    progressBreakdown: [
      { course: "JavaScript Mastery", progress: 58 },
      { course: "UI/UX Design", progress: 100 },
    ],
  },
  {
    id: "STU-1011",
    name: "Noah Smith",
    email: "noah@example.com",
    phone: "+1 415 555 0145",
    country: "United States",
    status: "active",
    joinedAt: "2026-07-17",
    lastActive: "2 hours ago",
    enrolledCourses: 9,
    completedCourses: 4,
    certificates: 3,
    overallProgress: 88,
    learningHours: 110,
    weeklyGoal: { current: 6, target: 6 },
    currentCourse: "MERN Stack Development",
    courses: [
      { id: "course-019", title: "MERN Stack Development", instructor: "Alicia Green", progress: 88, status: "in-progress", lastActivity: "Authentication" },
      { id: "course-020", title: "Next.js Complete Guide", instructor: "Daniel Kim", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "Next.js Complete Guide", time: "3 hours ago" },
      { type: "Started", detail: "MERN Stack Development", time: "Yesterday" },
    ],
    progressBreakdown: [
      { course: "MERN Stack Development", progress: 88 },
      { course: "Next.js Complete Guide", progress: 100 },
    ],
  },
  {
    id: "STU-1012",
    name: "Zoe Martin",
    email: "zoe@example.com",
    phone: "+33 6 12 34 56 78",
    country: "France",
    status: "suspended",
    joinedAt: "2026-05-09",
    lastActive: "Never",
    enrolledCourses: 1,
    completedCourses: 0,
    certificates: 0,
    overallProgress: 9,
    learningHours: 7,
    weeklyGoal: { current: 0, target: 6 },
    currentCourse: "UI/UX Design",
    courses: [
      { id: "course-021", title: "UI/UX Design", instructor: "Riya Shah", progress: 9, status: "in-progress", lastActivity: "Color Theory" },
    ],
    activities: [
      { type: "Enrolled", detail: "UI/UX Design", time: "12 days ago" },
    ],
    progressBreakdown: [
      { course: "UI/UX Design", progress: 9 },
    ],
  },
  {
    id: "STU-1013",
    name: "Leo Nguyen",
    email: "leo@example.com",
    phone: "+84 912 345 678",
    country: "Vietnam",
    status: "active",
    joinedAt: "2026-09-02",
    lastActive: "45 minutes ago",
    enrolledCourses: 3,
    completedCourses: 1,
    certificates: 1,
    overallProgress: 63,
    learningHours: 52,
    weeklyGoal: { current: 4, target: 6 },
    currentCourse: "Next.js Complete Guide",
    courses: [
      { id: "course-022", title: "Next.js Complete Guide", instructor: "Daniel Kim", progress: 63, status: "in-progress", lastActivity: "Server Components" },
      { id: "course-023", title: "React Fundamentals", instructor: "John Doe", progress: 100, status: "completed", lastActivity: "Course completed" },
    ],
    activities: [
      { type: "Completed", detail: "React Fundamentals", time: "Yesterday" },
      { type: "Started", detail: "Next.js Complete Guide", time: "2 days ago" },
    ],
    progressBreakdown: [
      { course: "Next.js Complete Guide", progress: 63 },
      { course: "React Fundamentals", progress: 100 },
    ],
  },
  {
    id: "STU-1014",
    name: "Grace Moore",
    email: "grace@example.com",
    phone: "+61 431 234 567",
    country: "Australia",
    status: "inactive",
    joinedAt: "2026-06-02",
    lastActive: "1 week ago",
    enrolledCourses: 2,
    completedCourses: 0,
    certificates: 0,
    overallProgress: 26,
    learningHours: 19,
    weeklyGoal: { current: 1, target: 6 },
    currentCourse: "MERN Stack Development",
    courses: [
      { id: "course-024", title: "MERN Stack Development", instructor: "Alicia Green", progress: 26, status: "in-progress", lastActivity: "Deployment" },
    ],
    activities: [
      { type: "Started", detail: "MERN Stack Development", time: "4 days ago" },
    ],
    progressBreakdown: [
      { course: "MERN Stack Development", progress: 26 },
    ],
  },
];

export default adminStudents;
