export const notificationTypeConfig = {
  course: { label: "Course", icon: "BookOpen" },
  enrollment: { label: "Enrollment", icon: "UserPlus" },
  payment: { label: "Payment", icon: "CreditCard" },
  certificate: { label: "Certificate", icon: "Award" },
  assignment: { label: "Assignment", icon: "FileText" },
  quiz: { label: "Quiz", icon: "ClipboardList" },
  review: { label: "Review", icon: "Star" },
  system: { label: "System", icon: "Bell" },
  announcement: { label: "Announcement", icon: "Megaphone" },
};

export const notificationPriorityConfig = {
  low: { label: "Low", value: 1 },
  normal: { label: "Normal", value: 2 },
  high: { label: "High", value: 3 },
  critical: { label: "Critical", value: 4 },
};

export const adminNotifications = [
  {
    id: "notif-001",
    notificationId: "NOTIF-EDU-10245",
    title: "Course Enrollment Successful",
    message: "You have successfully enrolled in Full Stack Development.",
    type: "enrollment",
    recipientType: "student",
    recipientId: "stu-001",
    recipientName: "Rahul Sharma",
    recipientEmail: "rahul@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-02T10:30:00",
    scheduledAt: null,
    sentAt: "2026-10-02T10:31:00",
    readAt: "2026-10-02T10:35:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-002",
    notificationId: "NOTIF-EDU-10246",
    title: "Payment Confirmation",
    message: "Your payment for the React & Next.js course has been confirmed.",
    type: "payment",
    recipientType: "student",
    recipientId: "stu-002",
    recipientName: "Priya Nair",
    recipientEmail: "priya@example.com",
    priority: "high",
    channel: "email",
    status: "sent",
    read: false,
    createdAt: "2026-10-03T08:15:00",
    scheduledAt: null,
    sentAt: "2026-10-03T08:16:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "Email",
  },
  {
    id: "notif-003",
    notificationId: "NOTIF-EDU-10247",
    title: "Assignment Feedback Ready",
    message: "Your JavaScript Fundamentals assignment feedback is now available.",
    type: "assignment",
    recipientType: "student",
    recipientId: "stu-003",
    recipientName: "Aman Verma",
    recipientEmail: "aman@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-04T09:00:00",
    scheduledAt: null,
    sentAt: "2026-10-04T09:01:00",
    readAt: "2026-10-04T10:00:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-004",
    notificationId: "NOTIF-EDU-10248",
    title: "Certificate Issued",
    message: "Congratulations, your certificate for Python Basics has been issued.",
    type: "certificate",
    recipientType: "student",
    recipientId: "stu-004",
    recipientName: "Neha Kapoor",
    recipientEmail: "neha@example.com",
    priority: "high",
    channel: "in-app",
    status: "sent",
    read: false,
    createdAt: "2026-10-05T14:20:00",
    scheduledAt: null,
    sentAt: "2026-10-05T14:22:00",
    readAt: null,
    deliveryStatus: "pending",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-005",
    notificationId: "NOTIF-EDU-10249",
    title: "Quiz Reminder",
    message: "Your Data Analytics quiz is due tomorrow at 11:59 PM.",
    type: "quiz",
    recipientType: "student",
    recipientId: "stu-005",
    recipientName: "Rohan Gupta",
    recipientEmail: "rohan@example.com",
    priority: "normal",
    channel: "email",
    status: "sent",
    read: true,
    createdAt: "2026-10-06T09:45:00",
    scheduledAt: null,
    sentAt: "2026-10-06T09:46:00",
    readAt: "2026-10-06T09:50:00",
    deliveryStatus: "delivered",
    deliveryChannel: "Email",
  },
  {
    id: "notif-006",
    notificationId: "NOTIF-EDU-10250",
    title: "New Course Published",
    message: "Frontend Systems Design is now live and open for enrollment.",
    type: "course",
    recipientType: "student",
    recipientId: "stu-006",
    recipientName: "Maya Singh",
    recipientEmail: "maya@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: false,
    createdAt: "2026-10-07T07:30:00",
    scheduledAt: null,
    sentAt: "2026-10-07T07:31:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-007",
    notificationId: "NOTIF-EDU-10251",
    title: "Instructor Review Received",
    message: "A learner left a new review on your Web Development course.",
    type: "review",
    recipientType: "instructor",
    recipientId: "ins-001",
    recipientName: "Sarah Wilson",
    recipientEmail: "sarah@example.com",
    priority: "high",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-08T11:10:00",
    scheduledAt: null,
    sentAt: "2026-10-08T11:12:00",
    readAt: "2026-10-08T11:18:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-008",
    notificationId: "NOTIF-EDU-10252",
    title: "System Maintenance Notice",
    message: "We will perform scheduled platform maintenance on Saturday at 2 AM UTC.",
    type: "system",
    recipientType: "admin",
    recipientId: "adm-001",
    recipientName: "Ava Thompson",
    recipientEmail: "ava@edulearn.com",
    priority: "critical",
    channel: "email",
    status: "sent",
    read: true,
    createdAt: "2026-10-09T12:00:00",
    scheduledAt: null,
    sentAt: "2026-10-09T12:03:00",
    readAt: "2026-10-09T12:05:00",
    deliveryStatus: "delivered",
    deliveryChannel: "Email",
  },
  {
    id: "notif-009",
    notificationId: "NOTIF-EDU-10253",
    title: "Annual Course Update",
    message: "The Business Analytics curriculum has been updated with new modules.",
    type: "announcement",
    recipientType: "all-students",
    recipientId: "seg-001",
    recipientName: "All Students",
    recipientEmail: "students@edulearn.com",
    priority: "normal",
    channel: "push",
    status: "sent",
    read: false,
    createdAt: "2026-10-10T16:40:00",
    scheduledAt: null,
    sentAt: "2026-10-10T16:41:00",
    readAt: null,
    deliveryStatus: "sent",
    deliveryChannel: "Push",
  },
  {
    id: "notif-010",
    notificationId: "NOTIF-EDU-10254",
    title: "Workshop Registration Opens",
    message: "Registration is now open for the UI UX Design workshop series.",
    type: "announcement",
    recipientType: "student",
    recipientId: "stu-007",
    recipientName: "Ishita Rao",
    recipientEmail: "ishita@example.com",
    priority: "low",
    channel: "in-app",
    status: "draft",
    read: false,
    createdAt: "2026-10-11T13:20:00",
    scheduledAt: null,
    sentAt: null,
    readAt: null,
    deliveryStatus: "draft",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-011",
    notificationId: "NOTIF-EDU-10255",
    title: "Course Launch Reminder",
    message: "Your Digital Marketing course launch is scheduled for Friday morning.",
    type: "course",
    recipientType: "student",
    recipientId: "stu-008",
    recipientName: "Karan Mehta",
    recipientEmail: "karan@example.com",
    priority: "normal",
    channel: "email",
    status: "scheduled",
    read: false,
    createdAt: "2026-10-12T15:15:00",
    scheduledAt: "2026-10-15T09:00:00",
    sentAt: null,
    readAt: null,
    deliveryStatus: "scheduled",
    deliveryChannel: "Email",
  },
  {
    id: "notif-012",
    notificationId: "NOTIF-EDU-10256",
    title: "Enrollment Deadline Approaching",
    message: "The enrollment period for Cyber Security Essentials ends in 48 hours.",
    type: "enrollment",
    recipientType: "student",
    recipientId: "stu-009",
    recipientName: "Simran Kaur",
    recipientEmail: "simran@example.com",
    priority: "high",
    channel: "push",
    status: "sent",
    read: false,
    createdAt: "2026-10-13T08:00:00",
    scheduledAt: null,
    sentAt: "2026-10-13T08:02:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "Push",
  },
  {
    id: "notif-013",
    notificationId: "NOTIF-EDU-10257",
    title: "Assignment Due Soon",
    message: "Your final project draft is due in 24 hours.",
    type: "assignment",
    recipientType: "student",
    recipientId: "stu-010",
    recipientName: "Dhruv Sharma",
    recipientEmail: "dhruv@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-14T09:00:00",
    scheduledAt: null,
    sentAt: "2026-10-14T09:02:00",
    readAt: "2026-10-14T09:42:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-014",
    notificationId: "NOTIF-EDU-10258",
    title: "New Instructor Welcome",
    message: "Welcome aboard. Complete your setup and verify your profile.",
    type: "system",
    recipientType: "instructor",
    recipientId: "ins-002",
    recipientName: "Mark Lee",
    recipientEmail: "mark@example.com",
    priority: "normal",
    channel: "email",
    status: "sent",
    read: false,
    createdAt: "2026-10-15T10:15:00",
    scheduledAt: null,
    sentAt: "2026-10-15T10:17:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "Email",
  },
  {
    id: "notif-015",
    notificationId: "NOTIF-EDU-10259",
    title: "Course Review Reminder",
    message: "Share your feedback to help improve this learning path.",
    type: "review",
    recipientType: "student",
    recipientId: "stu-011",
    recipientName: "Naina Patel",
    recipientEmail: "naina@example.com",
    priority: "low",
    channel: "in-app",
    status: "sent",
    read: false,
    createdAt: "2026-10-16T11:30:00",
    scheduledAt: null,
    sentAt: "2026-10-16T11:31:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-016",
    notificationId: "NOTIF-EDU-10260",
    title: "Payment Failed",
    message: "Your last payment attempt failed. Update your billing information.",
    type: "payment",
    recipientType: "student",
    recipientId: "stu-012",
    recipientName: "Arjun Nair",
    recipientEmail: "arjun@example.com",
    priority: "critical",
    channel: "sms",
    status: "sent",
    read: true,
    createdAt: "2026-10-17T06:55:00",
    scheduledAt: null,
    sentAt: "2026-10-17T06:58:00",
    readAt: "2026-10-17T07:12:00",
    deliveryStatus: "delivered",
    deliveryChannel: "SMS",
  },
  {
    id: "notif-017",
    notificationId: "NOTIF-EDU-10261",
    title: "Quiz Results Published",
    message: "Your results for the Mobile UI Basics quiz are now available.",
    type: "quiz",
    recipientType: "student",
    recipientId: "stu-013",
    recipientName: "Meera Joshi",
    recipientEmail: "meera@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: false,
    createdAt: "2026-10-17T19:10:00",
    scheduledAt: null,
    sentAt: "2026-10-17T19:12:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-018",
    notificationId: "NOTIF-EDU-10262",
    title: "Certificate Verification Requested",
    message: "A verification request was submitted for a learner certificate.",
    type: "certificate",
    recipientType: "admin",
    recipientId: "adm-002",
    recipientName: "Elena Brooks",
    recipientEmail: "elena@edulearn.com",
    priority: "high",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-18T14:05:00",
    scheduledAt: null,
    sentAt: "2026-10-18T14:06:00",
    readAt: "2026-10-18T14:16:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-019",
    notificationId: "NOTIF-EDU-10263",
    title: "Instructor Webinar Invitation",
    message: "You are invited to the live webinar on curriculum design best practices.",
    type: "announcement",
    recipientType: "instructor",
    recipientId: "ins-003",
    recipientName: "Joseph Kim",
    recipientEmail: "joseph@example.com",
    priority: "normal",
    channel: "email",
    status: "draft",
    read: false,
    createdAt: "2026-10-19T08:10:00",
    scheduledAt: null,
    sentAt: null,
    readAt: null,
    deliveryStatus: "draft",
    deliveryChannel: "Email",
  },
  {
    id: "notif-020",
    notificationId: "NOTIF-EDU-10264",
    title: "Course Access Enabled",
    message: "Your access has been enabled for the advanced SEO course.",
    type: "course",
    recipientType: "student",
    recipientId: "stu-014",
    recipientName: "Pooja Reddy",
    recipientEmail: "pooja@example.com",
    priority: "normal",
    channel: "push",
    status: "sent",
    read: false,
    createdAt: "2026-10-20T08:45:00",
    scheduledAt: null,
    sentAt: "2026-10-20T08:46:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "Push",
  },
  {
    id: "notif-021",
    notificationId: "NOTIF-EDU-10265",
    title: "Course Completion Badge Earned",
    message: "You earned the Skill Builder badge in Data Science Essentials.",
    type: "certificate",
    recipientType: "student",
    recipientId: "stu-015",
    recipientName: "Anil Roy",
    recipientEmail: "anil@example.com",
    priority: "normal",
    channel: "in-app",
    status: "sent",
    read: true,
    createdAt: "2026-10-20T18:00:00",
    scheduledAt: null,
    sentAt: "2026-10-20T18:02:00",
    readAt: "2026-10-20T18:10:00",
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-022",
    notificationId: "NOTIF-EDU-10266",
    title: "Session Invite Draft",
    message: "Draft invitation for the instructor onboarding session is ready.",
    type: "system",
    recipientType: "instructor",
    recipientId: "ins-004",
    recipientName: "Grace Wilson",
    recipientEmail: "grace@example.com",
    priority: "low",
    channel: "email",
    status: "draft",
    read: false,
    createdAt: "2026-10-21T14:30:00",
    scheduledAt: null,
    sentAt: null,
    readAt: null,
    deliveryStatus: "draft",
    deliveryChannel: "Email",
  },
  {
    id: "notif-023",
    notificationId: "NOTIF-EDU-10267",
    title: "Final Project Evaluation",
    message: "Your capstone project result has been published by the review team.",
    type: "assignment",
    recipientType: "student",
    recipientId: "stu-016",
    recipientName: "Tanya Sen",
    recipientEmail: "tanya@example.com",
    priority: "high",
    channel: "in-app",
    status: "sent",
    read: false,
    createdAt: "2026-10-22T07:40:00",
    scheduledAt: null,
    sentAt: "2026-10-22T07:42:00",
    readAt: null,
    deliveryStatus: "delivered",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-024",
    notificationId: "NOTIF-EDU-10268",
    title: "Platform Update Announcement",
    message: "A new admin announcement is now available in your dashboard.",
    type: "announcement",
    recipientType: "admin",
    recipientId: "adm-003",
    recipientName: "Hannah Lee",
    recipientEmail: "hannah@edulearn.com",
    priority: "normal",
    channel: "in-app",
    status: "scheduled",
    read: false,
    createdAt: "2026-10-23T09:00:00",
    scheduledAt: "2026-10-25T10:30:00",
    sentAt: null,
    readAt: null,
    deliveryStatus: "scheduled",
    deliveryChannel: "In-App",
  },
  {
    id: "notif-025",
    notificationId: "NOTIF-EDU-10269",
    title: "Course Enrollment Welcome",
    message: "Welcome to Full Stack Development. Start with the onboarding lesson.",
    type: "enrollment",
    recipientType: "student",
    recipientId: "stu-017",
    recipientName: "Aditya Bhatia",
    recipientEmail: "aditya@example.com",
    priority: "normal",
    channel: "email",
    status: "sent",
    read: true,
    createdAt: "2026-10-24T12:00:00",
    scheduledAt: null,
    sentAt: "2026-10-24T12:02:00",
    readAt: "2026-10-24T12:31:00",
    deliveryStatus: "delivered",
    deliveryChannel: "Email",
  },
];

export default adminNotifications;
