export const adminAuditLogs = [
  {
    id: "EVT-10248",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Updated",
    actionType: "updated",
    targetType: "Course",
    targetName: "Advanced JavaScript",
    targetId: "CRS-10024",
    description: "Updated course pricing and publication settings.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T22:42:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10247",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Approved",
    actionType: "approved",
    targetType: "Instructor",
    targetName: "Aisha Rahman",
    targetId: "INS-2408",
    description: "Approved instructor application and activated course publishing access.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T20:15:00",
    ipAddress: "10.10.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10246",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Rejected",
    actionType: "rejected",
    targetType: "Review",
    targetName: "UX Fundamentals Review",
    targetId: "REV-8731",
    description: "Rejected a review submission containing promotional language and spam content.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-10-02T19:30:00",
    ipAddress: "172.16.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10245",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Suspended",
    actionType: "suspended",
    targetType: "Student",
    targetName: "Ananya Sharma",
    targetId: "STD-10421",
    description: "Suspended account after repeated policy violations.",
    status: "warning",
    securityEvent: true,
    timestamp: "2026-10-02T18:57:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "Multiple failed login attempts from a suspended device fingerprint.",
  },
  {
    id: "EVT-10244",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Settings Changed",
    actionType: "settings_changed",
    targetType: "Settings",
    targetName: "Platform Settings",
    targetId: "CFG-SET-01",
    description: "Updated global notification preferences and certificate thresholds.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T18:08:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10243",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Login",
    actionType: "login",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-ADMIN-01",
    description: "Administrator signed in to the admin console from a trusted device.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T17:46:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10242",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Created",
    actionType: "created",
    targetType: "Category",
    targetName: "Product Design",
    targetId: "CAT-2402",
    description: "Created a new category for product design learning tracks.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T16:20:00",
    ipAddress: "10.12.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10241",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Exported",
    actionType: "exported",
    targetType: "Payment",
    targetName: "Revenue Export",
    targetId: "EXP-2026-10-02",
    description: "Exported payment summary report for the previous month.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T15:38:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10240",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Published",
    actionType: "published",
    targetType: "Course",
    targetName: "AI for Product Managers",
    targetId: "CRS-12091",
    description: "Published course after successful review and content validation.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T14:52:00",
    ipAddress: "10.20.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10239",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Viewed",
    actionType: "viewed",
    targetType: "Payment",
    targetName: "Invoice #INV-4261",
    targetId: "INV-4261",
    description: "Viewed payment record for premium course invoice review.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-02T13:06:00",
    ipAddress: "172.27.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10238",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Notification Created",
    actionType: "created",
    targetType: "Notification",
    targetName: "Cohort Launch Reminder",
    targetId: "NTF-9081",
    description: "Created a reminder notification for the upcoming cohort launch.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T21:17:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.6 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10237",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "User Updated",
    actionType: "updated",
    targetType: "User",
    targetName: "Priya Mehta",
    targetId: "USR-6218",
    description: "Updated learner profile and account restrictions.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T20:44:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10236",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Failed Login",
    actionType: "failed",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-AUTH-09",
    description: "Multiple failed login attempts from an unrecognized browser session.",
    status: "failed",
    securityEvent: true,
    timestamp: "2026-10-01T19:58:00",
    ipAddress: "58.84.XXX.XXX",
    userAgent: "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36",
    securityReason: "Repeated failed login attempts triggered an automatic security review.",
  },
  {
    id: "EVT-10235",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Course Approved",
    actionType: "approved",
    targetType: "Course",
    targetName: "Growth Marketing Bootcamp",
    targetId: "CRS-11402",
    description: "Approved a new cohort-based course and enabled publishing.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T19:12:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10234",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Enrollment Updated",
    actionType: "updated",
    targetType: "Enrollment",
    targetName: "UI/UX Track Enrollment",
    targetId: "ENR-9315",
    description: "Updated enrollment status to active after payment confirmation.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T18:27:00",
    ipAddress: "10.14.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10233",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Certificate Issued",
    actionType: "approved",
    targetType: "Certificate",
    targetName: "Professional Python Certificate",
    targetId: "CRT-7811",
    description: "Issued a completion certificate to a learner who met the required score.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T17:41:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10232",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "User Deleted",
    actionType: "deleted",
    targetType: "User",
    targetName: "Aman Verma",
    targetId: "USR-9012",
    description: "Deleted a deactivated user account pending a data retention review.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-10-01T17:09:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10231",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Review Approved",
    actionType: "approved",
    targetType: "Review",
    targetName: "Data Analytics Deep Dive",
    targetId: "REV-8148",
    description: "Approved a learner review and re-enabled public display.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T15:52:00",
    ipAddress: "10.17.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10230",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Logout",
    actionType: "logout",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-ADMIN-02",
    description: "Admin session ended after the configured inactivity timeout was reached.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T15:10:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10229",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Course Rejected",
    actionType: "rejected",
    targetType: "Course",
    targetName: "Intro to Prompt Engineering",
    targetId: "CRS-8804",
    description: "Rejected course due to outdated curriculum and missing assessment rubric.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-10-01T14:00:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10228",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Category Updated",
    actionType: "updated",
    targetType: "Category",
    targetName: "Data Science",
    targetId: "CAT-1809",
    description: "Updated category metadata and reorganized learning track order.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-10-01T12:36:00",
    ipAddress: "172.18.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10227",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Payment Refunded",
    actionType: "updated",
    targetType: "Payment",
    targetName: "Refund for Full Stack Fundamentals",
    targetId: "PAY-6621",
    description: "Processed a partial refund request after course cancellation.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-09-30T23:14:00",
    ipAddress: "10.22.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10226",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "System Configuration Updated",
    actionType: "settings_changed",
    targetType: "System",
    targetName: "System Configuration",
    targetId: "CFG-CORE-02",
    description: "Updated session expiration values and system health thresholds.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-30T22:12:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10225",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Course Unpublished",
    actionType: "unpublished",
    targetType: "Course",
    targetName: "Content Strategy Sprint",
    targetId: "CRS-9123",
    description: "Unpublished course while awaiting updated curriculum validation.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-09-30T20:55:00",
    ipAddress: "172.31.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10224",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "User Activated",
    actionType: "activated",
    targetType: "Student",
    targetName: "Neha Kapoor",
    targetId: "STD-2418",
    description: "Activated a student account after the verification review was cleared.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-30T19:04:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10223",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Instructor Approved",
    actionType: "approved",
    targetType: "Instructor",
    targetName: "Noor Ali",
    targetId: "INS-4011",
    description: "Approved instructor profile and assigned default course moderation permissions.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-30T18:10:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10222",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Payment Record Updated",
    actionType: "updated",
    targetType: "Payment",
    targetName: "Subscription Renewal",
    targetId: "PAY-7710",
    description: "Updated payment status after verifying subscription renewal completion.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-29T21:02:00",
    ipAddress: "10.17.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10221",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Notification Scheduled",
    actionType: "created",
    targetType: "Notification",
    targetName: "Weekend Webinar Reminder",
    targetId: "NTF-3301",
    description: "Scheduled a webinar reminder for all enrolled learners in the automation track.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-29T20:41:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10220",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "User Suspended",
    actionType: "suspended",
    targetType: "User",
    targetName: "Kabir Singh",
    targetId: "USR-8711",
    description: "Suspended user after repeated policy and platform abuse reports.",
    status: "warning",
    securityEvent: true,
    timestamp: "2026-09-29T19:55:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "User flagged for suspicious multi-account activity across sessions.",
  },
  {
    id: "EVT-10219",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Notification Cancelled",
    actionType: "deleted",
    targetType: "Notification",
    targetName: "Product Drop Reminder",
    targetId: "NTF-1284",
    description: "Cancelled a scheduled announcement due to content approval delays.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-09-29T18:33:00",
    ipAddress: "10.43.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10218",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Course Created",
    actionType: "created",
    targetType: "Course",
    targetName: "Digital Marketing Essentials",
    targetId: "CRS-3009",
    description: "Created a new digital marketing course for the next enrollment cycle.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-28T17:44:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10217",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Enrollment Cancelled",
    actionType: "deleted",
    targetType: "Enrollment",
    targetName: "SEO Bootcamp",
    targetId: "ENR-1332",
    description: "Cancelled enrollment after the learner requested a refund and account review.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-09-28T16:49:00",
    ipAddress: "172.16.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10216",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Instructor Profile Updated",
    actionType: "updated",
    targetType: "Instructor",
    targetName: "Rahul Sethi",
    targetId: "INS-5529",
    description: "Updated instructor profile biography and curriculum focus areas.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-28T15:04:00",
    ipAddress: "10.11.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10215",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Certificate Revoked",
    actionType: "rejected",
    targetType: "Certificate",
    targetName: "Front-End Workshop Completion",
    targetId: "CRT-5214",
    description: "Revoked a certificate after a verification failure and manual review request.",
    status: "failed",
    securityEvent: true,
    timestamp: "2026-09-27T21:01:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "Invalid certificate verification signature detected during audit.",
  },
  {
    id: "EVT-10214",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "User Created",
    actionType: "created",
    targetType: "User",
    targetName: "Simran Kaur",
    targetId: "USR-6091",
    description: "Created a new learner account for the upcoming program intake.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-27T19:30:00",
    ipAddress: "172.18.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10213",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Review Hidden",
    actionType: "rejected",
    targetType: "Review",
    targetName: "Data Visualization Masterclass",
    targetId: "REV-5007",
    description: "Hidden a review pending additional verification and moderation.",
    status: "warning",
    securityEvent: false,
    timestamp: "2026-09-27T18:40:00",
    ipAddress: "10.19.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10212",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Exported",
    actionType: "exported",
    targetType: "Course",
    targetName: "Course Performance Export",
    targetId: "EXP-2026-09-27",
    description: "Exported leaderboard and completion data for weekly admin review.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-27T17:05:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10211",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Category Created",
    actionType: "created",
    targetType: "Category",
    targetName: "Cybersecurity",
    targetId: "CAT-3005",
    description: "Created a new category for cybersecurity and digital trust programs.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-27T16:14:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10210",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Viewed",
    actionType: "viewed",
    targetType: "Course",
    targetName: "Advanced JavaScript",
    targetId: "CRS-10024",
    description: "Viewed course performance and conversion report for the current month.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-26T13:28:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10209",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Login",
    actionType: "login",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-ADMIN-44",
    description: "Admin signed in to review weekly platform quality data.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-26T10:05:00",
    ipAddress: "172.16.XXX.XXX",
    userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10208",
    actor: {
      name: "Maya Moderator",
      email: "maya.moderator@edulearn.demo",
      role: "Moderator",
      initials: "MM",
    },
    action: "Course Published",
    actionType: "published",
    targetType: "Course",
    targetName: "Design Systems in Practice",
    targetId: "CRS-11044",
    description: "Published a course after the final moderation pass and QA review.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-25T19:52:00",
    ipAddress: "10.13.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10207",
    actor: {
      name: "Nikhil Admin",
      email: "nikhil.admin@edulearn.demo",
      role: "Admin",
      initials: "NA",
    },
    action: "Settings Updated",
    actionType: "settings_changed",
    targetType: "Settings",
    targetName: "Audit Settings",
    targetId: "CFG-AUDIT-01",
    description: "Updated audit retention settings and event visibility preferences.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-25T16:33:00",
    ipAddress: "10.9.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10206",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Failed Login",
    actionType: "failed",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-AUTH-58",
    description: "Detected a failed login attempt from a blocked IP range.",
    status: "failed",
    securityEvent: true,
    timestamp: "2026-09-25T15:18:00",
    ipAddress: "203.0.XXX.XXX",
    userAgent: "Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36",
    securityReason: "Blocked source matched a previous suspicious address list.",
  },
  {
    id: "EVT-10205",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "Enrollment Created",
    actionType: "created",
    targetType: "Enrollment",
    targetName: "AI Leadership Program",
    targetId: "ENR-8804",
    description: "Created a new enrollment record after the payment verification step succeeded.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-24T11:57:00",
    ipAddress: "198.51.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/127.0.0.0",
    securityReason: "",
  },
  {
    id: "EVT-10204",
    actor: {
      name: "Harsh Admin",
      email: "harsh.admin@edulearn.demo",
      role: "Admin",
      initials: "HA",
    },
    action: "Course Updated",
    actionType: "updated",
    targetType: "Course",
    targetName: "Product Strategy Essentials",
    targetId: "CRS-4401",
    description: "Updated descriptions, assessments, and cohort pacing for the next session.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-24T10:41:00",
    ipAddress: "10.45.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10203",
    actor: {
      name: "Sana Admin",
      email: "sana.admin@edulearn.demo",
      role: "Admin",
      initials: "SA",
    },
    action: "Certificate Issued",
    actionType: "approved",
    targetType: "Certificate",
    targetName: "Data Visualization Badge",
    targetId: "CRT-3290",
    description: "Issued a digital certificate to a learner after successful course completion.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-23T19:28:00",
    ipAddress: "172.18.XXX.XXX",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15",
    securityReason: "",
  },
  {
    id: "EVT-10202",
    actor: {
      name: "Rohit Admin",
      email: "rohit.admin@edulearn.demo",
      role: "Admin",
      initials: "RA",
    },
    action: "User Updated",
    actionType: "updated",
    targetType: "User",
    targetName: "Nisha Rao",
    targetId: "USR-7742",
    description: "Updated organization access and assigned learning cohort permissions.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-22T18:22:00",
    ipAddress: "172.20.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    securityReason: "",
  },
  {
    id: "EVT-10201",
    actor: {
      name: "Vandana Admin",
      email: "vandana.admin@edulearn.demo",
      role: "Super Admin",
      initials: "VA",
    },
    action: "Admin Login",
    actionType: "login",
    targetType: "System",
    targetName: "Admin Console",
    targetId: "SYS-ADMIN-99",
    description: "Super admin signed in for the daily compliance and reporting review.",
    status: "success",
    securityEvent: false,
    timestamp: "2026-09-22T08:16:00",
    ipAddress: "192.168.XXX.XXX",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
    securityReason: "",
  },
];

export const auditActionLabels = {
  login: "Login",
  logout: "Logout",
  created: "Created",
  updated: "Updated",
  deleted: "Deleted",
  approved: "Approved",
  rejected: "Rejected",
  suspended: "Suspended",
  activated: "Activated",
  published: "Published",
  unpublished: "Unpublished",
  viewed: "Viewed",
  exported: "Exported",
  settings_changed: "Settings Changed",
  failed: "Failed",
};

export const auditStatusOptions = ["all", "success", "warning", "failed"];
export const auditActionTypeOptions = [
  "all",
  "created",
  "updated",
  "deleted",
  "approved",
  "rejected",
  "suspended",
  "activated",
  "published",
  "unpublished",
  "login",
  "logout",
  "viewed",
  "exported",
  "settings_changed",
  "failed",
];

export const auditActorOptions = ["all", "Super Admin", "Admin", "Moderator"];
export const auditTargetTypeOptions = [
  "all",
  "User",
  "Student",
  "Instructor",
  "Course",
  "Category",
  "Enrollment",
  "Payment",
  "Certificate",
  "Review",
  "Notification",
  "Settings",
  "System",
];
