export const adminCategories = [
  {
    id: "CAT-001",
    name: "Web Development",
    slug: "web-development",
    description: "Learn modern web development technologies and frameworks.",
    icon: "Code2",
    status: "active",
    createdAt: "2026-06-12",
    updatedAt: "2026-09-20",
    seoTitle: "Web Development Courses",
    seoDescription: "Explore expert-led web development courses covering frontend, backend, and full-stack skills.",
    courseCount: 124,
    studentCount: 12840,
    averageRating: 4.7,
    completionRate: 78,
    subcategories: [
      {
        id: "SUB-001",
        name: "Frontend Development",
        slug: "frontend-development",
        description: "Frontend technologies and frameworks.",
        status: "active",
        courseCount: 42,
      },
      {
        id: "SUB-002",
        name: "Backend Development",
        slug: "backend-development",
        description: "Server-side development technologies.",
        status: "active",
        courseCount: 28,
      },
      {
        id: "SUB-003",
        name: "Full Stack Development",
        slug: "full-stack-development",
        description: "End-to-end application development workflows.",
        status: "active",
        courseCount: 35,
      },
      {
        id: "SUB-004",
        name: "JavaScript Frameworks",
        slug: "javascript-frameworks",
        description: "Framework-level mastery with React, Vue, and Next.js.",
        status: "active",
        courseCount: 19,
      },
    ],
    topCourses: [
      { id: "CRS-001", title: "React Fundamentals", students: 1240, rating: 4.8 },
      { id: "CRS-002", title: "Next.js Complete Guide", students: 980, rating: 4.7 },
      { id: "CRS-003", title: "JavaScript Mastery", students: 850, rating: 4.9 },
    ],
  },
  {
    id: "CAT-002",
    name: "Programming",
    slug: "programming",
    description: "Sharpen your coding fundamentals and advanced software engineering skills.",
    icon: "Terminal",
    status: "active",
    createdAt: "2026-05-18",
    updatedAt: "2026-09-12",
    seoTitle: "Programming Courses",
    seoDescription: "Explore programming courses in Python, JavaScript, algorithms, and software design.",
    courseCount: 92,
    studentCount: 8400,
    averageRating: 4.6,
    completionRate: 76,
    subcategories: [
      {
        id: "SUB-005",
        name: "Python Development",
        slug: "python-development",
        description: "Python for automation, data, and backend work.",
        status: "active",
        courseCount: 23,
      },
      {
        id: "SUB-006",
        name: "Algorithms",
        slug: "algorithms",
        description: "Core algorithmic techniques and data structures.",
        status: "active",
        courseCount: 17,
      },
      {
        id: "SUB-007",
        name: "Software Engineering",
        slug: "software-engineering",
        description: "Design principles and maintainable engineering workflows.",
        status: "inactive",
        courseCount: 12,
      },
    ],
    topCourses: [
      { id: "CRS-004", title: "Python for Data Science", students: 1180, rating: 4.8 },
      { id: "CRS-005", title: "Advanced Algorithms", students: 760, rating: 4.6 },
      { id: "CRS-006", title: "Clean Code Workflow", students: 650, rating: 4.7 },
    ],
  },
  {
    id: "CAT-003",
    name: "Data Science",
    slug: "data-science",
    description: "Turn data into insights using analytics, statistics, and machine learning.",
    icon: "Database",
    status: "active",
    createdAt: "2026-04-02",
    updatedAt: "2026-09-11",
    seoTitle: "Data Science Courses",
    seoDescription: "Master data analysis, visualization, and machine learning fundamentals.",
    courseCount: 70,
    studentCount: 5180,
    averageRating: 4.8,
    completionRate: 81,
    subcategories: [
      {
        id: "SUB-008",
        name: "Analytics",
        slug: "analytics",
        description: "Analytics and measuring outcomes for business decisions.",
        status: "active",
        courseCount: 24,
      },
      {
        id: "SUB-009",
        name: "Machine Learning",
        slug: "machine-learning",
        description: "Practical ML workflows and model building.",
        status: "active",
        courseCount: 21,
      },
      {
        id: "SUB-010",
        name: "SQL & Reporting",
        slug: "sql-reporting",
        description: "Querying, modeling, and reporting best practices.",
        status: "active",
        courseCount: 16,
      },
    ],
    topCourses: [
      { id: "CRS-007", title: "SQL Mastery for Analysts", students: 980, rating: 4.8 },
      { id: "CRS-008", title: "Python for Data Science", students: 920, rating: 4.9 },
      { id: "CRS-009", title: "ML Foundations", students: 710, rating: 4.7 },
    ],
  },
  {
    id: "CAT-004",
    name: "Design",
    slug: "design",
    description: "Create elegant experiences with design systems, UI, and product thinking.",
    icon: "Palette",
    status: "active",
    createdAt: "2026-03-21",
    updatedAt: "2026-08-28",
    seoTitle: "Design Courses",
    seoDescription: "Learn UI, UX, design systems, and visual storytelling for modern products.",
    courseCount: 63,
    studentCount: 4730,
    averageRating: 4.9,
    completionRate: 82,
    subcategories: [
      {
        id: "SUB-011",
        name: "UI Design",
        slug: "ui-design",
        description: "Craft clean interfaces and product experiences.",
        status: "active",
        courseCount: 19,
      },
      {
        id: "SUB-012",
        name: "UX Research",
        slug: "ux-research",
        description: "Understand user needs and validate product decisions.",
        status: "active",
        courseCount: 15,
      },
      {
        id: "SUB-013",
        name: "Design Systems",
        slug: "design-systems",
        description: "Build scalable, maintainable design foundations.",
        status: "active",
        courseCount: 20,
      },
    ],
    topCourses: [
      { id: "CRS-010", title: "UI/UX Design Systems", students: 1186, rating: 4.9 },
      { id: "CRS-011", title: "Figma for Product Design", students: 740, rating: 4.5 },
      { id: "CRS-012", title: "UX Strategy Blueprint", students: 620, rating: 4.7 },
    ],
  },
  {
    id: "CAT-005",
    name: "Business",
    slug: "business",
    description: "Build leadership, strategy, and operational capability for modern teams.",
    icon: "BriefcaseBusiness",
    status: "active",
    createdAt: "2026-07-09",
    updatedAt: "2026-09-19",
    seoTitle: "Business Courses",
    seoDescription: "Explore business strategy, leadership, and operations for growth-driven teams.",
    courseCount: 48,
    studentCount: 3910,
    averageRating: 4.5,
    completionRate: 72,
    subcategories: [
      {
        id: "SUB-014",
        name: "Leadership",
        slug: "leadership",
        description: "Develop strategy, influence, and team leadership practices.",
        status: "active",
        courseCount: 18,
      },
      {
        id: "SUB-015",
        name: "Operations",
        slug: "operations",
        description: "Improve processes, systems, and execution quality.",
        status: "active",
        courseCount: 14,
      },
      {
        id: "SUB-016",
        name: "Strategy",
        slug: "strategy",
        description: "Understand market opportunities and sustainable business decisions.",
        status: "active",
        courseCount: 16,
      },
    ],
    topCourses: [
      { id: "CRS-013", title: "Business Strategy Bootcamp", students: 640, rating: 4.6 },
      { id: "CRS-014", title: "Leadership Essentials for Teams", students: 570, rating: 4.5 },
      { id: "CRS-015", title: "Operational Excellence", students: 520, rating: 4.4 },
    ],
  },
  {
    id: "CAT-006",
    name: "Marketing",
    slug: "marketing",
    description: "Grow brands and demand with strategic marketing, content, and acquisition skills.",
    icon: "Megaphone",
    status: "inactive",
    createdAt: "2026-05-14",
    updatedAt: "2026-09-06",
    seoTitle: "Marketing Courses",
    seoDescription: "Develop digital marketing, customer acquisition, and growth strategy expertise.",
    courseCount: 34,
    studentCount: 2875,
    averageRating: 4.4,
    completionRate: 68,
    subcategories: [
      {
        id: "SUB-017",
        name: "SEO",
        slug: "seo",
        description: "Search engine optimization and content strategy.",
        status: "inactive",
        courseCount: 10,
      },
      {
        id: "SUB-018",
        name: "Content Marketing",
        slug: "content-marketing",
        description: "Audience-focused content systems and storytelling.",
        status: "active",
        courseCount: 11,
      },
      {
        id: "SUB-019",
        name: "Growth Marketing",
        slug: "growth-marketing",
        description: "Acquisition strategies for startups and modern teams.",
        status: "active",
        courseCount: 13,
      },
    ],
    topCourses: [
      { id: "CRS-016", title: "Digital Marketing Growth Lab", students: 540, rating: 4.3 },
      { id: "CRS-017", title: "Content Strategy Mastery", students: 430, rating: 4.5 },
      { id: "CRS-018", title: "Paid Acquisition Playbook", students: 390, rating: 4.4 },
    ],
  },
  {
    id: "CAT-007",
    name: "Cloud & DevOps",
    slug: "cloud-devops",
    description: "Build infrastructure knowledge and deployment skills for modern software delivery.",
    icon: "Cloud",
    status: "active",
    createdAt: "2026-08-07",
    updatedAt: "2026-09-22",
    seoTitle: "Cloud & DevOps Courses",
    seoDescription: "Learn AWS, automation, systems reliability, and cloud deployment practices.",
    courseCount: 41,
    studentCount: 3560,
    averageRating: 4.6,
    completionRate: 75,
    subcategories: [
      {
        id: "SUB-020",
        name: "Cloud Foundations",
        slug: "cloud-foundations",
        description: "Core cloud concepts and provider fundamentals.",
        status: "active",
        courseCount: 13,
      },
      {
        id: "SUB-021",
        name: "CI/CD",
        slug: "ci-cd",
        description: "Deployment pipelines and delivery automation.",
        status: "active",
        courseCount: 14,
      },
      {
        id: "SUB-022",
        name: "Infrastructure",
        slug: "infrastructure",
        description: "Deployment, scaling, and operational reliability.",
        status: "active",
        courseCount: 14,
      },
    ],
    topCourses: [
      { id: "CRS-019", title: "AWS Cloud Practitioner Bootcamp", students: 740, rating: 4.7 },
      { id: "CRS-020", title: "DevOps Essentials", students: 520, rating: 4.6 },
      { id: "CRS-021", title: "Production Deployment Systems", students: 480, rating: 4.8 },
    ],
  },
  {
    id: "CAT-008",
    name: "Personal Development",
    slug: "personal-development",
    description: "Build habits, productivity, and confidence for sustainable growth.",
    icon: "Sparkles",
    status: "active",
    createdAt: "2026-06-27",
    updatedAt: "2026-09-18",
    seoTitle: "Personal Development Courses",
    seoDescription: "Discover productivity, habits, and personal growth programs.",
    courseCount: 18,
    studentCount: 1960,
    averageRating: 4.5,
    completionRate: 70,
    subcategories: [
      {
        id: "SUB-023",
        name: "Productivity",
        slug: "productivity",
        description: "Work smarter with time and workflow systems.",
        status: "active",
        courseCount: 8,
      },
      {
        id: "SUB-024",
        name: "Habits",
        slug: "habits",
        description: "Build routines and repeatable systems.",
        status: "active",
        courseCount: 5,
      },
      {
        id: "SUB-025",
        name: "Communication",
        slug: "communication",
        description: "Improve confidence, listening, and persuasive ability.",
        status: "active",
        courseCount: 5,
      },
    ],
    topCourses: [
      { id: "CRS-022", title: "High Performance Habits", students: 430, rating: 4.6 },
      { id: "CRS-023", title: "Focus & Productivity Systems", students: 390, rating: 4.4 },
      { id: "CRS-024", title: "Communication Confidence", students: 330, rating: 4.5 },
    ],
  },
  {
    id: "CAT-009",
    name: "Photography",
    slug: "photography",
    description: "Practice visual storytelling, editing, and camera craft across genres.",
    icon: "Camera",
    status: "inactive",
    createdAt: "2026-02-15",
    updatedAt: "2026-08-19",
    seoTitle: "Photography Courses",
    seoDescription: "Explore composition, lighting, editing, and photography fundamentals.",
    courseCount: 0,
    studentCount: 0,
    averageRating: 0,
    completionRate: 0,
    subcategories: [
      {
        id: "SUB-026",
        name: "Portrait Photography",
        slug: "portrait-photography",
        description: "Creating strong portraits and lighting setups.",
        status: "inactive",
        courseCount: 0,
      },
      {
        id: "SUB-027",
        name: "Photo Editing",
        slug: "photo-editing",
        description: "Edit and enhance digital photographs for storytelling.",
        status: "inactive",
        courseCount: 0,
      },
    ],
    topCourses: [],
  },
  {
    id: "CAT-010",
    name: "Other",
    slug: "other",
    description: "Additional learning tracks and cross-disciplinary courses for all learners.",
    icon: "FolderOpen",
    status: "active",
    createdAt: "2026-07-25",
    updatedAt: "2026-09-15",
    seoTitle: "Other Courses",
    seoDescription: "Browse additional educational topics and emerging learning areas.",
    courseCount: 0,
    studentCount: 0,
    averageRating: 0,
    completionRate: 0,
    subcategories: [
      {
        id: "SUB-028",
        name: "General Learning",
        slug: "general-learning",
        description: "Broad categories and general educational topics.",
        status: "active",
        courseCount: 0,
      },
    ],
    topCourses: [],
  },
];

export const adminCategoriesSummary = {
  totalCategories: 10,
  activeCategories: 7,
  totalSubcategories: 32,
  uncategorizedCourses: 12,
};
