export const adminPayments = [
  {
    id: "pay-001",
    transactionId: "TXN-EDU-10245",
    studentId: "stu-001",
    studentName: "Rahul Sharma",
    studentEmail: "rahul@example.com",
    courseId: "course-001",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    amount: 4999,
    currency: "INR",
    paymentMethod: "UPI",
    status: "successful",
    paymentDate: "2026-10-02",
    paymentTime: "14:32",
    enrollmentId: "ENR-2026-00451",
    enrollmentStatus: "active",
    progress: 68,
    paymentReference: "REF-784521",
    gatewayReference: "MOCK-GW-884512",
    invoiceNumber: "INV-2026-00451",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-10-02",
    enrollmentDate: "2026-09-21",
    certificateStatus: "Not Issued",
    notes: "Initial enrollment payment.",
  },
  {
    id: "pay-002",
    transactionId: "TXN-EDU-10246",
    studentId: "stu-002",
    studentName: "Priya Nair",
    studentEmail: "priya@example.com",
    courseId: "course-002",
    courseName: "React Developer Bootcamp",
    instructorId: "inst-002",
    instructorName: "Aisha Khan",
    amount: 3499,
    currency: "INR",
    paymentMethod: "Card",
    status: "successful",
    paymentDate: "2026-10-01",
    paymentTime: "10:15",
    enrollmentId: "ENR-2026-00452",
    enrollmentStatus: "active",
    progress: 42,
    paymentReference: "REF-784522",
    gatewayReference: "MOCK-GW-884513",
    invoiceNumber: "INV-2026-00452",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-10-01",
    enrollmentDate: "2026-09-28",
    certificateStatus: "Not Issued",
    notes: "Front-end track purchase.",
  },
  {
    id: "pay-003",
    transactionId: "TXN-EDU-10247",
    studentId: "stu-003",
    studentName: "Arjun Mehta",
    studentEmail: "arjun@example.com",
    courseId: "course-003",
    courseName: "Python for Data Science",
    instructorId: "inst-003",
    instructorName: "Sonia Verma",
    amount: 2800,
    currency: "INR",
    paymentMethod: "Net Banking",
    status: "pending",
    paymentDate: "2026-09-30",
    paymentTime: "16:20",
    enrollmentId: "ENR-2026-00453",
    enrollmentStatus: "pending",
    progress: 0,
    paymentReference: "REF-784523",
    gatewayReference: "MOCK-GW-884514",
    invoiceNumber: "INV-2026-00453",
    refund: null,
    failureReason: null,
    paymentAttempt: 2,
    lastAttemptDate: "2026-09-30",
    enrollmentDate: "2026-09-30",
    certificateStatus: "Not Issued",
    notes: "Bank confirmation pending.",
  },
  {
    id: "pay-004",
    transactionId: "TXN-EDU-10248",
    studentId: "stu-004",
    studentName: "Meera Iyer",
    studentEmail: "meera@example.com",
    courseId: "course-004",
    courseName: "UI/UX Design Systems",
    instructorId: "inst-004",
    instructorName: "Riya Das",
    amount: 6999,
    currency: "INR",
    paymentMethod: "Card",
    status: "failed",
    paymentDate: "2026-09-28",
    paymentTime: "09:42",
    enrollmentId: "ENR-2026-00454",
    enrollmentStatus: "inactive",
    progress: 0,
    paymentReference: "REF-784524",
    gatewayReference: "MOCK-GW-884515",
    invoiceNumber: "INV-2026-00454",
    refund: null,
    failureReason: "Payment declined",
    paymentAttempt: 2,
    lastAttemptDate: "2026-09-28",
    enrollmentDate: "2026-09-28",
    certificateStatus: "Not Issued",
    notes: "Card bank declined transaction.",
  },
  {
    id: "pay-005",
    transactionId: "TXN-EDU-10249",
    studentId: "stu-005",
    studentName: "Karan Singh",
    studentEmail: "karan@example.com",
    courseId: "course-005",
    courseName: "Digital Marketing Mastery",
    instructorId: "inst-005",
    instructorName: "Sahil Mehra",
    amount: 2599,
    currency: "INR",
    paymentMethod: "Wallet",
    status: "successful",
    paymentDate: "2026-09-26",
    paymentTime: "18:05",
    enrollmentId: "ENR-2026-00455",
    enrollmentStatus: "active",
    progress: 55,
    paymentReference: "REF-784525",
    gatewayReference: "MOCK-GW-884516",
    invoiceNumber: "INV-2026-00455",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-26",
    enrollmentDate: "2026-09-26",
    certificateStatus: "Not Issued",
    notes: "Wallet payment processed.",
  },
  {
    id: "pay-006",
    transactionId: "TXN-EDU-10250",
    studentId: "stu-006",
    studentName: "Ananya Roy",
    studentEmail: "ananya@example.com",
    courseId: "course-006",
    courseName: "Business Strategy Essentials",
    instructorId: "inst-006",
    instructorName: "Kabir Sen",
    amount: 8699,
    currency: "INR",
    paymentMethod: "Card",
    status: "refunded",
    paymentDate: "2026-09-22",
    paymentTime: "12:10",
    enrollmentId: "ENR-2026-00456",
    enrollmentStatus: "cancelled",
    progress: 0,
    paymentReference: "REF-784526",
    gatewayReference: "MOCK-GW-884517",
    invoiceNumber: "INV-2026-00456",
    refund: {
      refundId: "RFND-2026-0182",
      amount: 8699,
      date: "2026-09-24",
      reason: "Course Cancelled",
      status: "processed",
    },
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-22",
    enrollmentDate: "2026-09-22",
    certificateStatus: "Not Issued",
    notes: "Course cancelled by organizer.",
  },
  {
    id: "pay-007",
    transactionId: "TXN-EDU-10251",
    studentId: "stu-007",
    studentName: "Vikram Patel",
    studentEmail: "vikram@example.com",
    courseId: "course-007",
    courseName: "Machine Learning Foundations",
    instructorId: "inst-007",
    instructorName: "Tanvi Kulkarni",
    amount: 12999,
    currency: "INR",
    paymentMethod: "UPI",
    status: "successful",
    paymentDate: "2026-09-18",
    paymentTime: "08:55",
    enrollmentId: "ENR-2026-00457",
    enrollmentStatus: "active",
    progress: 84,
    paymentReference: "REF-784527",
    gatewayReference: "MOCK-GW-884518",
    invoiceNumber: "INV-2026-00457",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-18",
    enrollmentDate: "2026-09-18",
    certificateStatus: "Issued",
    notes: "Premium enrollment paid by UPI.",
  },
  {
    id: "pay-008",
    transactionId: "TXN-EDU-10252",
    studentId: "stu-008",
    studentName: "Neha Chopra",
    studentEmail: "neha@example.com",
    courseId: "course-008",
    courseName: "JavaScript Mastery",
    instructorId: "inst-008",
    instructorName: "Dev Patel",
    amount: 2199,
    currency: "INR",
    paymentMethod: "Card",
    status: "cancelled",
    paymentDate: "2026-09-17",
    paymentTime: "15:40",
    enrollmentId: "ENR-2026-00458",
    enrollmentStatus: "cancelled",
    progress: 0,
    paymentReference: "REF-784528",
    gatewayReference: "MOCK-GW-884519",
    invoiceNumber: "INV-2026-00458",
    refund: null,
    failureReason: "User cancelled checkout",
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-17",
    enrollmentDate: "2026-09-17",
    certificateStatus: "Not Issued",
    notes: "Checkout cancelled before completion.",
  },
  {
    id: "pay-009",
    transactionId: "TXN-EDU-10253",
    studentId: "stu-009",
    studentName: "Rohit Kapoor",
    studentEmail: "rohit@example.com",
    courseId: "course-009",
    courseName: "AWS Cloud Foundations",
    instructorId: "inst-009",
    instructorName: "Mitali Rao",
    amount: 4899,
    currency: "INR",
    paymentMethod: "Net Banking",
    status: "successful",
    paymentDate: "2026-09-16",
    paymentTime: "11:18",
    enrollmentId: "ENR-2026-00459",
    enrollmentStatus: "active",
    progress: 31,
    paymentReference: "REF-784529",
    gatewayReference: "MOCK-GW-884520",
    invoiceNumber: "INV-2026-00459",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-16",
    enrollmentDate: "2026-09-16",
    certificateStatus: "Not Issued",
    notes: "Cloud certification batch enrollment.",
  },
  {
    id: "pay-010",
    transactionId: "TXN-EDU-10254",
    studentId: "stu-010",
    studentName: "Sanya Gupta",
    studentEmail: "sanya@example.com",
    courseId: "course-010",
    courseName: "Advanced SQL & Reporting",
    instructorId: "inst-010",
    instructorName: "Ishaan Khanna",
    amount: 3900,
    currency: "INR",
    paymentMethod: "UPI",
    status: "pending",
    paymentDate: "2026-09-15",
    paymentTime: "13:48",
    enrollmentId: "ENR-2026-00460",
    enrollmentStatus: "pending",
    progress: 0,
    paymentReference: "REF-784530",
    gatewayReference: "MOCK-GW-884521",
    invoiceNumber: "INV-2026-00460",
    refund: null,
    failureReason: null,
    paymentAttempt: 3,
    lastAttemptDate: "2026-09-15",
    enrollmentDate: "2026-09-15",
    certificateStatus: "Not Issued",
    notes: "Verification pending from UPI gateway.",
  },
  {
    id: "pay-011",
    transactionId: "TXN-EDU-10255",
    studentId: "stu-011",
    studentName: "Yash Verma",
    studentEmail: "yash@example.com",
    courseId: "course-011",
    courseName: "Next.js Complete Guide",
    instructorId: "inst-011",
    instructorName: "Nisha Shah",
    amount: 8999,
    currency: "INR",
    paymentMethod: "Card",
    status: "successful",
    paymentDate: "2026-09-12",
    paymentTime: "17:08",
    enrollmentId: "ENR-2026-00461",
    enrollmentStatus: "active",
    progress: 71,
    paymentReference: "REF-784531",
    gatewayReference: "MOCK-GW-884522",
    invoiceNumber: "INV-2026-00461",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-12",
    enrollmentDate: "2026-09-12",
    certificateStatus: "Pending",
    notes: "High-value purchase for full-stack track.",
  },
  {
    id: "pay-012",
    transactionId: "TXN-EDU-10256",
    studentId: "stu-012",
    studentName: "Divya Bansal",
    studentEmail: "divya@example.com",
    courseId: "course-012",
    courseName: "Product Design Roadmap",
    instructorId: "inst-012",
    instructorName: "Rohit Nair",
    amount: 1600,
    currency: "INR",
    paymentMethod: "Wallet",
    status: "successful",
    paymentDate: "2026-09-04",
    paymentTime: "12:07",
    enrollmentId: "ENR-2026-00462",
    enrollmentStatus: "active",
    progress: 53,
    paymentReference: "REF-784532",
    gatewayReference: "MOCK-GW-884523",
    invoiceNumber: "INV-2026-00462",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-09-04",
    enrollmentDate: "2026-09-04",
    certificateStatus: "Not Issued",
    notes: "Promotional wallet transaction.",
  },
  {
    id: "pay-013",
    transactionId: "TXN-EDU-10257",
    studentId: "stu-013",
    studentName: "Harshad Dutta",
    studentEmail: "harshad@example.com",
    courseId: "course-013",
    courseName: "Product Management Essentials",
    instructorId: "inst-013",
    instructorName: "Pooja Jha",
    amount: 3299,
    currency: "INR",
    paymentMethod: "Free Enrollment",
    status: "successful",
    paymentDate: "2026-08-30",
    paymentTime: "09:20",
    enrollmentId: "ENR-2026-00463",
    enrollmentStatus: "active",
    progress: 66,
    paymentReference: "REF-784533",
    gatewayReference: "MOCK-GW-884524",
    invoiceNumber: "INV-2026-00463",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-08-30",
    enrollmentDate: "2026-08-30",
    certificateStatus: "Not Issued",
    notes: "Free enrollment granted by scholarship.",
  },
  {
    id: "pay-014",
    transactionId: "TXN-EDU-10258",
    studentId: "stu-014",
    studentName: "Ishita Malhotra",
    studentEmail: "ishita@example.com",
    courseId: "course-014",
    courseName: "Cybersecurity Fundamentals",
    instructorId: "inst-014",
    instructorName: "Ashok Menon",
    amount: 4999,
    currency: "INR",
    paymentMethod: "Card",
    status: "failed",
    paymentDate: "2026-08-24",
    paymentTime: "19:13",
    enrollmentId: "ENR-2026-00464",
    enrollmentStatus: "inactive",
    progress: 0,
    paymentReference: "REF-784534",
    gatewayReference: "MOCK-GW-884525",
    invoiceNumber: "INV-2026-00464",
    refund: null,
    failureReason: "Insufficient funds",
    paymentAttempt: 3,
    lastAttemptDate: "2026-08-24",
    enrollmentDate: "2026-08-24",
    certificateStatus: "Not Issued",
    notes: "Final retry failed due to bank response.",
  },
  {
    id: "pay-015",
    transactionId: "TXN-EDU-10259",
    studentId: "stu-015",
    studentName: "Aman Bedi",
    studentEmail: "aman@example.com",
    courseId: "course-015",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    amount: 4999,
    currency: "INR",
    paymentMethod: "UPI",
    status: "refunded",
    paymentDate: "2026-08-10",
    paymentTime: "10:02",
    enrollmentId: "ENR-2026-00465",
    enrollmentStatus: "cancelled",
    progress: 0,
    paymentReference: "REF-784535",
    gatewayReference: "MOCK-GW-884526",
    invoiceNumber: "INV-2026-00465",
    refund: {
      refundId: "RFND-2026-0191",
      amount: 4999,
      date: "2026-08-12",
      reason: "Duplicate Payment",
      status: "processed",
    },
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-08-10",
    enrollmentDate: "2026-08-10",
    certificateStatus: "Not Issued",
    notes: "Duplicate purchase detected and reversed.",
  },
  {
    id: "pay-016",
    transactionId: "TXN-EDU-10260",
    studentId: "stu-016",
    studentName: "Nandini Joshi",
    studentEmail: "nandini@example.com",
    courseId: "course-016",
    courseName: "Leadership & Management",
    instructorId: "inst-016",
    instructorName: "Varun Tiwari",
    amount: 7599,
    currency: "INR",
    paymentMethod: "Card",
    status: "successful",
    paymentDate: "2026-08-01",
    paymentTime: "14:46",
    enrollmentId: "ENR-2026-00466",
    enrollmentStatus: "active",
    progress: 90,
    paymentReference: "REF-784536",
    gatewayReference: "MOCK-GW-884527",
    invoiceNumber: "INV-2026-00466",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-08-01",
    enrollmentDate: "2026-08-01",
    certificateStatus: "Eligible",
    notes: "Leadership program completed successfully.",
  },
  {
    id: "pay-017",
    transactionId: "TXN-EDU-10261",
    studentId: "stu-017",
    studentName: "Kavya Reddy",
    studentEmail: "kavya@example.com",
    courseId: "course-017",
    courseName: "Cloud & DevOps Essentials",
    instructorId: "inst-017",
    instructorName: "Anirban Das",
    amount: 6349,
    currency: "INR",
    paymentMethod: "Net Banking",
    status: "successful",
    paymentDate: "2026-07-29",
    paymentTime: "11:11",
    enrollmentId: "ENR-2026-00467",
    enrollmentStatus: "active",
    progress: 48,
    paymentReference: "REF-784537",
    gatewayReference: "MOCK-GW-884528",
    invoiceNumber: "INV-2026-00467",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-07-29",
    enrollmentDate: "2026-07-28",
    certificateStatus: "Not Issued",
    notes: "DevOps career package purchase.",
  },
  {
    id: "pay-018",
    transactionId: "TXN-EDU-10262",
    studentId: "stu-018",
    studentName: "Jatin Sethi",
    studentEmail: "jatin@example.com",
    courseId: "course-018",
    courseName: "Career Growth Blueprint",
    instructorId: "inst-018",
    instructorName: "Maya Shah",
    amount: 2100,
    currency: "INR",
    paymentMethod: "Manual",
    status: "pending",
    paymentDate: "2026-07-22",
    paymentTime: "09:33",
    enrollmentId: "ENR-2026-00468",
    enrollmentStatus: "pending",
    progress: 0,
    paymentReference: "REF-784538",
    gatewayReference: "MOCK-GW-884529",
    invoiceNumber: "INV-2026-00468",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-07-22",
    enrollmentDate: "2026-07-22",
    certificateStatus: "Not Issued",
    notes: "Manual registration assisted by admin.",
  },
  {
    id: "pay-019",
    transactionId: "TXN-EDU-10263",
    studentId: "stu-019",
    studentName: "Shreya Kapoor",
    studentEmail: "shreya@example.com",
    courseId: "course-019",
    courseName: "Figma for Product Design",
    instructorId: "inst-019",
    instructorName: "Ritika Sood",
    amount: 2599,
    currency: "INR",
    paymentMethod: "UPI",
    status: "successful",
    paymentDate: "2026-07-20",
    paymentTime: "08:50",
    enrollmentId: "ENR-2026-00469",
    enrollmentStatus: "active",
    progress: 74,
    paymentReference: "REF-784539",
    gatewayReference: "MOCK-GW-884530",
    invoiceNumber: "INV-2026-00469",
    refund: null,
    failureReason: null,
    paymentAttempt: 1,
    lastAttemptDate: "2026-07-20",
    enrollmentDate: "2026-07-20",
    certificateStatus: "Not Issued",
    notes: "UI design purchase by student wallet top-up.",
  },
  {
    id: "pay-020",
    transactionId: "TXN-EDU-10264",
    studentId: "stu-020",
    studentName: "Rajat Khurana",
    studentEmail: "rajat@example.com",
    courseId: "course-020",
    courseName: "Cybersecurity Bootcamp",
    instructorId: "inst-020",
    instructorName: "Rakesh Singh",
    amount: 9999,
    currency: "INR",
    paymentMethod: "Card",
    status: "failed",
    paymentDate: "2026-07-15",
    paymentTime: "13:09",
    enrollmentId: "ENR-2026-00470",
    enrollmentStatus: "inactive",
    progress: 0,
    paymentReference: "REF-784540",
    gatewayReference: "MOCK-GW-884531",
    invoiceNumber: "INV-2026-00470",
    refund: null,
    failureReason: "3D secure authentication failed",
    paymentAttempt: 2,
    lastAttemptDate: "2026-07-15",
    enrollmentDate: "2026-07-15",
    certificateStatus: "Not Issued",
    notes: "Authentication step failed for premium capture.",
  },
];

export const adminPaymentsSummary = {
  totalRevenue: adminPayments
    .filter((payment) => payment.status === "successful" || payment.status === "refunded")
    .reduce((sum, payment) => sum + Number(payment.amount || 0), 0),
  successfulPayments: adminPayments.filter((payment) => payment.status === "successful").length,
  pendingPayments: adminPayments.filter((payment) => payment.status === "pending").length,
  refundedAmount: adminPayments
    .filter((payment) => payment.status === "refunded")
    .reduce((sum, payment) => sum + Number(payment.amount || 0), 0),
};
