export const adminUsersSummary = {
  totalUsers: 12540,
  students: 10840,
  instructors: 1245,
  administrators: 455,
};

export const adminUsers = [
  {
    id: "USR001",
    name: "Aarav Sharma",
    username: "@aaravsharma",
    email: "aarav@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-09-12",
    courses: 8,
    completedCourses: 3,
    certificates: 2,
    lastActive: "5 minutes ago",
    avatar: null,
  },
  {
    id: "USR002",
    name: "Priya Nair",
    username: "@priyanair",
    email: "priya@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-08-24",
    courses: 12,
    completedCourses: 5,
    certificates: 4,
    lastActive: "2 hours ago",
    avatar: null,
  },
  {
    id: "USR003",
    name: "Daniel Kim",
    username: "@danielkim",
    email: "daniel@example.com",
    role: "instructor",
    status: "active",
    joinedAt: "2026-09-28",
    courses: 14,
    completedCourses: 0,
    certificates: 1,
    lastActive: "1 hour ago",
    avatar: null,
  },
  {
    id: "USR004",
    name: "Sofia Martinez",
    username: "@sofiam",
    email: "sofia@example.com",
    role: "instructor",
    status: "inactive",
    joinedAt: "2026-06-10",
    courses: 6,
    completedCourses: 0,
    certificates: 1,
    lastActive: "3 days ago",
    avatar: null,
  },
  {
    id: "USR005",
    name: "Michael Chen",
    username: "@mchen",
    email: "michael@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2025-11-06",
    courses: 0,
    completedCourses: 0,
    certificates: 0,
    lastActive: "15 minutes ago",
    avatar: null,
  },
  {
    id: "USR006",
    name: "Ava Patel",
    username: "@avapatel",
    email: "ava@example.com",
    role: "student",
    status: "suspended",
    joinedAt: "2026-01-16",
    courses: 4,
    completedCourses: 1,
    certificates: 0,
    lastActive: "Never",
    avatar: null,
  },
  {
    id: "USR007",
    name: "Ethan Brooks",
    username: "@ethanbrooks",
    email: "ethan@example.com",
    role: "instructor",
    status: "active",
    joinedAt: "2026-09-08",
    courses: 9,
    completedCourses: 0,
    certificates: 2,
    lastActive: "Yesterday",
    avatar: null,
  },
  {
    id: "USR008",
    name: "Nia Thompson",
    username: "@niat",
    email: "nia@example.com",
    role: "student",
    status: "inactive",
    joinedAt: "2026-04-03",
    courses: 3,
    completedCourses: 1,
    certificates: 1,
    lastActive: "2 weeks ago",
    avatar: null,
  },
  {
    id: "USR009",
    name: "Lucas Wilson",
    username: "@lucasw",
    email: "lucas@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2026-07-14",
    courses: 0,
    completedCourses: 0,
    certificates: 0,
    lastActive: "30 minutes ago",
    avatar: null,
  },
  {
    id: "USR010",
    name: "Emma Davis",
    username: "@emmad",
    email: "emma@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-09-18",
    courses: 5,
    completedCourses: 2,
    certificates: 1,
    lastActive: "10 minutes ago",
    avatar: null,
  },
  {
    id: "USR011",
    name: "Noah Smith",
    username: "@noahsmith",
    email: "noah@example.com",
    role: "instructor",
    status: "active",
    joinedAt: "2026-07-25",
    courses: 11,
    completedCourses: 0,
    certificates: 3,
    lastActive: "4 hours ago",
    avatar: null,
  },
  {
    id: "USR012",
    name: "Zoe Martin",
    username: "@zoem",
    email: "zoe@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-08-05",
    courses: 7,
    completedCourses: 4,
    certificates: 2,
    lastActive: "6 hours ago",
    avatar: null,
  },
  {
    id: "USR013",
    name: "Leo Nguyen",
    username: "@leong",
    email: "leo@example.com",
    role: "instructor",
    status: "suspended",
    joinedAt: "2025-12-09",
    courses: 10,
    completedCourses: 0,
    certificates: 2,
    lastActive: "3 days ago",
    avatar: null,
  },
  {
    id: "USR014",
    name: "Grace Moore",
    username: "@gracemoore",
    email: "grace@example.com",
    role: "admin",
    status: "inactive",
    joinedAt: "2026-03-12",
    courses: 0,
    completedCourses: 0,
    certificates: 0,
    lastActive: "1 week ago",
    avatar: null,
  },
  {
    id: "USR015",
    name: "Rahul Verma",
    username: "@rahulv",
    email: "rahul@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-09-11",
    courses: 9,
    completedCourses: 6,
    certificates: 3,
    lastActive: "20 minutes ago",
    avatar: null,
  },
  {
    id: "USR016",
    name: "Claire Johnson",
    username: "@clairej",
    email: "claire@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-09-02",
    courses: 2,
    completedCourses: 1,
    certificates: 0,
    lastActive: "1 day ago",
    avatar: null,
  },
  {
    id: "USR017",
    name: "Omar Hassan",
    username: "@omarh",
    email: "omar@example.com",
    role: "instructor",
    status: "active",
    joinedAt: "2026-06-28",
    courses: 13,
    completedCourses: 0,
    certificates: 2,
    lastActive: "8 hours ago",
    avatar: null,
  },
  {
    id: "USR018",
    name: "Hannah Lee",
    username: "@hannahlee",
    email: "hannah@example.com",
    role: "student",
    status: "suspended",
    joinedAt: "2025-10-12",
    courses: 1,
    completedCourses: 0,
    certificates: 0,
    lastActive: "Never",
    avatar: null,
  },
  {
    id: "USR019",
    name: "Isaac Brown",
    username: "@isaacb",
    email: "isaac@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2026-02-18",
    courses: 0,
    completedCourses: 0,
    certificates: 0,
    lastActive: "3 hours ago",
    avatar: null,
  },
  {
    id: "USR020",
    name: "Maya Singh",
    username: "@mayasingh",
    email: "maya@example.com",
    role: "student",
    status: "inactive",
    joinedAt: "2026-05-22",
    courses: 6,
    completedCourses: 2,
    certificates: 1,
    lastActive: "2 weeks ago",
    avatar: null,
  },
  {
    id: "USR021",
    name: "Aria Patel",
    username: "@ariapatel",
    email: "aria@example.com",
    role: "instructor",
    status: "active",
    joinedAt: "2026-08-30",
    courses: 7,
    completedCourses: 0,
    certificates: 1,
    lastActive: "45 minutes ago",
    avatar: null,
  },
  {
    id: "USR022",
    name: "Liam Carter",
    username: "@liamc",
    email: "liam@example.com",
    role: "student",
    status: "active",
    joinedAt: "2026-09-16",
    courses: 4,
    completedCourses: 2,
    certificates: 1,
    lastActive: "12 minutes ago",
    avatar: null,
  },
  {
    id: "USR023",
    name: "Nina Park",
    username: "@ninap",
    email: "nina@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2026-07-02",
    courses: 0,
    completedCourses: 0,
    certificates: 0,
    lastActive: "22 minutes ago",
    avatar: null,
  },
  {
    id: "USR024",
    name: "Oscar Reed",
    username: "@oscarreed",
    email: "oscar@example.com",
    role: "student",
    status: "inactive",
    joinedAt: "2025-09-04",
    courses: 2,
    completedCourses: 1,
    certificates: 0,
    lastActive: "Never",
    avatar: null,
  },
];

export default adminUsers;
