export const adminInstructorsSummary = {
  totalInstructors: 1245,
  activeInstructors: 986,
  pendingApproval: 48,
  averageRating: 4.7,
};

export const adminInstructors = [
  {
    id: "INS-1001",
    name: "John Doe",
    email: "john@example.com",
    expertise: ["React", "Next.js", "JavaScript"],
    status: "active",
    verification: "verified",
    joinedAt: "2026-08-12",
    courses: 12,
    students: 2840,
    rating: 4.8,
    reviews: 245,
    completionRate: 82,
    teachingHours: 640,
    bio: "Frontend engineer and educator specializing in modern web development and advanced JavaScript training.",
    profileComplete: 100,
    phone: "+1 415 555 0123",
    country: "United States",
    experience: "8 years",
    coursesList: [
      { id: "COURSE-001", title: "React Fundamentals", category: "Web Development", status: "published", students: 1240, rating: 4.8, createdAt: "2026-08-20" },
      { id: "COURSE-002", title: "Next.js Masterclass", category: "Frontend", status: "published", students: 980, rating: 4.9, createdAt: "2026-09-02" },
      { id: "COURSE-003", title: "JavaScript Patterns", category: "Programming", status: "draft", students: 0, rating: 0, createdAt: "2026-09-15" },
    ],
  },
  {
    id: "INS-1002",
    name: "Alicia Green",
    email: "alicia@example.com",
    expertise: ["MERN Stack", "Node.js", "MongoDB"],
    status: "active",
    verification: "verified",
    joinedAt: "2026-09-05",
    courses: 9,
    students: 1875,
    rating: 4.9,
    reviews: 196,
    completionRate: 86,
    teachingHours: 540,
    bio: "Full-stack instructor helping developers build production-ready apps with modern backend architectures.",
    profileComplete: 98,
    phone: "+44 7700 900123",
    country: "United Kingdom",
    experience: "10 years",
    coursesList: [
      { id: "COURSE-011", title: "MERN Stack Development", category: "Full Stack", status: "published", students: 980, rating: 4.9, createdAt: "2026-09-08" },
      { id: "COURSE-012", title: "Node.js APIs", category: "Backend", status: "published", students: 760, rating: 4.8, createdAt: "2026-09-18" },
      { id: "COURSE-013", title: "MongoDB Essentials", category: "Database", status: "pending review", students: 135, rating: 4.7, createdAt: "2026-09-21" },
    ],
  },
  {
    id: "INS-1003",
    name: "Sarah Wilson",
    email: "sarah@example.com",
    expertise: ["JavaScript", "TypeScript", "Web Development"],
    status: "pending",
    verification: "pending",
    joinedAt: "2026-10-01",
    courses: 3,
    students: 328,
    rating: 4.6,
    reviews: 42,
    completionRate: 76,
    teachingHours: 180,
    bio: "JavaScript educator focused on frontend architecture, TypeScript patterns, and practical implementation skills.",
    profileComplete: 89,
    phone: "+1 212 555 0168",
    country: "Canada",
    experience: "6 years",
    coursesList: [
      { id: "COURSE-021", title: "JavaScript Mastery", category: "Programming", status: "pending review", students: 180, rating: 4.7, createdAt: "2026-10-01" },
      { id: "COURSE-022", title: "TypeScript Foundations", category: "Frontend", status: "draft", students: 0, rating: 0, createdAt: "2026-10-05" },
    ],
  },
  {
    id: "INS-1004",
    name: "Riya Shah",
    email: "riya@example.com",
    expertise: ["UI/UX", "Design Systems", "Product Design"],
    status: "active",
    verification: "verified",
    joinedAt: "2026-07-19",
    courses: 8,
    students: 1542,
    rating: 4.7,
    reviews: 188,
    completionRate: 80,
    teachingHours: 420,
    bio: "Design lead and educator guiding learners through human-centered product design and interface systems.",
    profileComplete: 95,
    phone: "+91 98210 24567",
    country: "India",
    experience: "7 years",
    coursesList: [
      { id: "COURSE-031", title: "UI/UX Design Essentials", category: "Design", status: "published", students: 840, rating: 4.7, createdAt: "2026-07-23" },
      { id: "COURSE-032", title: "Design Systems Mastery", category: "Design", status: "published", students: 512, rating: 4.8, createdAt: "2026-08-11" },
      { id: "COURSE-033", title: "Figma for Product Teams", category: "Design", status: "draft", students: 0, rating: 0, createdAt: "2026-09-04" },
    ],
  },
  {
    id: "INS-1005",
    name: "Daniel Kim",
    email: "daniel@example.com",
    expertise: ["Next.js", "React", "Full Stack"],
    status: "active",
    verification: "verified",
    joinedAt: "2026-06-27",
    courses: 15,
    students: 3328,
    rating: 4.9,
    reviews: 412,
    completionRate: 88,
    teachingHours: 812,
    bio: "Full-stack engineer building modern product experiences across React, Next.js, and deployment workflows.",
    profileComplete: 100,
    phone: "+82 10 1234 5678",
    country: "South Korea",
    experience: "9 years",
    coursesList: [
      { id: "COURSE-041", title: "Next.js Complete Guide", category: "Frontend", status: "published", students: 1860, rating: 4.9, createdAt: "2026-06-30" },
      { id: "COURSE-042", title: "Production React Apps", category: "Web Development", status: "published", students: 980, rating: 4.8, createdAt: "2026-07-21" },
      { id: "COURSE-043", title: "Frontend Performance", category: "Performance", status: "published", students: 488, rating: 4.7, createdAt: "2026-08-12" },
    ],
  },
  {
    id: "INS-1006",
    name: "Priya Nair",
    email: "priya@example.com",
    expertise: ["Python", "Data Science", "Machine Learning"],
    status: "inactive",
    verification: "unverified",
    joinedAt: "2026-04-08",
    courses: 4,
    students: 695,
    rating: 4.3,
    reviews: 74,
    completionRate: 68,
    teachingHours: 300,
    bio: "Data scientist and educator teaching Python, analytics, and applied machine learning for real-world projects.",
    profileComplete: 72,
    phone: "+91 98765 43210",
    country: "India",
    experience: "5 years",
    coursesList: [
      { id: "COURSE-051", title: "Python for Data Science", category: "Data Science", status: "archived", students: 460, rating: 4.4, createdAt: "2026-04-08" },
      { id: "COURSE-052", title: "Machine Learning Bootcamp", category: "AI", status: "draft", students: 0, rating: 0, createdAt: "2026-07-14" },
    ],
  },
  {
    id: "INS-1007",
    name: "Marcus Lee",
    email: "marcus@example.com",
    expertise: ["Cybersecurity", "Cloud", "DevOps"],
    status: "suspended",
    verification: "verified",
    joinedAt: "2026-03-22",
    courses: 6,
    students: 1245,
    rating: 4.5,
    reviews: 131,
    completionRate: 74,
    teachingHours: 360,
    bio: "Security-focused instructor helping teams understand cloud systems, safeguards, and modern DevOps operations.",
    profileComplete: 86,
    phone: "+1 617 555 0202",
    country: "United States",
    experience: "11 years",
    coursesList: [
      { id: "COURSE-061", title: "Cloud Security Essentials", category: "Security", status: "published", students: 520, rating: 4.6, createdAt: "2026-03-27" },
      { id: "COURSE-062", title: "Azure DevOps", category: "Cloud", status: "published", students: 365, rating: 4.4, createdAt: "2026-04-19" },
      { id: "COURSE-063", title: "Cybersecurity Fundamentals", category: "Security", status: "archived", students: 360, rating: 4.5, createdAt: "2026-06-02" },
    ],
  },
  {
    id: "INS-1008",
    name: "Olivia Brown",
    email: "olivia@example.com",
    expertise: ["UI/UX", "Brand Design", "Marketing"],
    status: "active",
    verification: "verification pending",
    joinedAt: "2026-09-18",
    courses: 5,
    students: 980,
    rating: 4.8,
    reviews: 105,
    completionRate: 83,
    teachingHours: 260,
    bio: "Visual storyteller helping learners create engaging experiences, brands, and conversion-focused design systems.",
    profileComplete: 91,
    phone: "+61 401 234 567",
    country: "Australia",
    experience: "6 years",
    coursesList: [
      { id: "COURSE-071", title: "Brand Design Studio", category: "Marketing", status: "published", students: 435, rating: 4.8, createdAt: "2026-09-22" },
      { id: "COURSE-072", title: "UX Research Basics", category: "Design", status: "published", students: 320, rating: 4.7, createdAt: "2026-10-01" },
    ],
  },
  {
    id: "INS-1009",
    name: "Ethan Brooks",
    email: "ethan@example.com",
    expertise: ["React", "Redux", "Testing"],
    status: "pending",
    verification: "pending",
    joinedAt: "2026-09-28",
    courses: 2,
    students: 244,
    rating: 4.6,
    reviews: 28,
    completionRate: 73,
    teachingHours: 96,
    bio: "React specialist focused on state management, testing strategies, and scalable frontend app architecture.",
    profileComplete: 84,
    phone: "+1 646 555 0116",
    country: "United States",
    experience: "4 years",
    coursesList: [
      { id: "COURSE-081", title: "React State Management", category: "Frontend", status: "pending review", students: 120, rating: 4.6, createdAt: "2026-09-29" },
      { id: "COURSE-082", title: "Testing React Apps", category: "Testing", status: "draft", students: 0, rating: 0, createdAt: "2026-10-02" },
    ],
  },
  {
    id: "INS-1010",
    name: "Noah Smith",
    email: "noah@example.com",
    expertise: ["Python", "Data Analysis", "SQL"],
    status: "active",
    verification: "verified",
    joinedAt: "2026-08-03",
    courses: 11,
    students: 2175,
    rating: 4.8,
    reviews: 301,
    completionRate: 84,
    teachingHours: 680,
    bio: "Analyst and educator helping learners turn raw data into decisions with SQL and Python-based workflows.",
    profileComplete: 97,
    phone: "+1 305 555 0188",
    country: "United States",
    experience: "8 years",
    coursesList: [
      { id: "COURSE-091", title: "Python Data Analysis", category: "Analytics", status: "published", students: 940, rating: 4.8, createdAt: "2026-08-10" },
      { id: "COURSE-092", title: "SQL for Beginners", category: "Data", status: "published", students: 680, rating: 4.7, createdAt: "2026-08-22" },
      { id: "COURSE-093", title: "Advanced Data Storytelling", category: "Analytics", status: "draft", students: 0, rating: 0, createdAt: "2026-09-02" },
    ],
  },
];

export default adminInstructors;
