export const adminCoursesSummary = {
  totalCourses: 486,
  publishedCourses: 342,
  pendingReview: 38,
  draftCourses: 106,
};

export const adminCourses = [
  {
    id: "CRS-1001",
    title: "React Fundamentals",
    slug: "react-fundamentals",
    thumbnail: "",
    instructor: {
      id: "INS-1001",
      name: "John Doe",
      avatar: "",
    },
    category: "Web Development",
    subcategory: "Frontend Development",
    level: "Beginner",
    language: "English",
    price: 1999,
    originalPrice: 2999,
    status: "published",
    students: 2840,
    rating: 4.8,
    reviews: 245,
    completionRate: 82,
    sections: 8,
    lessons: 64,
    quizzes: 6,
    assignments: 4,
    duration: "18h 40m",
    createdAt: "2026-08-20",
    updatedAt: "2026-09-28",
    description: "Learn React fundamentals and build modern web applications with reusable components, state, hooks, and clean frontend architecture.",
    shortDescription: "A practical React course for beginners who want to ship modern interfaces and real-world UI patterns.",
    objectives: [
      "Understand the React component model",
      "Build reusable UI with hooks and state",
      "Manage app state and event flows",
      "Create production-ready frontend logic",
    ],
    requirements: [
      "Basic JavaScript knowledge",
      "A modern browser and code editor",
      "Comfort with HTML and CSS basics",
    ],
    audience: [
      "Frontend developers starting with React",
      "Students looking for hands-on UI practice",
      "Professionals building marketing or SaaS interfaces",
    ],
    skills: [
      "React Components",
      "Hooks",
      "State Management",
      "UI Architecture",
    ],
    curriculum: [
      { title: "JavaScript Fundamentals", lessons: 8, duration: "2h 30m" },
      { title: "Advanced JavaScript", lessons: 10, duration: "3h 10m" },
      { title: "React Fundamentals", lessons: 12, duration: "4h 20m" },
      { title: "State & Effects", lessons: 9, duration: "3h 15m" },
    ],
  },
  {
    id: "CRS-1002",
    title: "Node.js Advanced Backend Mastery",
    slug: "nodejs-advanced-backend-mastery",
    thumbnail: "",
    instructor: {
      id: "INS-1002",
      name: "Sarah Wilson",
      avatar: "",
    },
    category: "Programming",
    subcategory: "Backend Development",
    level: "Advanced",
    language: "English",
    price: 3499,
    originalPrice: 4999,
    status: "pending",
    students: 1284,
    rating: 4.7,
    reviews: 144,
    completionRate: 74,
    sections: 7,
    lessons: 52,
    quizzes: 5,
    assignments: 3,
    duration: "16h 20m",
    createdAt: "2026-09-17",
    updatedAt: "2026-09-30",
    description: "Scale Node.js applications with performance tuning, API design, background jobs, and resilient production patterns.",
    shortDescription: "A backend-focused Node.js course for developers shipping real-world services and APIs.",
    objectives: [
      "Design and secure scalable APIs",
      "Use streams, clusters, and worker patterns",
      "Handle async flows and background jobs",
      "Deploy resilient backend services",
    ],
    requirements: [
      "Node.js basics",
      "REST API understanding",
      "Basic database familiarity",
    ],
    audience: [
      "Backend engineers",
      "Full-stack developers",
      "Developers learning production systems",
    ],
    skills: [
      "Node.js Architecture",
      "API Design",
      "Scaling",
      "Production Patterns",
    ],
    curriculum: [
      { title: "High-performance Node.js", lessons: 9, duration: "2h 40m" },
      { title: "Async Patterns", lessons: 11, duration: "3h 15m" },
      { title: "API Design", lessons: 12, duration: "4h 05m" },
      { title: "Deployment & Monitoring", lessons: 8, duration: "2h 20m" },
    ],
  },
  {
    id: "CRS-1003",
    title: "Python for Data Science",
    slug: "python-for-data-science",
    thumbnail: "",
    instructor: {
      id: "INS-1003",
      name: "Alicia Green",
      avatar: "",
    },
    category: "Data Science",
    subcategory: "Analytics",
    level: "Intermediate",
    language: "English",
    price: 0,
    originalPrice: 0,
    status: "draft",
    students: 0,
    rating: 0,
    reviews: 0,
    completionRate: 0,
    sections: 5,
    lessons: 33,
    quizzes: 4,
    assignments: 2,
    duration: "12h 10m",
    createdAt: "2026-09-12",
    updatedAt: "2026-09-29",
    description: "Use Python to clean data, build models, and create dashboards for modern analytics workflows.",
    shortDescription: "An introduction to practical data science with Python and notebook-based workflows.",
    objectives: [
      "Analyze and clean datasets",
      "Build statistical models with Python",
      "Create dashboards and visual reports",
      "Understand the ML workflow",
    ],
    requirements: [
      "Basic Excel or spreadsheet comfort",
      "Curiosity about datasets and analytics",
      "A computer with Python installed",
    ],
    audience: [
      "Analytics beginners",
      "Students exploring ML",
      "Professionals switching into data roles",
    ],
    skills: [
      "Python",
      "Pandas",
      "Visualization",
      "Data Cleaning",
    ],
    curriculum: [
      { title: "Python Essentials", lessons: 8, duration: "2h 10m" },
      { title: "Data Wrangling", lessons: 9, duration: "2h 50m" },
      { title: "Visualization", lessons: 7, duration: "2h 20m" },
      { title: "Machine Learning Setup", lessons: 6, duration: "2h 30m" },
    ],
  },
  {
    id: "CRS-1004",
    title: "UI/UX Design Systems",
    slug: "uiux-design-systems",
    thumbnail: "",
    instructor: {
      id: "INS-1004",
      name: "Riya Shah",
      avatar: "",
    },
    category: "Design",
    subcategory: "Design Systems",
    level: "Intermediate",
    language: "English",
    price: 2499,
    originalPrice: 3499,
    status: "published",
    students: 1950,
    rating: 4.9,
    reviews: 332,
    completionRate: 88,
    sections: 9,
    lessons: 71,
    quizzes: 7,
    assignments: 5,
    duration: "20h 15m",
    createdAt: "2026-07-11",
    updatedAt: "2026-09-26",
    description: "Build consistent, accessible design systems with tokens, components, and scalable UI patterns.",
    shortDescription: "A premium design course for building visual systems that scale from product to brand.",
    objectives: [
      "Design accessible interfaces",
      "Build scalable design tokens",
      "Systematize UI patterns",
      "Collaborate effectively with engineers",
    ],
    requirements: [
      "Figma or a design tool",
      "A basic understanding of UI principles",
      "A product mindset",
    ],
    audience: [
      "Product designers",
      "UI engineers",
      "Design-led startups",
    ],
    skills: [
      "Design Systems",
      "Accessibility",
      "Visual Hierarchy",
      "Prototyping",
    ],
    curriculum: [
      { title: "Design Foundations", lessons: 8, duration: "2h 30m" },
      { title: "Tokens & Layout", lessons: 10, duration: "3h 10m" },
      { title: "Component Design", lessons: 12, duration: "4h 20m" },
      { title: "Accessibility", lessons: 7, duration: "2h 05m" },
    ],
  },
  {
    id: "CRS-1005",
    title: "Digital Marketing Growth Lab",
    slug: "digital-marketing-growth-lab",
    thumbnail: "",
    instructor: {
      id: "INS-1005",
      name: "Daniel Kim",
      avatar: "",
    },
    category: "Marketing",
    subcategory: "Growth Marketing",
    level: "Beginner",
    language: "English",
    price: 1499,
    originalPrice: 1999,
    status: "rejected",
    students: 910,
    rating: 3.9,
    reviews: 67,
    completionRate: 62,
    sections: 6,
    lessons: 43,
    quizzes: 5,
    assignments: 3,
    duration: "13h 30m",
    createdAt: "2026-09-20",
    updatedAt: "2026-09-29",
    description: "Drive demand with strategy, paid channels, search intent, storytelling, and conversion-focused campaigns.",
    shortDescription: "A growth-focused marketing course tailored to founders, creators, and lean teams.",
    objectives: [
      "Plan acquisition strategies",
      "Build content engines",
      "Measure campaign effectiveness",
      "Convert brand interest into revenue",
    ],
    requirements: [
      "Basic marketing interest",
      "Comfort with spreadsheets",
      "A clear target audience in mind",
    ],
    audience: [
      "Marketing professionals",
      "Founders and operators",
      "Content creators",
    ],
    skills: [
      "SEO",
      "Paid Media",
      "Content Strategy",
      "Conversion Optimization",
    ],
    curriculum: [
      { title: "Growth Foundations", lessons: 7, duration: "2h 00m" },
      { title: "SEO Strategy", lessons: 8, duration: "2h 40m" },
      { title: "Content Funnels", lessons: 9, duration: "3h 00m" },
      { title: "Campaign Measurement", lessons: 6, duration: "2h 15m" },
    ],
  },
  {
    id: "CRS-1006",
    title: "AWS Cloud Practitioner Bootcamp",
    slug: "aws-cloud-practitioner-bootcamp",
    thumbnail: "",
    instructor: {
      id: "INS-1006",
      name: "Imran Ali",
      avatar: "",
    },
    category: "Cloud & DevOps",
    subcategory: "Cloud Computing",
    level: "Beginner",
    language: "English",
    price: 3999,
    originalPrice: 4999,
    status: "published",
    students: 1532,
    rating: 4.6,
    reviews: 193,
    completionRate: 79,
    sections: 7,
    lessons: 55,
    quizzes: 6,
    assignments: 4,
    duration: "17h 00m",
    createdAt: "2026-08-09",
    updatedAt: "2026-09-24",
    description: "Learn the cloud concepts, architecture, networking, and deployment fundamentals needed in modern DevOps roles.",
    shortDescription: "Build a strong cloud foundation with AWS and deployment fundamentals for beginners.",
    objectives: [
      "Understand AWS core services",
      "Learn cloud architecture basics",
      "Deploy simple real-world workloads",
      "Prepare for cloud certifications",
    ],
    requirements: [
      "Basic computer literacy",
      "Curiosity about infrastructure",
      "Willingness to learn cloud concepts",
    ],
    audience: [
      "Career switchers",
      "Developers entering cloud roles",
      "Startup founders",
    ],
    skills: [
      "AWS Basics",
      "Networking",
      "Deployment",
      "Cloud Security",
    ],
    curriculum: [
      { title: "Cloud Foundations", lessons: 8, duration: "2h 30m" },
      { title: "AWS Core Services", lessons: 10, duration: "3h 10m" },
      { title: "Networking", lessons: 9, duration: "3h 00m" },
      { title: "Deployment Basics", lessons: 7, duration: "2h 15m" },
    ],
  },
  {
    id: "CRS-1007",
    title: "Business Strategy Bootcamp",
    slug: "business-strategy-bootcamp",
    thumbnail: "",
    instructor: {
      id: "INS-1007",
      name: "Nina Patel",
      avatar: "",
    },
    category: "Business",
    subcategory: "Strategy",
    level: "Intermediate",
    language: "English",
    price: 2099,
    originalPrice: 2799,
    status: "draft",
    students: 435,
    rating: 4.5,
    reviews: 71,
    completionRate: 68,
    sections: 6,
    lessons: 39,
    quizzes: 4,
    assignments: 2,
    duration: "11h 25m",
    createdAt: "2026-09-22",
    updatedAt: "2026-09-30",
    description: "Learn how strategic planning, market analysis, and decision frameworks help businesses navigate growth and uncertainty.",
    shortDescription: "A practical business course for founders, managers, and operators making strategic decisions every day.",
    objectives: [
      "Frame strategic problems clearly",
      "Assess competitive positioning",
      "Prioritize the right opportunities",
      "Turn strategy into action",
    ],
    requirements: [
      "Basic business awareness",
      "Comfort with decision frameworks",
      "Real-world experience or interest in markets",
    ],
    audience: [
      "Managers",
      "Founders",
      "Business analysts",
    ],
    skills: [
      "Market Analysis",
      "Business Planning",
      "Competitive Strategy",
      "Decision Making",
    ],
    curriculum: [
      { title: "Business Fundamentals", lessons: 7, duration: "2h 10m" },
      { title: "Market Analysis", lessons: 8, duration: "2h 45m" },
      { title: "Strategic Planning", lessons: 9, duration: "3h 15m" },
      { title: "Execution", lessons: 6, duration: "2h 10m" },
    ],
  },
  {
    id: "CRS-1008",
    title: "SQL Mastery for Data Analysts",
    slug: "sql-mastery-for-data-analysts",
    thumbnail: "",
    instructor: {
      id: "INS-1008",
      name: "Priya Nair",
      avatar: "",
    },
    category: "Data Science",
    subcategory: "Database Analytics",
    level: "Beginner",
    language: "English",
    price: 0,
    originalPrice: 0,
    status: "published",
    students: 3275,
    rating: 4.8,
    reviews: 281,
    completionRate: 84,
    sections: 8,
    lessons: 58,
    quizzes: 6,
    assignments: 4,
    duration: "15h 50m",
    createdAt: "2026-06-25",
    updatedAt: "2026-09-21",
    description: "Learn SQL from the ground up and build confidence writing queries that answer real business questions.",
    shortDescription: "A clear and practical SQL course for analysts and business operators working with data.",
    objectives: [
      "Write SQL queries confidently",
      "Join and aggregate data accurately",
      "Create insight-driven reporting flows",
      "Understand relational tables and models",
    ],
    requirements: [
      "No prior SQL knowledge required",
      "A willingness to practice query writing",
      "Basic spreadsheet comfort helpful",
    ],
    audience: [
      "Data analysts",
      "Operations teams",
      "Business professionals",
    ],
    skills: [
      "SQL",
      "Data Queries",
      "Analysis",
      "Reporting",
    ],
    curriculum: [
      { title: "SQL Basics", lessons: 8, duration: "2h 20m" },
      { title: "Joins & Filters", lessons: 11, duration: "3h 15m" },
      { title: "Aggregations", lessons: 9, duration: "2h 55m" },
      { title: "Reporting", lessons: 7, duration: "2h 30m" },
    ],
  },
  {
    id: "CRS-1009",
    title: "Figma for Product Design",
    slug: "figma-for-product-design",
    thumbnail: "",
    instructor: {
      id: "INS-1009",
      name: "Ava Martinez",
      avatar: "",
    },
    category: "Design",
    subcategory: "Product Design",
    level: "Beginner",
    language: "English",
    price: 1799,
    originalPrice: 2499,
    status: "archived",
    students: 642,
    rating: 4.2,
    reviews: 88,
    completionRate: 63,
    sections: 5,
    lessons: 32,
    quizzes: 3,
    assignments: 2,
    duration: "10h 45m",
    createdAt: "2026-05-20",
    updatedAt: "2026-09-18",
    description: "Master Figma workflows for wireframing, prototypes, and design handoff while building a reusable portfolio-ready toolkit.",
    shortDescription: "An approachable product design course for beginners who want to create polished user-facing interfaces.",
    objectives: [
      "Navigate Figma confidently",
      "Prototype interactions and flows",
      "Create polished interfaces from concept to handoff",
      "Prepare a portfolio-ready design project",
    ],
    requirements: [
      "No prior design knowledge required",
      "A stable internet connection",
      "Figma installed or a browser-based access",
    ],
    audience: [
      "New designers",
      "Product enthusiasts",
      "Junior UX designers",
    ],
    skills: [
      "Figma",
      "Wireframing",
      "Prototyping",
      "Design Handoff",
    ],
    curriculum: [
      { title: "Figma Basics", lessons: 7, duration: "2h 05m" },
      { title: "Layouts & Components", lessons: 8, duration: "2h 30m" },
      { title: "Prototype Flows", lessons: 6, duration: "2h 15m" },
      { title: "Handoff", lessons: 5, duration: "1h 40m" },
    ],
  },
  {
    id: "CRS-1010",
    title: "Full-Stack Next.js Development",
    slug: "full-stack-nextjs-development",
    thumbnail: "",
    instructor: {
      id: "INS-1010",
      name: "Michael Chen",
      avatar: "",
    },
    category: "Web Development",
    subcategory: "Full Stack",
    level: "Advanced",
    language: "English",
    price: 4999,
    originalPrice: 6999,
    status: "pending",
    students: 880,
    rating: 4.7,
    reviews: 102,
    completionRate: 76,
    sections: 9,
    lessons: 72,
    quizzes: 7,
    assignments: 5,
    duration: "22h 05m",
    createdAt: "2026-09-19",
    updatedAt: "2026-10-01",
    description: "Create a production-grade full-stack app with Next.js, authentication, APIs, data layers, and deployment strategies.",
    shortDescription: "A hands-on, advanced project course for building ambitious products with Next.js.",
    objectives: [
      "Create full-stack product workflows",
      "Integrate auth and APIs reliably",
      "Ship production-ready architecture",
      "Deploy to a real hosting platform",
    ],
    requirements: [
      "React and JavaScript proficiency",
      "Comfort with web app structure",
      "Willingness to build projects end-to-end",
    ],
    audience: [
      "Full-stack engineers",
      "Launchers building SaaS products",
      "Product-focused developers",
    ],
    skills: [
      "Next.js",
      "API Routes",
      "Auth",
      "Deployment",
    ],
    curriculum: [
      { title: "App Architecture", lessons: 8, duration: "2h 50m" },
      { title: "Data Layer", lessons: 9, duration: "3h 00m" },
      { title: "Authentication", lessons: 7, duration: "2h 20m" },
      { title: "Production Deployment", lessons: 8, duration: "2h 40m" },
    ],
  },
  {
    id: "CRS-1011",
    title: "Python Automation for Workflows",
    slug: "python-automation-for-workflows",
    thumbnail: "",
    instructor: {
      id: "INS-1011",
      name: "Lucas Brown",
      avatar: "",
    },
    category: "Programming",
    subcategory: "Automation",
    level: "Beginner",
    language: "English",
    price: 999,
    originalPrice: 1499,
    status: "published",
    students: 2340,
    rating: 4.4,
    reviews: 189,
    completionRate: 71,
    sections: 6,
    lessons: 42,
    quizzes: 5,
    assignments: 3,
    duration: "12h 20m",
    createdAt: "2026-09-10",
    updatedAt: "2026-09-27",
    description: "Automate repetitive tasks with Python scripts, file processing, APIs, and workflow orchestration concepts.",
    shortDescription: "A Python automation course for professionals streamlining tasks and boosting productivity.",
    objectives: [
      "Automate file conversions",
      "Read and write data efficiently",
      "Use APIs from scripts",
      "Create simple workflow automation pipelines",
    ],
    requirements: [
      "Basic Python comfort",
      "A desktop or laptop",
      "A practical task to automate",
    ],
    audience: [
      "Operations teams",
      "Analysts",
      "Small-business owners",
    ],
    skills: [
      "Python Scripts",
      "Automation",
      "Task Scheduling",
      "API Integration",
    ],
    curriculum: [
      { title: "Python Basics", lessons: 7, duration: "2h 10m" },
      { title: "File Automation", lessons: 8, duration: "2h 45m" },
      { title: "APIs", lessons: 7, duration: "2h 40m" },
      { title: "Workflows", lessons: 6, duration: "2h 15m" },
    ],
  },
  {
    id: "CRS-1012",
    title: "Leadership Essentials for Teams",
    slug: "leadership-essentials-for-teams",
    thumbnail: "",
    instructor: {
      id: "INS-1012",
      name: "Harper Lee",
      avatar: "",
    },
    category: "Other",
    subcategory: "Leadership",
    level: "Intermediate",
    language: "English",
    price: 1299,
    originalPrice: 1899,
    status: "published",
    students: 1110,
    rating: 4.5,
    reviews: 136,
    completionRate: 75,
    sections: 6,
    lessons: 40,
    quizzes: 4,
    assignments: 3,
    duration: "11h 40m",
    createdAt: "2026-08-17",
    updatedAt: "2026-09-23",
    description: "Develop leadership clarity, communication, trust-building, and team momentum in modern business environments.",
    shortDescription: "A practical leadership course for team leads, managers, and future leaders who want stronger influence.",
    objectives: [
      "Lead with clarity and empathy",
      "Communicate team direction effectively",
      "Build accountability and trust",
      "Move teams from friction to momentum",
    ],
    requirements: [
      "Team or project context helpful",
      "Interest in leading people",
      "Willingness to reflect on leadership habits",
    ],
    audience: [
      "Team leads",
      "Managers",
      "Aspiring leaders",
    ],
    skills: [
      "Leadership",
      "Team Dynamics",
      "Communication",
      "Coaching",
    ],
    curriculum: [
      { title: "Leadership Foundations", lessons: 7, duration: "2h 15m" },
      { title: "Communication", lessons: 8, duration: "2h 40m" },
      { title: "Team Building", lessons: 7, duration: "2h 30m" },
      { title: "Decision Making", lessons: 6, duration: "2h 05m" },
    ],
  },
];
