export const permissionDefinitions = [
  { key: "dashboard", label: "Dashboard" },
  { key: "settings", label: "Settings" },
  { key: "systemHealth", label: "System Health" },
  { key: "auditLogs", label: "Audit Logs" },
  { key: "users", label: "Users" },
  { key: "students", label: "Students" },
  { key: "instructors", label: "Instructors" },
  { key: "courses", label: "Courses" },
  { key: "categories", label: "Categories" },
  { key: "enrollments", label: "Enrollments" },
  { key: "reviews", label: "Reviews" },
  { key: "certificates", label: "Certificates" },
  { key: "assignments", label: "Assignments" },
  { key: "quizzes", label: "Quizzes" },
  { key: "payments", label: "Payments" },
  { key: "reports", label: "Reports" },
  { key: "notifications", label: "Notifications" },
];

export const permissionGroups = [
  { title: "Platform", items: ["dashboard", "settings", "systemHealth", "auditLogs"] },
  { title: "Users", items: ["users", "students", "instructors"] },
  { title: "Learning", items: ["courses", "categories", "enrollments"] },
  { title: "Content", items: ["reviews", "certificates", "assignments", "quizzes"] },
  { title: "Financial", items: ["payments", "reports"] },
  { title: "Communication", items: ["notifications"] },
];

export function createDefaultPermissionSet() {
  return permissionDefinitions.reduce((accumulator, permission) => {
    accumulator[permission.key] = {
      view: false,
      create: false,
      edit: false,
      delete: false,
      approve: false,
      export: false,
    };
    return accumulator;
  }, {});
}

export const adminRoles = [
  {
    id: "role-super-admin",
    name: "Super Admin",
    description: "Full access to all EduLearn administrative features.",
    type: "system",
    status: "active",
    usersCount: 2,
    createdAt: "2026-01-01",
    updatedAt: "2026-10-01",
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      settings: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      systemHealth: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      auditLogs: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      users: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      students: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      instructors: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      courses: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      categories: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      enrollments: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      reviews: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      certificates: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      assignments: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      quizzes: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      payments: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      reports: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      notifications: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
    },
  },
  {
    id: "role-admin",
    name: "Admin",
    description: "Manages administrative workflows, platform operations, and operational oversight.",
    type: "system",
    status: "active",
    usersCount: 3,
    createdAt: "2026-01-15",
    updatedAt: "2026-09-27",
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      settings: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      systemHealth: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      auditLogs: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      users: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      students: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      instructors: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      courses: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      categories: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      enrollments: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      reviews: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      certificates: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      assignments: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      quizzes: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      payments: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      reports: { view: true, create: false, edit: false, delete: false, approve: true, export: true },
      notifications: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
    },
  },
  {
    id: "role-moderator",
    name: "Moderator",
    description: "Can review and moderate community-generated content.",
    type: "system",
    status: "active",
    usersCount: 2,
    createdAt: "2026-02-01",
    updatedAt: "2026-09-08",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      systemHealth: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      auditLogs: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      users: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      students: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      instructors: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      courses: { view: true, create: false, edit: false, delete: false, approve: true, export: false },
      categories: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      enrollments: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      reviews: { view: true, create: false, edit: true, delete: true, approve: true, export: true },
      certificates: { view: true, create: false, edit: false, delete: false, approve: true, export: true },
      assignments: { view: true, create: false, edit: true, delete: false, approve: true, export: false },
      quizzes: { view: true, create: false, edit: true, delete: false, approve: true, export: false },
      payments: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      notifications: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
    },
  },
  {
    id: "role-instructor-manager",
    name: "Instructor Manager",
    description: "Can manage instructor profiles and course-related instructor operations.",
    type: "custom",
    status: "active",
    usersCount: 4,
    createdAt: "2026-03-11",
    updatedAt: "2026-09-19",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      systemHealth: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      auditLogs: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      users: { view: true, create: false, edit: true, delete: false, approve: false, export: false },
      students: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      instructors: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      courses: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
      categories: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      enrollments: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      reviews: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      certificates: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      assignments: { view: true, create: true, edit: true, delete: false, approve: false, export: false },
      quizzes: { view: true, create: false, edit: true, delete: false, approve: false, export: false },
      payments: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      notifications: { view: true, create: true, edit: true, delete: false, approve: false, export: true },
    },
  },
  {
    id: "role-content-manager",
    name: "Content Manager",
    description: "Can manage courses, categories, quizzes, and learning content.",
    type: "custom",
    status: "active",
    usersCount: 3,
    createdAt: "2026-04-06",
    updatedAt: "2026-09-28",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      systemHealth: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      auditLogs: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      users: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      students: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      instructors: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      courses: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      categories: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      enrollments: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      reviews: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      certificates: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
      assignments: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      quizzes: { view: true, create: true, edit: true, delete: true, approve: true, export: true },
      payments: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      notifications: { view: true, create: true, edit: true, delete: false, approve: true, export: true },
    },
  },
  {
    id: "role-support-agent",
    name: "Support Agent",
    description: "Can view student and enrollment information and assist with support workflows.",
    type: "custom",
    status: "inactive",
    usersCount: 4,
    createdAt: "2026-05-14",
    updatedAt: "2026-08-01",
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      systemHealth: { view: false, create: false, edit: false, delete: false, approve: false, export: false },
      auditLogs: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      users: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      students: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      instructors: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      courses: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      categories: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      enrollments: { view: true, create: false, edit: true, delete: false, approve: false, export: true },
      reviews: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      certificates: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      assignments: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      quizzes: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      payments: { view: true, create: false, edit: false, delete: false, approve: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, approve: false, export: true },
      notifications: { view: true, create: false, edit: true, delete: false, approve: true, export: true },
    },
  },
];

export const roleUserAssignments = {
  "role-super-admin": [
    { name: "Aarav Sharma", email: "aarav@edulearn.example", role: "Super Admin", status: "Active" },
    { name: "Meera Patel", email: "meera@edulearn.example", role: "Super Admin", status: "Active" },
  ],
  "role-admin": [
    { name: "Riya Kapoor", email: "riya@edulearn.example", role: "Admin", status: "Active" },
    { name: "Daniel Mensah", email: "daniel@edulearn.example", role: "Admin", status: "Active" },
    { name: "Sonia Verma", email: "sonia@edulearn.example", role: "Admin", status: "Active" },
  ],
  "role-moderator": [
    { name: "Ishaan Khanna", email: "ishaan@edulearn.example", role: "Moderator", status: "Active" },
    { name: "Leah Martins", email: "leah@edulearn.example", role: "Moderator", status: "Active" },
  ],
  "role-instructor-manager": [
    { name: "Nikhil Bose", email: "nikhil@edulearn.example", role: "Instructor Manager", status: "Active" },
    { name: "Priya Nair", email: "priya@edulearn.example", role: "Instructor Manager", status: "Active" },
    { name: "Alan Furtado", email: "alan@edulearn.example", role: "Instructor Manager", status: "Active" },
    { name: "Sara Ibrahim", email: "sara@edulearn.example", role: "Instructor Manager", status: "Inactive" },
  ],
  "role-content-manager": [
    { name: "Maya Singh", email: "maya@edulearn.example", role: "Content Manager", status: "Active" },
    { name: "Owen Clark", email: "owen@edulearn.example", role: "Content Manager", status: "Active" },
    { name: "Hina Shah", email: "hina@edulearn.example", role: "Content Manager", status: "Inactive" },
  ],
  "role-support-agent": [
    { name: "Tara Wilson", email: "tara@edulearn.example", role: "Support Agent", status: "Inactive" },
    { name: "Jatin Rao", email: "jatin@edulearn.example", role: "Support Agent", status: "Inactive" },
    { name: "Rhea Gomez", email: "rhea@edulearn.example", role: "Support Agent", status: "Active" },
    { name: "Vikram Das", email: "vikram@edulearn.example", role: "Support Agent", status: "Active" },
  ],
};

export const roleActivityRecords = [
  { action: "Admin role updated", actor: "Aarav Sharma", timestamp: "2 hours ago", status: "Success" },
  { action: "Moderator permissions changed", actor: "Leah Martins", timestamp: "Yesterday", status: "Success" },
  { action: "Course Manager created", actor: "Riya Kapoor", timestamp: "2 days ago", status: "Success" },
  { action: "Support Agent activated", actor: "Meera Patel", timestamp: "3 days ago", status: "Success" },
  { action: "Instructor Manager access reviewed", actor: "Daniel Mensah", timestamp: "5 days ago", status: "Review" },
];

export const lockedPermissionsByRole = {
  "role-super-admin": [
    "dashboard",
    "settings",
    "systemHealth",
    "auditLogs",
    "users",
    "students",
    "instructors",
    "reports",
  ],
};
