export const adminCertificates = [
  {
    id: "cert-001",
    certificateId: "CERT-EDU-10245",
    verificationCode: "VERIFY-784521",
    verificationStatus: "verified",
    studentId: "stu-001",
    studentName: "Rahul Sharma",
    studentEmail: "rahul@example.com",
    courseId: "course-001",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    certificateType: "Course Completion",
    issueDate: "2026-10-02",
    completionDate: "2026-09-30",
    expiryDate: null,
    score: 92,
    completionPercentage: 100,
    lessonsCompleted: 48,
    totalLessons: 48,
    quizScore: 94,
    assignmentScore: 90,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Full Stack Development Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-002",
    certificateId: "CERT-EDU-10246",
    verificationCode: "VERIFY-784522",
    verificationStatus: "verified",
    studentId: "stu-002",
    studentName: "Priya Nair",
    studentEmail: "priya@example.com",
    courseId: "course-002",
    courseName: "React Developer Bootcamp",
    instructorId: "inst-002",
    instructorName: "Aisha Khan",
    certificateType: "Achievement",
    issueDate: "2026-10-01",
    completionDate: "2026-09-28",
    expiryDate: null,
    score: 88,
    completionPercentage: 94,
    lessonsCompleted: 35,
    totalLessons: 37,
    quizScore: 90,
    assignmentScore: 87,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "React Developer Bootcamp Achievement",
    courseStatus: "Completed",
    courseProgress: 94,
  },
  {
    id: "cert-003",
    certificateId: "CERT-EDU-10247",
    verificationCode: "VERIFY-784523",
    verificationStatus: "pending",
    studentId: "stu-003",
    studentName: "Arjun Mehta",
    studentEmail: "arjun@example.com",
    courseId: "course-003",
    courseName: "Python for Data Science",
    instructorId: "inst-003",
    instructorName: "Sonia Verma",
    certificateType: "Professional Certificate",
    issueDate: "2026-09-30",
    completionDate: "2026-09-26",
    expiryDate: null,
    score: 81,
    completionPercentage: 88,
    lessonsCompleted: 22,
    totalLessons: 25,
    quizScore: 83,
    assignmentScore: 79,
    status: "pending",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Python for Data Science Professional Certificate",
    courseStatus: "In Progress",
    courseProgress: 88,
  },
  {
    id: "cert-004",
    certificateId: "CERT-EDU-10248",
    verificationCode: "VERIFY-784524",
    verificationStatus: "unverified",
    studentId: "stu-004",
    studentName: "Meera Iyer",
    studentEmail: "meera@example.com",
    courseId: "course-004",
    courseName: "UI/UX Design Systems",
    instructorId: "inst-004",
    instructorName: "Riya Das",
    certificateType: "Course Completion",
    issueDate: "2026-09-29",
    completionDate: "2026-09-24",
    expiryDate: "2027-09-24",
    score: 95,
    completionPercentage: 100,
    lessonsCompleted: 30,
    totalLessons: 30,
    quizScore: 96,
    assignmentScore: 94,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "UI/UX Design Systems Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-005",
    certificateId: "CERT-EDU-10249",
    verificationCode: "VERIFY-784525",
    verificationStatus: "verified",
    studentId: "stu-005",
    studentName: "Karan Singh",
    studentEmail: "karan@example.com",
    courseId: "course-005",
    courseName: "Digital Marketing Mastery",
    instructorId: "inst-005",
    instructorName: "Sahil Mehra",
    certificateType: "Achievement",
    issueDate: "2026-09-26",
    completionDate: "2026-09-22",
    expiryDate: null,
    score: 79,
    completionPercentage: 86,
    lessonsCompleted: 18,
    totalLessons: 21,
    quizScore: 82,
    assignmentScore: 76,
    status: "pending",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Digital Marketing Mastery Achievement",
    courseStatus: "Completed",
    courseProgress: 86,
  },
  {
    id: "cert-006",
    certificateId: "CERT-EDU-10250",
    verificationCode: "VERIFY-784526",
    verificationStatus: "revoked",
    studentId: "stu-006",
    studentName: "Ananya Roy",
    studentEmail: "ananya@example.com",
    courseId: "course-006",
    courseName: "Business Strategy Essentials",
    instructorId: "inst-006",
    instructorName: "Kabir Sen",
    certificateType: "Professional Certificate",
    issueDate: "2026-09-22",
    completionDate: "2026-09-18",
    expiryDate: null,
    score: 74,
    completionPercentage: 82,
    lessonsCompleted: 22,
    totalLessons: 27,
    quizScore: 76,
    assignmentScore: 72,
    status: "revoked",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Business Strategy Essentials Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 82,
  },
  {
    id: "cert-007",
    certificateId: "CERT-EDU-10251",
    verificationCode: "VERIFY-784527",
    verificationStatus: "verified",
    studentId: "stu-007",
    studentName: "Vikram Patel",
    studentEmail: "vikram@example.com",
    courseId: "course-007",
    courseName: "Machine Learning Foundations",
    instructorId: "inst-007",
    instructorName: "Tanvi Kulkarni",
    certificateType: "Professional Certificate",
    issueDate: "2026-09-18",
    completionDate: "2026-09-15",
    expiryDate: "2028-09-15",
    score: 96,
    completionPercentage: 100,
    lessonsCompleted: 40,
    totalLessons: 40,
    quizScore: 97,
    assignmentScore: 95,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Machine Learning Foundations Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-008",
    certificateId: "CERT-EDU-10252",
    verificationCode: "VERIFY-784528",
    verificationStatus: "unverified",
    studentId: "stu-008",
    studentName: "Neha Chopra",
    studentEmail: "neha@example.com",
    courseId: "course-008",
    courseName: "JavaScript Mastery",
    instructorId: "inst-008",
    instructorName: "Dev Patel",
    certificateType: "Course Completion",
    issueDate: "2026-09-17",
    completionDate: "2026-09-12",
    expiryDate: null,
    score: 66,
    completionPercentage: 75,
    lessonsCompleted: 21,
    totalLessons: 28,
    quizScore: 68,
    assignmentScore: 64,
    status: "pending",
    issuedBy: "EduLearn Academy",
    certificateTitle: "JavaScript Mastery Certificate",
    courseStatus: "Completed",
    courseProgress: 75,
  },
  {
    id: "cert-009",
    certificateId: "CERT-EDU-10253",
    verificationCode: "VERIFY-784529",
    verificationStatus: "verified",
    studentId: "stu-009",
    studentName: "Rohit Kapoor",
    studentEmail: "rohit@example.com",
    courseId: "course-009",
    courseName: "AWS Cloud Foundations",
    instructorId: "inst-009",
    instructorName: "Mitali Rao",
    certificateType: "Professional Certificate",
    issueDate: "2026-09-16",
    completionDate: "2026-09-11",
    expiryDate: "2027-09-11",
    score: 91,
    completionPercentage: 100,
    lessonsCompleted: 26,
    totalLessons: 26,
    quizScore: 93,
    assignmentScore: 89,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "AWS Cloud Foundations Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-010",
    certificateId: "CERT-EDU-10254",
    verificationCode: "VERIFY-784530",
    verificationStatus: "verified",
    studentId: "stu-010",
    studentName: "Sanya Gupta",
    studentEmail: "sanya@example.com",
    courseId: "course-010",
    courseName: "Advanced SQL & Reporting",
    instructorId: "inst-010",
    instructorName: "Ishaan Khanna",
    certificateType: "Course Completion",
    issueDate: "2026-09-15",
    completionDate: "2026-09-13",
    expiryDate: null,
    score: 87,
    completionPercentage: 94,
    lessonsCompleted: 29,
    totalLessons: 31,
    quizScore: 89,
    assignmentScore: 85,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Advanced SQL & Reporting Certificate",
    courseStatus: "Completed",
    courseProgress: 94,
  },
  {
    id: "cert-011",
    certificateId: "CERT-EDU-10255",
    verificationCode: "VERIFY-784531",
    verificationStatus: "pending",
    studentId: "stu-011",
    studentName: "Yash Verma",
    studentEmail: "yash@example.com",
    courseId: "course-011",
    courseName: "Next.js Complete Guide",
    instructorId: "inst-011",
    instructorName: "Nisha Shah",
    certificateType: "Professional Certificate",
    issueDate: "2026-09-12",
    completionDate: "2026-09-10",
    expiryDate: null,
    score: 98,
    completionPercentage: 100,
    lessonsCompleted: 42,
    totalLessons: 42,
    quizScore: 99,
    assignmentScore: 97,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Next.js Complete Guide Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-012",
    certificateId: "CERT-EDU-10256",
    verificationCode: "VERIFY-784532",
    verificationStatus: "verified",
    studentId: "stu-012",
    studentName: "Divya Bansal",
    studentEmail: "divya@example.com",
    courseId: "course-012",
    courseName: "Product Design Roadmap",
    instructorId: "inst-012",
    instructorName: "Rohit Nair",
    certificateType: "Achievement",
    issueDate: "2026-09-04",
    completionDate: "2026-08-30",
    expiryDate: null,
    score: 69,
    completionPercentage: 80,
    lessonsCompleted: 20,
    totalLessons: 25,
    quizScore: 72,
    assignmentScore: 66,
    status: "expired",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Product Design Roadmap Achievement",
    courseStatus: "Completed",
    courseProgress: 80,
  },
  {
    id: "cert-013",
    certificateId: "CERT-EDU-10257",
    verificationCode: "VERIFY-784533",
    verificationStatus: "verified",
    studentId: "stu-013",
    studentName: "Harshad Dutta",
    studentEmail: "harshad@example.com",
    courseId: "course-013",
    courseName: "Product Management Essentials",
    instructorId: "inst-013",
    instructorName: "Pooja Jha",
    certificateType: "Course Completion",
    issueDate: "2026-08-30",
    completionDate: "2026-08-24",
    expiryDate: "2027-08-24",
    score: 83,
    completionPercentage: 92,
    lessonsCompleted: 18,
    totalLessons: 20,
    quizScore: 84,
    assignmentScore: 81,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Product Management Essentials Certificate",
    courseStatus: "Completed",
    courseProgress: 92,
  },
  {
    id: "cert-014",
    certificateId: "CERT-EDU-10258",
    verificationCode: "VERIFY-784534",
    verificationStatus: "unverified",
    studentId: "stu-014",
    studentName: "Ishita Malhotra",
    studentEmail: "ishita@example.com",
    courseId: "course-014",
    courseName: "Cybersecurity Fundamentals",
    instructorId: "inst-014",
    instructorName: "Ashok Menon",
    certificateType: "Professional Certificate",
    issueDate: "2026-08-24",
    completionDate: "2026-08-18",
    expiryDate: "2027-08-18",
    score: 61,
    completionPercentage: 71,
    lessonsCompleted: 17,
    totalLessons: 24,
    quizScore: 64,
    assignmentScore: 59,
    status: "pending",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Cybersecurity Fundamentals Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 71,
  },
  {
    id: "cert-015",
    certificateId: "CERT-EDU-10259",
    verificationCode: "VERIFY-784535",
    verificationStatus: "revoked",
    studentId: "stu-015",
    studentName: "Aman Bedi",
    studentEmail: "aman@example.com",
    courseId: "course-015",
    courseName: "Full Stack Development",
    instructorId: "inst-001",
    instructorName: "John Doe",
    certificateType: "Course Completion",
    issueDate: "2026-08-10",
    completionDate: "2026-08-01",
    expiryDate: null,
    score: 70,
    completionPercentage: 82,
    lessonsCompleted: 25,
    totalLessons: 30,
    quizScore: 72,
    assignmentScore: 68,
    status: "revoked",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Full Stack Development Course Completion",
    courseStatus: "Completed",
    courseProgress: 82,
  },
  {
    id: "cert-016",
    certificateId: "CERT-EDU-10260",
    verificationCode: "VERIFY-784536",
    verificationStatus: "verified",
    studentId: "stu-016",
    studentName: "Nandini Joshi",
    studentEmail: "nandini@example.com",
    courseId: "course-016",
    courseName: "Leadership & Management",
    instructorId: "inst-016",
    instructorName: "Varun Tiwari",
    certificateType: "Professional Certificate",
    issueDate: "2026-08-01",
    completionDate: "2026-07-25",
    expiryDate: "2028-07-25",
    score: 94,
    completionPercentage: 100,
    lessonsCompleted: 32,
    totalLessons: 32,
    quizScore: 95,
    assignmentScore: 93,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Leadership & Management Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 100,
  },
  {
    id: "cert-017",
    certificateId: "CERT-EDU-10261",
    verificationCode: "VERIFY-784537",
    verificationStatus: "verified",
    studentId: "stu-017",
    studentName: "Kavya Reddy",
    studentEmail: "kavya@example.com",
    courseId: "course-017",
    courseName: "Cloud & DevOps Essentials",
    instructorId: "inst-017",
    instructorName: "Anirban Das",
    certificateType: "Course Completion",
    issueDate: "2026-07-29",
    completionDate: "2026-07-21",
    expiryDate: null,
    score: 89,
    completionPercentage: 96,
    lessonsCompleted: 31,
    totalLessons: 32,
    quizScore: 92,
    assignmentScore: 86,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Cloud & DevOps Essentials Certificate",
    courseStatus: "Completed",
    courseProgress: 96,
  },
  {
    id: "cert-018",
    certificateId: "CERT-EDU-10262",
    verificationCode: "VERIFY-784538",
    verificationStatus: "unverified",
    studentId: "stu-018",
    studentName: "Jatin Sethi",
    studentEmail: "jatin@example.com",
    courseId: "course-018",
    courseName: "Career Growth Blueprint",
    instructorId: "inst-018",
    instructorName: "Maya Shah",
    certificateType: "Achievement",
    issueDate: "2026-07-22",
    completionDate: "2026-07-19",
    expiryDate: null,
    score: 77,
    completionPercentage: 85,
    lessonsCompleted: 16,
    totalLessons: 19,
    quizScore: 80,
    assignmentScore: 74,
    status: "pending",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Career Growth Blueprint Achievement",
    courseStatus: "Completed",
    courseProgress: 85,
  },
  {
    id: "cert-019",
    certificateId: "CERT-EDU-10263",
    verificationCode: "VERIFY-784539",
    verificationStatus: "verified",
    studentId: "stu-019",
    studentName: "Shreya Kapoor",
    studentEmail: "shreya@example.com",
    courseId: "course-019",
    courseName: "Figma for Product Design",
    instructorId: "inst-019",
    instructorName: "Ritika Sood",
    certificateType: "Achievement",
    issueDate: "2026-07-20",
    completionDate: "2026-07-17",
    expiryDate: null,
    score: 90,
    completionPercentage: 97,
    lessonsCompleted: 13,
    totalLessons: 14,
    quizScore: 91,
    assignmentScore: 89,
    status: "issued",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Figma for Product Design Achievement",
    courseStatus: "Completed",
    courseProgress: 97,
  },
  {
    id: "cert-020",
    certificateId: "CERT-EDU-10264",
    verificationCode: "VERIFY-784540",
    verificationStatus: "revoked",
    studentId: "stu-020",
    studentName: "Rajat Khurana",
    studentEmail: "rajat@example.com",
    courseId: "course-020",
    courseName: "Cybersecurity Bootcamp",
    instructorId: "inst-020",
    instructorName: "Rakesh Singh",
    certificateType: "Professional Certificate",
    issueDate: "2026-07-15",
    completionDate: "2026-07-10",
    expiryDate: "2028-07-10",
    score: 63,
    completionPercentage: 74,
    lessonsCompleted: 18,
    totalLessons: 24,
    quizScore: 68,
    assignmentScore: 58,
    status: "revoked",
    issuedBy: "EduLearn Academy",
    certificateTitle: "Cybersecurity Bootcamp Professional Certificate",
    courseStatus: "Completed",
    courseProgress: 74,
  },
];
