export const staffRoleSummary = {
  "Super Admin": {
    accessLevel: "Platform Administration",
    permissions: 48,
    permissionPreview: [
      "Manage Users",
      "Manage Courses",
      "Manage Enrollments",
      "View Reports",
      "Manage Reviews",
      "Manage Settings",
    ],
  },
  Admin: {
    accessLevel: "Operational Administration",
    permissions: 36,
    permissionPreview: [
      "Manage Users",
      "Manage Courses",
      "Manage Enrollments",
      "View Reports",
      "Manage Reviews",
    ],
  },
  Moderator: {
    accessLevel: "Content Moderation",
    permissions: 24,
    permissionPreview: [
      "Review Content",
      "Moderate Reviews",
      "Approve Courses",
      "Monitor Reports",
    ],
  },
  "Instructor Manager": {
    accessLevel: "Instructor Operations",
    permissions: 22,
    permissionPreview: [
      "Manage Instructors",
      "Review Courses",
      "Adjust Enrollments",
      "Export Instructor Reports",
    ],
  },
  "Content Manager": {
    accessLevel: "Content Administration",
    permissions: 28,
    permissionPreview: [
      "Manage Courses",
      "Manage Categories",
      "Review Content",
      "Approve Learning Assets",
    ],
  },
  "Support Agent": {
    accessLevel: "Support Operations",
    permissions: 18,
    permissionPreview: [
      "View Students",
      "View Enrollments",
      "Manage Support Requests",
      "Export Support Reports",
    ],
  },
};

export const adminStaff = [
  {
    id: "STF-1001",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    jobTitle: "Platform Administrator",
    role: "Super Admin",
    status: "Active",
    joinedAt: "2026-01-12",
    lastActive: "2026-10-03",
    avatar: "SJ",
    department: "Administration",
    phone: "+1 555 010 1001",
    permissions: 48,
    accessLevel: "Platform Administration",
  },
  {
    id: "STF-1002",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    jobTitle: "Operations Lead",
    role: "Admin",
    status: "Active",
    joinedAt: "2026-02-18",
    lastActive: "2026-10-02",
    avatar: "MC",
    department: "Operations",
    phone: "+1 555 010 1002",
    permissions: 36,
    accessLevel: "Operational Administration",
  },
  {
    id: "STF-1003",
    name: "Priya Nair",
    email: "priya.nair@example.com",
    jobTitle: "Content Reviewer",
    role: "Moderator",
    status: "Active",
    joinedAt: "2026-03-05",
    lastActive: "2026-10-01",
    avatar: "PN",
    department: "Quality Assurance",
    phone: "+1 555 010 1003",
    permissions: 24,
    accessLevel: "Content Moderation",
  },
  {
    id: "STF-1004",
    name: "Daniel Brooks",
    email: "daniel.brooks@example.com",
    jobTitle: "Instructor Success Manager",
    role: "Instructor Manager",
    status: "Active",
    joinedAt: "2026-04-08",
    lastActive: "2026-09-28",
    avatar: "DB",
    department: "Instructor Success",
    phone: "+1 555 010 1004",
    permissions: 22,
    accessLevel: "Instructor Operations",
  },
  {
    id: "STF-1005",
    name: "Aisha Rahman",
    email: "aisha.rahman@example.com",
    jobTitle: "Learning Content Manager",
    role: "Content Manager",
    status: "Invited",
    joinedAt: "2026-05-11",
    lastActive: "Never",
    avatar: "AR",
    department: "Learning Design",
    phone: "+1 555 010 1005",
    permissions: 28,
    accessLevel: "Content Administration",
  },
  {
    id: "STF-1006",
    name: "Lucas Nguyen",
    email: "lucas.nguyen@example.com",
    jobTitle: "Support Specialist",
    role: "Support Agent",
    status: "Active",
    joinedAt: "2026-05-25",
    lastActive: "2026-10-03",
    avatar: "LN",
    department: "Support",
    phone: "+1 555 010 1006",
    permissions: 18,
    accessLevel: "Support Operations",
  },
  {
    id: "STF-1007",
    name: "Emma Patel",
    email: "emma.patel@example.com",
    jobTitle: "Administrative Analyst",
    role: "Admin",
    status: "Suspended",
    joinedAt: "2026-02-09",
    lastActive: "2026-08-18",
    avatar: "EP",
    department: "Administration",
    phone: "+1 555 010 1007",
    permissions: 36,
    accessLevel: "Operational Administration",
  },
  {
    id: "STF-1008",
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    jobTitle: "Community Manager",
    role: "Moderator",
    status: "Inactive",
    joinedAt: "2026-06-02",
    lastActive: "2026-09-14",
    avatar: "OM",
    department: "Community",
    phone: "+1 555 010 1008",
    permissions: 24,
    accessLevel: "Content Moderation",
  },
  {
    id: "STF-1009",
    name: "Noah Davis",
    email: "noah.davis@example.com",
    jobTitle: "Faculty Operations Manager",
    role: "Instructor Manager",
    status: "Invited",
    joinedAt: "2026-06-29",
    lastActive: "Never",
    avatar: "ND",
    department: "Faculty Operations",
    phone: "+1 555 010 1009",
    permissions: 22,
    accessLevel: "Instructor Operations",
  },
  {
    id: "STF-1010",
    name: "Sophia Wilson",
    email: "sophia.wilson@example.com",
    jobTitle: "Support Lead",
    role: "Support Agent",
    status: "Active",
    joinedAt: "2026-03-21",
    lastActive: "2026-10-02",
    avatar: "SW",
    department: "Support",
    phone: "+1 555 010 1010",
    permissions: 18,
    accessLevel: "Support Operations",
  },
  {
    id: "STF-1011",
    name: "Ethan Green",
    email: "ethan.green@example.com",
    jobTitle: "Program Operations Analyst",
    role: "Admin",
    status: "Inactive",
    joinedAt: "2026-07-14",
    lastActive: "2026-09-22",
    avatar: "EG",
    department: "Operations",
    phone: "+1 555 010 1011",
    permissions: 36,
    accessLevel: "Operational Administration",
  },
  {
    id: "STF-1012",
    name: "Maya Thompson",
    email: "maya.thompson@example.com",
    jobTitle: "Course Quality Lead",
    role: "Content Manager",
    status: "Active",
    joinedAt: "2026-04-24",
    lastActive: "2026-10-01",
    avatar: "MT",
    department: "Learning Design",
    phone: "+1 555 010 1012",
    permissions: 28,
    accessLevel: "Content Administration",
  },
  {
    id: "STF-1013",
    name: "Harper Lee",
    email: "harper.lee@example.com",
    jobTitle: "Enrollment Coordinator",
    role: "Support Agent",
    status: "Invited",
    joinedAt: "2026-08-15",
    lastActive: "Never",
    avatar: "HL",
    department: "Student Success",
    phone: "+1 555 010 1013",
    permissions: 18,
    accessLevel: "Support Operations",
  },
  {
    id: "STF-1014",
    name: "Rohan Kapoor",
    email: "rohan.kapoor@example.com",
    jobTitle: "Reporting Specialist",
    role: "Moderator",
    status: "Active",
    joinedAt: "2026-06-17",
    lastActive: "2026-10-03",
    avatar: "RK",
    department: "Reporting",
    phone: "+1 555 010 1014",
    permissions: 24,
    accessLevel: "Content Moderation",
  },
  {
    id: "STF-1015",
    name: "Liam Foster",
    email: "liam.foster@example.com",
    jobTitle: "Platform Security Analyst",
    role: "Super Admin",
    status: "Active",
    joinedAt: "2026-01-30",
    lastActive: "2026-10-02",
    avatar: "LF",
    department: "Security",
    phone: "+1 555 010 1015",
    permissions: 48,
    accessLevel: "Platform Administration",
  },
];

export const staffActivityTemplates = [
  "Logged into Admin Dashboard",
  "Reviewed student account",
  "Updated course approval",
  "Updated category",
  "Reviewed platform reports",
  "Reviewed instructor profile",
  "Moderated student feedback",
  "Resolved support ticket",
];
