export const assignments = [
  {
    id: "react-project-01",
    courseSlug: "react-nextjs-complete-course",
    lessonId: "lesson-07",
    title: "Build a Responsive React Dashboard",
    description:
      "Build a responsive student dashboard using React and Tailwind CSS. The project should include reusable components, responsive layouts, accessible forms, and clean component architecture.",
    type: "project",
    dueDate: "2026-10-20",
    dueDateLabel: "October 20, 2026",
    deadlineStatus: "Due Soon",
    maxMarks: 100,
    estimatedTime: "4 hours",
    attemptsAllowed: 2,
    attemptsUsed: 0,
    allowedFileTypes: ["application/zip", "application/pdf", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    allowedExtensions: [".zip", ".pdf", ".docx"],
    maxFileSizeMB: 10,
    requiresTextResponse: true,
    requiresFile: true,
    status: "not-submitted",
    submissionType: "Project File + Description",
    sectionTitle: "React Projects",
    requirements: [
      "Responsive design across desktop, tablet, and mobile",
      "Reusable React components",
      "Mobile navigation and touch-friendly controls",
      "Client-side form validation",
      "Accessible UI patterns and keyboard support",
      "Clean folder structure and maintainable code",
    ],
    objectives: [
      "Build reusable React components.",
      "Create responsive layouts.",
      "Manage component state.",
      "Apply Tailwind CSS.",
      "Structure a frontend project professionally.",
    ],
    instructions:
      "Create a polished dashboard interface that matches the EduLearn design language. Include a summary panel, data cards, navigation, and a responsive layout. Explain the structure of your implementation and document any tradeoffs in your written submission.",
    resources: [
      { label: "React Documentation", url: "https://react.dev/" },
      { label: "Tailwind CSS Documentation", url: "https://tailwindcss.com/docs" },
      { label: "Course Lesson Notes", url: "https://example.com/course-notes" },
    ],
    textResponseMinLength: 40,
    textResponseMaxLength: 2000,
    submissionLabel: "Your Submission",
    feedback: null,
  },
  {
    id: "react-api-integration",
    courseSlug: "react-nextjs-complete-course",
    lessonId: "lesson-05",
    title: "Build a Next.js API Integration",
    description:
      "Integrate a mock API, handle loading states, and present data clearly in a clean dashboard experience. The final result should be responsive and production-minded.",
    type: "project",
    dueDate: "2026-10-15",
    dueDateLabel: "October 15, 2026",
    deadlineStatus: "Submitted",
    maxMarks: 100,
    estimatedTime: "3 hours",
    attemptsAllowed: 2,
    attemptsUsed: 1,
    allowedFileTypes: ["application/zip", "application/pdf"],
    allowedExtensions: [".zip", ".pdf"],
    maxFileSizeMB: 10,
    requiresTextResponse: true,
    requiresFile: true,
    status: "submitted",
    submissionType: "Project File + Description",
    sectionTitle: "React Fundamentals",
    requirements: [
      "Fetch and render remote data safely",
      "Handle loading and error states",
      "Use reusable UI sections",
      "Follow accessible form and button patterns",
      "Keep code readable and modular",
    ],
    objectives: [
      "Work with API-driven data flows.",
      "Create loading and empty states.",
      "Apply state management patterns.",
      "Build polished frontend experiences.",
      "Write maintainable component logic.",
    ],
    instructions:
      "Build a small data-driven app that loads mock content from a local endpoint and displays it in a responsive interface. Include thoughtful empty, loading, and error states.",
    resources: [
      { label: "Fetch API Guide", url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API" },
      { label: "Course Lesson Notes", url: "https://example.com/api-notes" },
    ],
    textResponseMinLength: 50,
    textResponseMaxLength: 2000,
    submissionLabel: "Your Submission",
    submittedAt: "October 15, 2026",
    submittedFileName: "react-api-integration.zip",
    submittedFileSize: "4.5 MB",
    textResponse: "I structured the app around a clean data-fetching layer, showed loading states while data was being fetched, and focused on strong accessibility patterns in the cards and buttons.",
    feedback: null,
  },
  {
    id: "react-capstone",
    courseSlug: "react-nextjs-complete-course",
    lessonId: "lesson-07",
    title: "Capstone Frontend Project",
    description:
      "Ship a polished portfolio-ready project that showcases your frontend and design skills. The project should feel confident, responsive, and thoughtfully structured.",
    type: "project",
    dueDate: "2026-09-30",
    dueDateLabel: "September 30, 2026",
    deadlineStatus: "Graded",
    maxMarks: 100,
    estimatedTime: "6 hours",
    attemptsAllowed: 2,
    attemptsUsed: 1,
    allowedFileTypes: ["application/zip", "application/pdf", "image/png", "image/jpeg"],
    allowedExtensions: [".zip", ".pdf", ".png", ".jpg", ".jpeg"],
    maxFileSizeMB: 10,
    requiresTextResponse: true,
    requiresFile: true,
    status: "graded",
    submissionType: "Project File + Description",
    sectionTitle: "Next.js Foundations",
    requirements: [
      "Production-ready UI polish",
      "Responsive design and mobile-first layout",
      "Well-structured components and clean code",
      "Readable, accessible interactions",
      "Clear final presentation and thought process",
    ],
    objectives: [
      "Assemble a portfolio-grade frontend build.",
      "Manage multiple UI states cleanly.",
      "Design for clarity and usability.",
      "Reflect on tradeoffs and decisions.",
      "Ship a polished final output.",
    ],
    instructions:
      "Create a complete frontend experience that demonstrates solid UX, strong layout decisions, and implementable component patterns. Include a short summary of your approach and the reasoning behind your implementation choices.",
    resources: [
      { label: "Design System Patterns", url: "https://www.nngroup.com/articles/" },
      { label: "Frontend Performance Checklist", url: "https://web.dev/learn" },
    ],
    textResponseMinLength: 80,
    textResponseMaxLength: 2500,
    submissionLabel: "Your Submission",
    submittedAt: "October 05, 2026",
    submittedFileName: "frontend-capstone.zip",
    submittedFileSize: "8.2 MB",
    textResponse: "The project was designed around reusable UI blocks, a consistent spacing system, and strong hierarchy. I focused on careful state handling and keeping the implementation organized enough to scale.",
    score: 86,
    percentage: 86,
    feedback: "Strong implementation. Improve component abstraction and loading states.",
    gradedAt: "October 09, 2026",
  },
];

export default assignments;
