export const HOME_COURSES = [
  {
    _id: "react-nextjs-guide",
    slug: "react-nextjs-complete-guide",
    title: "React & Next.js Complete Guide",
    category: "Web Development",
    categoryId: { name: "Web Development" },
    instructor: "John Doe",
    instructorId: { name: "John Doe" },
    thumbnail:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80&auto=format&fit=crop",
    rating: 4.8,
    reviewCount: 120,
    price: 49,
    discountPrice: null,
    duration: 40,
    level: "All Levels",
  },
  {
    _id: "uiux-design-masterclass",
    slug: "uiux-design-masterclass",
    title: "UI/UX Design Masterclass",
    category: "Design",
    categoryId: { name: "Design" },
    instructor: "Sarah Lee",
    instructorId: { name: "Sarah Lee" },
    thumbnail:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80&auto=format&fit=crop",
    rating: 4.7,
    reviewCount: 86,
    price: 39,
    discountPrice: null,
    duration: 28,
    level: "Beginner",
  },
  {
    _id: "python-for-beginners",
    slug: "python-for-beginners",
    title: "Python for Beginners",
    category: "Programming",
    categoryId: { name: "Programming" },
    instructor: "Emily Watson",
    instructorId: { name: "Emily Watson" },
    thumbnail:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80&auto=format&fit=crop",
    rating: 4.9,
    reviewCount: 204,
    price: 29,
    discountPrice: null,
    duration: 22,
    level: "Beginner",
  },
  {
    _id: "digital-marketing-complete",
    slug: "digital-marketing-complete-course",
    title: "Digital Marketing Complete Course",
    category: "Marketing",
    categoryId: { name: "Marketing" },
    instructor: "Michael Chen",
    instructorId: { name: "Michael Chen" },
    thumbnail:
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&q=80&auto=format&fit=crop",
    rating: 4.6,
    reviewCount: 93,
    price: 45,
    discountPrice: null,
    duration: 35,
    level: "All Levels",
  },
];

export const HOME_STATS = [
  { value: "10K+", label: "Active Students" },
  { value: "500+", label: "Expert Instructors" },
  { value: "1.2K+", label: "Online Courses" },
  { value: "4.8/5", label: "Average Rating" },
];
