export const instructorDashboard = {
  instructor: {
    id: "instructor-001",
    name: "John Doe",
    title: "Senior Full Stack Developer",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=faces",
    rating: 4.9,
    students: 2450,
    courses: 12,
  },
  stats: {
    totalCourses: 12,
    publishedCourses: 9,
    draftCourses: 3,
    totalStudents: 2450,
    totalEarnings: 482000,
    averageRating: 4.9,
    courseCompletionRate: 82,
  },
  revenue: {
    currency: "INR",
    labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    monthly: [32000, 41000, 38500, 46000, 52000, 48500],
  },
  courses: [
    {
      name: "Full Stack Web Development",
      students: 1250,
      rating: 4.9,
      completion: 82,
      revenue: 185000,
      status: "Published",
    },
    {
      name: "React & Next.js Masterclass",
      students: 820,
      rating: 4.8,
      completion: 76,
      revenue: 120000,
      status: "Published",
    },
    {
      name: "JavaScript Fundamentals",
      students: 380,
      rating: 4.7,
      completion: 88,
      revenue: 58000,
      status: "Draft",
    },
    {
      name: "Advanced TypeScript",
      students: 290,
      rating: 4.9,
      completion: 68,
      revenue: 42000,
      status: "Published",
    },
  ],
  recentEnrollments: [
    {
      id: "enrollment-1",
      name: "Sarah Wilson",
      course: "Full Stack Web Development",
      date: "September 30, 2026",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=faces",
    },
    {
      id: "enrollment-2",
      name: "Michael Chen",
      course: "React & Next.js Masterclass",
      date: "September 28, 2026",
      avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=faces",
    },
    {
      id: "enrollment-3",
      name: "Emily Davis",
      course: "JavaScript Fundamentals",
      date: "September 24, 2026",
      avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=faces",
    },
    {
      id: "enrollment-4",
      name: "David Kumar",
      course: "Advanced TypeScript",
      date: "September 22, 2026",
      avatar: "https://images.unsplash.com/photo-1504593811423-6dd665756598?w=400&h=400&fit=crop&crop=faces",
    },
    {
      id: "enrollment-5",
      name: "Priya Nair",
      course: "React & Next.js Masterclass",
      date: "September 12, 2026",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=faces",
    },
  ],
  recentActivity: [
    { id: "activity-1", text: "Michael enrolled in React & Next.js Masterclass.", time: "2 hours ago", icon: "users" },
    { id: "activity-2", text: "Sarah submitted Assignment #4.", time: "5 hours ago", icon: "assignment" },
    { id: "activity-3", text: "David completed JavaScript Fundamentals.", time: "Yesterday", icon: "check" },
    { id: "activity-4", text: "Emily left a 5-star review.", time: "2 days ago", icon: "star" },
  ],
  upcomingTasks: [
    { id: "task-1", title: "Review pending assignments", count: 3, href: "/instructor/assignments" },
    { id: "task-2", title: "Respond to student questions", count: 5, href: "/instructor/messages" },
    { id: "task-3", title: "Review new course feedback", count: 8, href: "/instructor/reviews" },
    { id: "task-4", title: "Update course content", count: 2, href: "/instructor/courses" },
  ],
  pendingAssignments: [
    {
      id: "assignment-1",
      name: "React Hooks Assignment",
      course: "React & Next.js Masterclass",
      submissions: 12,
      dueDate: "Oct 3",
    },
    {
      id: "assignment-2",
      name: "API Design Challenge",
      course: "Full Stack Web Development",
      submissions: 8,
      dueDate: "Oct 8",
    },
  ],
  studentOverview: {
    totalStudents: 2450,
    activeLearners: 1820,
    completedCourses: 1240,
    averageCompletion: 78,
  },
  ratingSummary: {
    average: 4.9,
    totalReviews: 384,
    distribution: [
      { label: "5 Stars", count: 92 },
      { label: "4 Stars", count: 6 },
      { label: "3 Stars", count: 1 },
      { label: "2 Stars", count: 0.5 },
      { label: "1 Star", count: 0.5 },
    ],
  },
  quickActions: [
    { label: "Create Course", href: "/instructor/courses/create", icon: "plus" },
    { label: "Manage Courses", href: "/instructor/courses", icon: "book" },
    { label: "View Students", href: "/instructor/students", icon: "users" },
    { label: "View Assignments", href: "/instructor/assignments", icon: "clipboard" },
    { label: "View Reviews", href: "/instructor/reviews", icon: "star" },
    { label: "View Analytics", href: "/instructor/analytics", icon: "chart" },
  ],
};

export default instructorDashboard;
