export const instructors = [
  {
    id: "instructor-1",
    slug: "sarah-johnson",
    name: "Sarah Johnson",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&h=800&fit=crop&crop=faces",
    role: "Senior Full Stack Engineer",
    bio: "Sarah builds and teaches production-grade web apps with a focus on clear architecture, strong product thinking, and modern frontend workflows.",
    expertise: ["React", "Next.js", "JavaScript", "TypeScript"],
    rating: 4.9,
    reviewCount: 245,
    studentCount: 42500,
    courseCount: 8,
    category: "Development",
    experience: "12+ years",
    teachingExperience: "8 years",
    location: "New York, USA",
    company: "Former product engineer at Stripe",
    education: ["B.S. in Computer Science", "Google UX & Frontend Certification"],
    highlights: [
      "Built products used by 100K+ learners",
      "Worked across SaaS, ecommerce, and education platforms",
      "Mentored engineering teams shipping customer-facing features",
    ],
    languages: ["English", "Spanish"],
  },
  {
    id: "instructor-2",
    slug: "michael-chen",
    name: "Michael Chen",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=800&fit=crop&crop=faces",
    role: "Lead TypeScript Architect",
    bio: "Michael helps developers create robust, scalable frontends with maintainable systems and strong engineering habits.",
    expertise: ["TypeScript", "Architecture", "JavaScript", "React"],
    rating: 4.8,
    reviewCount: 198,
    studentCount: 28900,
    courseCount: 6,
    category: "Development",
    experience: "10+ years",
    teachingExperience: "6 years",
    location: "Singapore",
    company: "Enterprise platform consultant",
    education: ["M.S. in Software Engineering", "AWS Solutions Architect"],
    highlights: [
      "Led TypeScript transformations for Fortune 500 teams",
      "Authored internal engineering standards for large orgs",
      "Specializes in developer experience and product velocity",
    ],
    languages: ["English", "Mandarin"],
  },
  {
    id: "instructor-3",
    slug: "emily-rodriguez",
    name: "Emily Rodriguez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=800&fit=crop&crop=faces",
    role: "JavaScript Educator",
    bio: "Emily teaches practical coding through real-world projects, turning beginners into confident builders with a strong fundamentals-first approach.",
    expertise: ["JavaScript", "Web Development", "Coding Fundamentals", "Frontend"],
    rating: 4.9,
    reviewCount: 264,
    studentCount: 61200,
    courseCount: 11,
    category: "Development",
    experience: "9+ years",
    teachingExperience: "7 years",
    location: "Austin, USA",
    company: "Former bootcamp lead",
    education: ["B.A. in Computer Science", "UX Bootcamp Certification"],
    highlights: [
      "Helped 20,000+ students launch career transitions",
      "Known for making complex topics approachable",
      "Built project-based curriculum for beginner devs",
    ],
    languages: ["English", "Spanish"],
  },
  {
    id: "instructor-4",
    slug: "david-williams",
    name: "David Williams",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&h=800&fit=crop&crop=faces",
    role: "Principal Product Designer",
    bio: "David blends product design, UX research, and storytelling to help students create interfaces that feel intuitive and conversion-ready.",
    expertise: ["UI/UX", "Figma", "Design Systems", "Product Design"],
    rating: 4.8,
    reviewCount: 171,
    studentCount: 18300,
    courseCount: 5,
    category: "Design",
    experience: "11+ years",
    teachingExperience: "5 years",
    location: "London, UK",
    company: "Design advisory for SaaS teams",
    education: ["B.A. in Visual Communication", "Interaction Design Certification"],
    highlights: [
      "Designed experiences adopted by SaaS teams worldwide",
      "Award-winning portfolio across startup and enterprise work",
      "Focused on user-centered product decisions",
    ],
    languages: ["English", "French"],
  },
  {
    id: "instructor-5",
    slug: "priya-patel",
    name: "Priya Patel",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=800&fit=crop&crop=faces",
    role: "Design Systems Lead",
    bio: "Priya teaches design systems that scale, with a strong focus on accessibility, speed, and team alignment across product organizations.",
    expertise: ["Design Systems", "Accessibility", "Figma", "UI/UX"],
    rating: 4.9,
    reviewCount: 205,
    studentCount: 12800,
    courseCount: 4,
    category: "Design",
    experience: "9+ years",
    teachingExperience: "4 years",
    location: "Toronto, Canada",
    company: "Senior design systems consultant",
    education: ["B.Des. in Interaction Design", "DesignOps Certification"],
    highlights: [
      "Created component libraries used by cross-functional product teams",
      "Wrote accessibility standards for enterprise apps",
      "Helps teams move from chaos to consistency",
    ],
    languages: ["English", "Hindi"],
  },
  {
    id: "instructor-6",
    slug: "james-thompson",
    name: "James Thompson",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&h=800&fit=crop&crop=faces",
    role: "Head of Growth Marketing",
    bio: "James teaches marketing systems that connect customer insight, channel strategy, and data-driven experimentation into sustainable growth loops.",
    expertise: ["Marketing", "Growth", "Analytics", "Content Strategy"],
    rating: 4.8,
    reviewCount: 216,
    studentCount: 24600,
    courseCount: 7,
    category: "Marketing",
    experience: "13+ years",
    teachingExperience: "6 years",
    location: "Chicago, USA",
    company: "SaaS growth advisor",
    education: ["B.A. in Marketing", "Growth Strategy Fellowship"],
    highlights: [
      "Grew three SaaS products to seven-figure pipelines",
      "Built content engines that scaled acquisition sustainably",
      "Translates strategy into measurable execution",
    ],
    languages: ["English"],
  },
  {
    id: "instructor-7",
    slug: "olivia-martinez",
    name: "Olivia Martinez",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&h=800&fit=crop&crop=faces",
    role: "SEO & Content Consultant",
    bio: "Olivia helps creators and teams build search visibility, editorial systems, and content strategies that earn traffic and trust.",
    expertise: ["SEO", "Content Strategy", "Analytics", "Marketing"],
    rating: 4.7,
    reviewCount: 194,
    studentCount: 15200,
    courseCount: 5,
    category: "Marketing",
    experience: "8+ years",
    teachingExperience: "5 years",
    location: "Barcelona, Spain",
    company: "Growth content consultant",
    education: ["B.A. in Communications", "SEO Certification"],
    highlights: [
      "Helped brands rank on page one for high-intent keywords",
      "Builds easy-to-follow content systems for lean teams",
      "Combines content strategy with attribution insight",
    ],
    languages: ["English", "Spanish"],
  },
  {
    id: "instructor-8",
    slug: "daniel-kim",
    name: "Daniel Kim",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=800&fit=crop&crop=faces",
    role: "Data Science Mentor",
    bio: "Daniel brings real-world analytics and machine learning experience to students who want to move from theory to production-ready problem solving.",
    expertise: ["Data Science", "Python", "Machine Learning", "SQL"],
    rating: 4.9,
    reviewCount: 228,
    studentCount: 24800,
    courseCount: 9,
    category: "Data Science",
    experience: "14+ years",
    teachingExperience: "7 years",
    location: "Seoul, South Korea",
    company: "Former ML solutions lead",
    education: ["M.S. in Applied Statistics", "Google Cloud ML Certification"],
    highlights: [
      "Built data products across healthcare, fintech, and commerce",
      "Teaches from first principles with business context",
      "Guides learners from curiosity to portfolio-ready projects",
    ],
    languages: ["English", "Korean"],
  },
];

export const instructorCategories = [
  "Development",
  "Design",
  "Marketing",
  "Data Science",
];

export const instructorExpertiseOptions = [
  "React",
  "Next.js",
  "JavaScript",
  "TypeScript",
  "UI/UX",
  "Figma",
  "Marketing",
  "Growth",
  "Analytics",
  "Data Science",
  "Python",
  "Machine Learning",
  "Design Systems",
  "SEO",
  "Content Strategy",
  "SQL",
];

export default instructors;
