export const quizzes = [
  {
    id: "javascript-basics",
    slug: "javascript-basics",
    courseSlug: "javascript-fundamentals-from-zero-to-hero",
    lessonId: "lesson-05",
    title: "JavaScript Fundamentals Quiz",
    description: "Test your understanding of JavaScript fundamentals, variables, functions, and core browser behavior.",
    timeLimit: 15,
    passingScore: 70,
    attemptsAllowed: 2,
    requireAllQuestions: false,
    questions: [
      {
        id: "q1",
        question: "Which keyword is used to declare a constant in JavaScript?",
        type: "single-choice",
        options: [
          { id: "a", text: "var" },
          { id: "b", text: "let" },
          { id: "c", text: "const" },
          { id: "d", text: "static" },
        ],
        correctAnswer: "c",
        explanation: "const creates a binding that cannot be reassigned to a new value.",
      },
      {
        id: "q2",
        question: "What does the === operator compare?",
        type: "single-choice",
        options: [
          { id: "a", text: "Value only" },
          { id: "b", text: "Reference only" },
          { id: "c", text: "Type and value" },
          { id: "d", text: "Memory address only" },
        ],
        correctAnswer: "c",
        explanation: "=== checks both the value and type, unlike == which performs coercion.",
      },
      {
        id: "q3",
        question: "Which method converts a JavaScript value to a string?",
        type: "single-choice",
        options: [
          { id: "a", text: "toJSON()" },
          { id: "b", text: "String(value)" },
          { id: "c", text: "parseFloat()" },
          { id: "d", text: "Number(value)" },
        ],
        correctAnswer: "b",
        explanation: "String(value) converts a value into its string representation.",
      },
      {
        id: "q4",
        question: "How do you define a function declaration?",
        type: "single-choice",
        options: [
          { id: "a", text: "function greet() {}" },
          { id: "b", text: "const greet = () => {}" },
          { id: "c", text: "let greet = function() {}" },
          { id: "d", text: "All of the above" },
        ],
        correctAnswer: "d",
        explanation: "All of these are valid ways to define functions, depending on the style and needs of the code.",
      },
      {
        id: "q5",
        question: "Which array method returns a new array with elements that pass a test?",
        type: "single-choice",
        options: [
          { id: "a", text: "map()" },
          { id: "b", text: "filter()" },
          { id: "c", text: "reduce()" },
          { id: "d", text: "forEach()" },
        ],
        correctAnswer: "b",
        explanation: "filter() creates a new array with all elements that satisfy the provided condition.",
      },
      {
        id: "q6",
        question: "What is the result of typeof null in JavaScript?",
        type: "single-choice",
        options: [
          { id: "a", text: "null" },
          { id: "b", text: "object" },
          { id: "c", text: "undefined" },
          { id: "d", text: "boolean" },
        ],
        correctAnswer: "b",
        explanation: "Historically, typeof null returns 'object', which is a known JavaScript quirk.",
      },
      {
        id: "q7",
        question: "Which statement is used to stop a loop early?",
        type: "single-choice",
        options: [
          { id: "a", text: "continue" },
          { id: "b", text: "return" },
          { id: "c", text: "break" },
          { id: "d", text: "yield" },
        ],
        correctAnswer: "c",
        explanation: "break exits the current loop or switch statement immediately.",
      },
      {
        id: "q8",
        question: "Which method adds an element to the end of an array?",
        type: "single-choice",
        options: [
          { id: "a", text: "push()" },
          { id: "b", text: "unshift()" },
          { id: "c", text: "splice()" },
          { id: "d", text: "concat()" },
        ],
        correctAnswer: "a",
        explanation: "push() appends one or more elements to the end of an array and returns the new length.",
      },
      {
        id: "q9",
        question: "What does the setTimeout function do?",
        type: "single-choice",
        options: [
          { id: "a", text: "Runs code immediately" },
          { id: "b", text: "Runs code after a delay" },
          { id: "c", text: "Stops all timers" },
          { id: "d", text: "Pauses execution" },
        ],
        correctAnswer: "b",
        explanation: "setTimeout schedules a function to run once after a specified delay.",
      },
      {
        id: "q10",
        question: "Which property is used to access the length of a string?",
        type: "single-choice",
        options: [
          { id: "a", text: ".size" },
          { id: "b", text: ".count" },
          { id: "c", text: ".length" },
          { id: "d", text: ".total" },
        ],
        correctAnswer: "c",
        explanation: "Strings in JavaScript expose a length property that returns the number of characters.",
      },
    ],
  },
  {
    id: "react-fundamentals",
    slug: "react-fundamentals",
    courseSlug: "react-nextjs-complete-course",
    lessonId: "lesson-04",
    title: "React Fundamentals Quiz",
    description: "Check your understanding of components, state, events, and rendering in React.",
    timeLimit: 12,
    passingScore: 75,
    attemptsAllowed: 2,
    requireAllQuestions: false,
    questions: [
      {
        id: "rq1",
        question: "What is the purpose of JSX?",
        type: "single-choice",
        options: [
          { id: "a", text: "A runtime database format" },
          { id: "b", text: "A syntax extension for describing UI in JavaScript" },
          { id: "c", text: "A CSS preprocessor" },
          { id: "d", text: "A Node.js server framework" },
        ],
        correctAnswer: "b",
        explanation: "JSX is a syntax extension that lets you write UI markup in a JavaScript-friendly way.",
      },
      {
        id: "rq2",
        question: "Which hook is used to manage local state in a function component?",
        type: "single-choice",
        options: [
          { id: "a", text: "useEffect" },
          { id: "b", text: "useState" },
          { id: "c", text: "useMemo" },
          { id: "d", text: "useContext" },
        ],
        correctAnswer: "b",
        explanation: "useState allows function components to store and update state between renders.",
      },
      {
        id: "rq3",
        question: "What is a prop in React?",
        type: "single-choice",
        options: [
          { id: "a", text: "A method for query parameters" },
          { id: "b", text: "A value passed to a component from its parent" },
          { id: "c", text: "A DOM event listener" },
          { id: "d", text: "An internal CSS variable" },
        ],
        correctAnswer: "b",
        explanation: "Props are inputs passed to a component so it can render dynamic content or behavior.",
      },
      {
        id: "rq4",
        question: "What do event handlers in React typically receive?",
        type: "single-choice",
        options: [
          { id: "a", text: "A server response" },
          { id: "b", text: "An event object" },
          { id: "c", text: "A CSS module" },
          { id: "d", text: "A database result" },
        ],
        correctAnswer: "b",
        explanation: "React event handlers usually receive the browser event object so you can inspect the interaction.",
      },
      {
        id: "rq5",
        question: "Which pattern is commonly used to render lists in React?",
        type: "single-choice",
        options: [
          { id: "a", text: "map()" },
          { id: "b", text: "for...of" },
          { id: "c", text: "reduce()" },
          { id: "d", text: "find()" },
        ],
        correctAnswer: "a",
        explanation: "map() is the standard pattern for rendering arrays into collections of JSX elements.",
      },
      {
        id: "rq6",
        question: "What is the purpose of a key prop in a list?",
        type: "single-choice",
        options: [
          { id: "a", text: "To store network data" },
          { id: "b", text: "To help React identify stable list items" },
          { id: "c", text: "To style the list" },
          { id: "d", text: "To represent form validation" },
        ],
        correctAnswer: "b",
        explanation: "Keys help React track which items changed, were added, or were removed across renders.",
      },
      {
        id: "rq7",
        question: "What is the correct way to update state based on the previous value?",
        type: "single-choice",
        options: [
          { id: "a", text: "setCount(count + 1)" },
          { id: "b", text: "setCount((prev) => prev + 1)" },
          { id: "c", text: "count++" },
          { id: "d", text: "updateCount()" },
        ],
        correctAnswer: "b",
        explanation: "Using a functional update ensures the latest state is used when updates depend on the current value.",
      },
      {
        id: "rq8",
        question: "Which hook is used to run code after render?",
        type: "single-choice",
        options: [
          { id: "a", text: "useLayoutEffect" },
          { id: "b", text: "useState" },
          { id: "c", text: "useEffect" },
          { id: "d", text: "useReducer" },
        ],
        correctAnswer: "c",
        explanation: "useEffect is used for side effects after rendering, such as fetching or subscriptions.",
      },
      {
        id: "rq9",
        question: "What happens when a component receives new props?",
        type: "single-choice",
        options: [
          { id: "a", text: "The component is destroyed" },
          { id: "b", text: "The component re-renders with new values" },
          { id: "c", text: "The DOM is reset" },
          { id: "d", text: "The code stops executing" },
        ],
        correctAnswer: "b",
        explanation: "React re-renders the component so it can display the latest prop values and updated UI.",
      },
      {
        id: "rq10",
        question: "Which concept allows a child component to receive values from its parent?",
        type: "single-choice",
        options: [
          { id: "a", text: "State" },
          { id: "b", text: "Refs" },
          { id: "c", text: "Props" },
          { id: "d", text: "Context" },
        ],
        correctAnswer: "c",
        explanation: "Props are the mechanism by which parent components pass data to children.",
      },
    ],
  },
];

export const quizLookup = Object.fromEntries(
  quizzes.flatMap((quiz) => [
    [quiz.id, quiz],
    [quiz.slug, quiz],
  ])
);

export default quizzes;
