export const studentProfile = {
  id: "student-demo-001",
  firstName: "Vandana",
  lastName: "Sharma",
  email: "vandana@example.com",
  phone: "+91 98765 43210",
  location: "Noida, India",
  dateOfBirth: "2000-01-15",
  gender: "Prefer not to say",
  avatar: null,
  bio: "Passionate learner exploring modern web development, JavaScript, React, Next.js, Node.js, and software engineering.",
  role: "Student",
  memberSince: "2026-01-10",
  accountStatus: "Active",
  emailVerified: true,
  skills: ["JavaScript", "React", "Next.js", "Node.js", "MongoDB", "Tailwind CSS"],
  learning: {
    goal: "Become a Full Stack Developer",
    level: "Intermediate",
    preferredStyle: "Video + Practical Projects",
    weeklyGoal: 10,
    preferredCategories: ["Web Development", "JavaScript", "Backend Development"],
  },
  statistics: {
    enrolledCourses: 12,
    completedCourses: 4,
    completedLessons: 148,
    learningHours: 86.5,
    certificates: 4,
    averageQuizScore: 84,
  },
  recentActivity: [
    { id: "activity-1", title: "Profile information updated", date: "Today", type: "profile" },
    { id: "activity-2", title: "Completed JavaScript Functions lesson", date: "Yesterday", type: "lesson" },
    { id: "activity-3", title: "Earned JavaScript Masterclass certificate", date: "3 days ago", type: "certificate" },
    { id: "activity-4", title: "Completed React assessment", date: "1 week ago", type: "quiz" },
  ],
};